// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               unknown
// source: v1/crypto.proto

// @ts-nocheck
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf";
import { messageTypeRegistry } from "../typeRegistry";

export const protobufPackage = "synch.v1";

/**
 * SYNCH 心契协议 — 加密原语
 * 包含：密钥对、签名、加密载荷、密钥交换、Vault 密钥封装
 */

/** KeyAlgorithm 支持的密钥/加密算法 */
export enum KeyAlgorithm {
  KEY_ALGORITHM_UNSPECIFIED = 0,
  /** KEY_ALGORITHM_ED25519 - 数字签名 (身份) */
  KEY_ALGORITHM_ED25519 = 1,
  /** KEY_ALGORITHM_X25519 - 密钥交换 (ECDH) */
  KEY_ALGORITHM_X25519 = 2,
  /** KEY_ALGORITHM_AES_256_GCM - 对称加密 (数据保护) */
  KEY_ALGORITHM_AES_256_GCM = 3,
  /** KEY_ALGORITHM_XCHACHA20 - 对称加密 (备选) */
  KEY_ALGORITHM_XCHACHA20 = 4,
  /** KEY_ALGORITHM_ARGON2ID - 密码派生函数 */
  KEY_ALGORITHM_ARGON2ID = 5,
  /** KEY_ALGORITHM_BLAKE3 - 哈希算法 */
  KEY_ALGORITHM_BLAKE3 = 6,
  UNRECOGNIZED = -1,
}

export function keyAlgorithmFromJSON(object: any): KeyAlgorithm {
  switch (object) {
    case 0:
    case "KEY_ALGORITHM_UNSPECIFIED":
      return KeyAlgorithm.KEY_ALGORITHM_UNSPECIFIED;
    case 1:
    case "KEY_ALGORITHM_ED25519":
      return KeyAlgorithm.KEY_ALGORITHM_ED25519;
    case 2:
    case "KEY_ALGORITHM_X25519":
      return KeyAlgorithm.KEY_ALGORITHM_X25519;
    case 3:
    case "KEY_ALGORITHM_AES_256_GCM":
      return KeyAlgorithm.KEY_ALGORITHM_AES_256_GCM;
    case 4:
    case "KEY_ALGORITHM_XCHACHA20":
      return KeyAlgorithm.KEY_ALGORITHM_XCHACHA20;
    case 5:
    case "KEY_ALGORITHM_ARGON2ID":
      return KeyAlgorithm.KEY_ALGORITHM_ARGON2ID;
    case 6:
    case "KEY_ALGORITHM_BLAKE3":
      return KeyAlgorithm.KEY_ALGORITHM_BLAKE3;
    case -1:
    case "UNRECOGNIZED":
    default:
      return KeyAlgorithm.UNRECOGNIZED;
  }
}

export function keyAlgorithmToJSON(object: KeyAlgorithm): string {
  switch (object) {
    case KeyAlgorithm.KEY_ALGORITHM_UNSPECIFIED:
      return "KEY_ALGORITHM_UNSPECIFIED";
    case KeyAlgorithm.KEY_ALGORITHM_ED25519:
      return "KEY_ALGORITHM_ED25519";
    case KeyAlgorithm.KEY_ALGORITHM_X25519:
      return "KEY_ALGORITHM_X25519";
    case KeyAlgorithm.KEY_ALGORITHM_AES_256_GCM:
      return "KEY_ALGORITHM_AES_256_GCM";
    case KeyAlgorithm.KEY_ALGORITHM_XCHACHA20:
      return "KEY_ALGORITHM_XCHACHA20";
    case KeyAlgorithm.KEY_ALGORITHM_ARGON2ID:
      return "KEY_ALGORITHM_ARGON2ID";
    case KeyAlgorithm.KEY_ALGORITHM_BLAKE3:
      return "KEY_ALGORITHM_BLAKE3";
    case KeyAlgorithm.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** KeyPair 密钥对表示 */
export interface KeyPair {
  $type: "synch.v1.KeyPair";
  /** 公钥 (Ed25519: 32 bytes, X25519: 32 bytes) */
  publicKey: Uint8Array;
  /** 加密后的私钥 (使用主密钥或密码派生密钥加密) */
  encryptedPrivateKey: Uint8Array;
  /** 使用的算法 */
  algorithm: KeyAlgorithm;
  /** 密钥创建时间 (Unix epoch millis) */
  createdAt: number;
  /** 密钥过期时间 (0 = 永不过期) */
  expiresAt: number;
  /** 密钥指纹 (Blake3(public_key)[0:8] 的十六进制表示) */
  fingerprint: string;
}

/** Signature 对数据的 Ed25519 签名 */
export interface Signature {
  $type: "synch.v1.Signature";
  /** 被签名的数据摘要 (通常为 Blake3 hash) */
  dataHash: Uint8Array;
  /** 签名值 (Ed25519: 64 bytes) */
  signatureBytes: Uint8Array;
  /** 签名者的公钥 */
  signerPublicKey: Uint8Array;
  /** 签名时间 */
  signedAt: number;
}

/** EncryptedPayload AES-256-GCM 加密的数据封装 */
export interface EncryptedPayload {
  $type: "synch.v1.EncryptedPayload";
  /** 密文 */
  ciphertext: Uint8Array;
  /** 随机数 / IV (AES-GCM: 12 bytes, XChaCha20: 24 bytes) */
  nonce: Uint8Array;
  /** 发送方公钥 (用于接收方重建共享密钥) */
  senderPublicKey: Uint8Array;
  /** 使用的加密算法 */
  algorithm: KeyAlgorithm;
  /** 附加认证数据 (AAD) 的哈希 (用于验证上下文) */
  aadHash: Uint8Array;
  /** 关联的契约 ID (可选，用于 E2EE 消息) */
  contractId: string;
  /** 棘轮序列号 (用于前向保密) */
  ratchetSeq: number;
  /** 发送方的当前棘轮公钥 (用于 DH 棘轮) */
  ratchetKey: Uint8Array;
  /** 上一条发送链的消息数量 (用于接收端同步) */
  prevChainLength: number;
}

/** KeyExchangeRequest 发起方发送 */
export interface KeyExchangeRequest {
  $type: "synch.v1.KeyExchangeRequest";
  /** 发起方的临时 X25519 公钥 */
  ephemeralPublicKey: Uint8Array;
  /** 发起方的身份公钥 (Ed25519, 用于验证) */
  identityPublicKey: Uint8Array;
  /** 对临时公钥的签名 (证明身份) */
  identityProof:
    | Signature
    | undefined;
  /** 请求时间 */
  timestamp: number;
}

/** KeyExchangeResponse 响应方回复 */
export interface KeyExchangeResponse {
  $type: "synch.v1.KeyExchangeResponse";
  /** 响应方的临时 X25519 公钥 */
  ephemeralPublicKey: Uint8Array;
  /** 响应方的身份公钥 */
  identityPublicKey: Uint8Array;
  /** 对临时公钥的签名 */
  identityProof:
    | Signature
    | undefined;
  /** 用共享密钥加密的确认消息 */
  encryptedConfirmation: EncryptedPayload | undefined;
}

/** VaultKey 描述一个 Vault 的加密密钥 */
export interface VaultKey {
  $type: "synch.v1.VaultKey";
  /** 对应的 Vault ID */
  vaultId: string;
  /** 加密后的 Vault 数据密钥 (用设备密钥或用户主密钥封装) */
  encryptedKeyMaterial: Uint8Array;
  /** 封装使用的算法 */
  wrappingAlgorithm: KeyAlgorithm;
  /** 密钥版本 (轮换时递增) */
  keyVersion: number;
  /** 密钥创建时间 */
  createdAt: number;
  /** 封装者公钥 (知道是哪个密钥加密的) */
  wrappedByPublicKey: Uint8Array;
}

/** SynchCertificate 节点身份证书 — 由信任锚签发 */
export interface SynchCertificate {
  $type: "synch.v1.SynchCertificate";
  /** 证书版本 */
  version: number;
  /** 证书持有者的公钥 */
  subjectPublicKey: Uint8Array;
  /** 持有者节点 ID */
  subjectNodeId: string;
  /** 签发者公钥 */
  issuerPublicKey: Uint8Array;
  /** 签发者对证书内容的签名 */
  issuerSignature:
    | Signature
    | undefined;
  /** 生效时间 */
  validFrom: number;
  /** 过期时间 */
  validUntil: number;
  /** 授予的能力列表 */
  grantedCapabilities: string[];
  /** 允许访问的 Vault ID 列表 (空 = 不限制) */
  allowedVaultIds: string[];
}

function createBaseKeyPair(): KeyPair {
  return {
    $type: "synch.v1.KeyPair",
    publicKey: new Uint8Array(0),
    encryptedPrivateKey: new Uint8Array(0),
    algorithm: 0,
    createdAt: 0,
    expiresAt: 0,
    fingerprint: "",
  };
}

export const KeyPair: MessageFns<KeyPair, "synch.v1.KeyPair"> = {
  $type: "synch.v1.KeyPair" as const,

  encode(message: KeyPair, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.publicKey.length !== 0) {
      writer.uint32(10).bytes(message.publicKey);
    }
    if (message.encryptedPrivateKey.length !== 0) {
      writer.uint32(18).bytes(message.encryptedPrivateKey);
    }
    if (message.algorithm !== 0) {
      writer.uint32(24).int32(message.algorithm);
    }
    if (message.createdAt !== 0) {
      writer.uint32(32).uint64(message.createdAt);
    }
    if (message.expiresAt !== 0) {
      writer.uint32(40).uint64(message.expiresAt);
    }
    if (message.fingerprint !== "") {
      writer.uint32(50).string(message.fingerprint);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): KeyPair {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseKeyPair();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.publicKey = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.encryptedPrivateKey = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.algorithm = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.createdAt = longToNumber(reader.uint64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.expiresAt = longToNumber(reader.uint64());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.fingerprint = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): KeyPair {
    return {
      $type: KeyPair.$type,
      publicKey: isSet(object.publicKey)
        ? bytesFromBase64(object.publicKey)
        : isSet(object.public_key)
        ? bytesFromBase64(object.public_key)
        : new Uint8Array(0),
      encryptedPrivateKey: isSet(object.encryptedPrivateKey)
        ? bytesFromBase64(object.encryptedPrivateKey)
        : isSet(object.encrypted_private_key)
        ? bytesFromBase64(object.encrypted_private_key)
        : new Uint8Array(0),
      algorithm: isSet(object.algorithm) ? keyAlgorithmFromJSON(object.algorithm) : 0,
      createdAt: isSet(object.createdAt)
        ? globalThis.Number(object.createdAt)
        : isSet(object.created_at)
        ? globalThis.Number(object.created_at)
        : 0,
      expiresAt: isSet(object.expiresAt)
        ? globalThis.Number(object.expiresAt)
        : isSet(object.expires_at)
        ? globalThis.Number(object.expires_at)
        : 0,
      fingerprint: isSet(object.fingerprint) ? globalThis.String(object.fingerprint) : "",
    };
  },

  toJSON(message: KeyPair): unknown {
    const obj: any = {};
    if (message.publicKey.length !== 0) {
      obj.publicKey = base64FromBytes(message.publicKey);
    }
    if (message.encryptedPrivateKey.length !== 0) {
      obj.encryptedPrivateKey = base64FromBytes(message.encryptedPrivateKey);
    }
    if (message.algorithm !== 0) {
      obj.algorithm = keyAlgorithmToJSON(message.algorithm);
    }
    if (message.createdAt !== 0) {
      obj.createdAt = Math.round(message.createdAt);
    }
    if (message.expiresAt !== 0) {
      obj.expiresAt = Math.round(message.expiresAt);
    }
    if (message.fingerprint !== "") {
      obj.fingerprint = message.fingerprint;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<KeyPair>, I>>(base?: I): KeyPair {
    return KeyPair.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<KeyPair>, I>>(object: I): KeyPair {
    const message = createBaseKeyPair();
    message.publicKey = object.publicKey ?? new Uint8Array(0);
    message.encryptedPrivateKey = object.encryptedPrivateKey ?? new Uint8Array(0);
    message.algorithm = object.algorithm ?? 0;
    message.createdAt = object.createdAt ?? 0;
    message.expiresAt = object.expiresAt ?? 0;
    message.fingerprint = object.fingerprint ?? "";
    return message;
  },
};

messageTypeRegistry.set(KeyPair.$type, KeyPair);

function createBaseSignature(): Signature {
  return {
    $type: "synch.v1.Signature",
    dataHash: new Uint8Array(0),
    signatureBytes: new Uint8Array(0),
    signerPublicKey: new Uint8Array(0),
    signedAt: 0,
  };
}

export const Signature: MessageFns<Signature, "synch.v1.Signature"> = {
  $type: "synch.v1.Signature" as const,

  encode(message: Signature, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.dataHash.length !== 0) {
      writer.uint32(10).bytes(message.dataHash);
    }
    if (message.signatureBytes.length !== 0) {
      writer.uint32(18).bytes(message.signatureBytes);
    }
    if (message.signerPublicKey.length !== 0) {
      writer.uint32(26).bytes(message.signerPublicKey);
    }
    if (message.signedAt !== 0) {
      writer.uint32(32).uint64(message.signedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Signature {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSignature();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.dataHash = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.signatureBytes = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.signerPublicKey = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.signedAt = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Signature {
    return {
      $type: Signature.$type,
      dataHash: isSet(object.dataHash)
        ? bytesFromBase64(object.dataHash)
        : isSet(object.data_hash)
        ? bytesFromBase64(object.data_hash)
        : new Uint8Array(0),
      signatureBytes: isSet(object.signatureBytes)
        ? bytesFromBase64(object.signatureBytes)
        : isSet(object.signature_bytes)
        ? bytesFromBase64(object.signature_bytes)
        : new Uint8Array(0),
      signerPublicKey: isSet(object.signerPublicKey)
        ? bytesFromBase64(object.signerPublicKey)
        : isSet(object.signer_public_key)
        ? bytesFromBase64(object.signer_public_key)
        : new Uint8Array(0),
      signedAt: isSet(object.signedAt)
        ? globalThis.Number(object.signedAt)
        : isSet(object.signed_at)
        ? globalThis.Number(object.signed_at)
        : 0,
    };
  },

  toJSON(message: Signature): unknown {
    const obj: any = {};
    if (message.dataHash.length !== 0) {
      obj.dataHash = base64FromBytes(message.dataHash);
    }
    if (message.signatureBytes.length !== 0) {
      obj.signatureBytes = base64FromBytes(message.signatureBytes);
    }
    if (message.signerPublicKey.length !== 0) {
      obj.signerPublicKey = base64FromBytes(message.signerPublicKey);
    }
    if (message.signedAt !== 0) {
      obj.signedAt = Math.round(message.signedAt);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Signature>, I>>(base?: I): Signature {
    return Signature.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Signature>, I>>(object: I): Signature {
    const message = createBaseSignature();
    message.dataHash = object.dataHash ?? new Uint8Array(0);
    message.signatureBytes = object.signatureBytes ?? new Uint8Array(0);
    message.signerPublicKey = object.signerPublicKey ?? new Uint8Array(0);
    message.signedAt = object.signedAt ?? 0;
    return message;
  },
};

messageTypeRegistry.set(Signature.$type, Signature);

function createBaseEncryptedPayload(): EncryptedPayload {
  return {
    $type: "synch.v1.EncryptedPayload",
    ciphertext: new Uint8Array(0),
    nonce: new Uint8Array(0),
    senderPublicKey: new Uint8Array(0),
    algorithm: 0,
    aadHash: new Uint8Array(0),
    contractId: "",
    ratchetSeq: 0,
    ratchetKey: new Uint8Array(0),
    prevChainLength: 0,
  };
}

export const EncryptedPayload: MessageFns<EncryptedPayload, "synch.v1.EncryptedPayload"> = {
  $type: "synch.v1.EncryptedPayload" as const,

  encode(message: EncryptedPayload, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ciphertext.length !== 0) {
      writer.uint32(10).bytes(message.ciphertext);
    }
    if (message.nonce.length !== 0) {
      writer.uint32(18).bytes(message.nonce);
    }
    if (message.senderPublicKey.length !== 0) {
      writer.uint32(26).bytes(message.senderPublicKey);
    }
    if (message.algorithm !== 0) {
      writer.uint32(32).int32(message.algorithm);
    }
    if (message.aadHash.length !== 0) {
      writer.uint32(42).bytes(message.aadHash);
    }
    if (message.contractId !== "") {
      writer.uint32(50).string(message.contractId);
    }
    if (message.ratchetSeq !== 0) {
      writer.uint32(56).uint32(message.ratchetSeq);
    }
    if (message.ratchetKey.length !== 0) {
      writer.uint32(66).bytes(message.ratchetKey);
    }
    if (message.prevChainLength !== 0) {
      writer.uint32(72).uint32(message.prevChainLength);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EncryptedPayload {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEncryptedPayload();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ciphertext = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.nonce = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.senderPublicKey = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.algorithm = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.aadHash = reader.bytes();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.contractId = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.ratchetSeq = reader.uint32();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.ratchetKey = reader.bytes();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.prevChainLength = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EncryptedPayload {
    return {
      $type: EncryptedPayload.$type,
      ciphertext: isSet(object.ciphertext) ? bytesFromBase64(object.ciphertext) : new Uint8Array(0),
      nonce: isSet(object.nonce) ? bytesFromBase64(object.nonce) : new Uint8Array(0),
      senderPublicKey: isSet(object.senderPublicKey)
        ? bytesFromBase64(object.senderPublicKey)
        : isSet(object.sender_public_key)
        ? bytesFromBase64(object.sender_public_key)
        : new Uint8Array(0),
      algorithm: isSet(object.algorithm) ? keyAlgorithmFromJSON(object.algorithm) : 0,
      aadHash: isSet(object.aadHash)
        ? bytesFromBase64(object.aadHash)
        : isSet(object.aad_hash)
        ? bytesFromBase64(object.aad_hash)
        : new Uint8Array(0),
      contractId: isSet(object.contractId)
        ? globalThis.String(object.contractId)
        : isSet(object.contract_id)
        ? globalThis.String(object.contract_id)
        : "",
      ratchetSeq: isSet(object.ratchetSeq)
        ? globalThis.Number(object.ratchetSeq)
        : isSet(object.ratchet_seq)
        ? globalThis.Number(object.ratchet_seq)
        : 0,
      ratchetKey: isSet(object.ratchetKey)
        ? bytesFromBase64(object.ratchetKey)
        : isSet(object.ratchet_key)
        ? bytesFromBase64(object.ratchet_key)
        : new Uint8Array(0),
      prevChainLength: isSet(object.prevChainLength)
        ? globalThis.Number(object.prevChainLength)
        : isSet(object.prev_chain_length)
        ? globalThis.Number(object.prev_chain_length)
        : 0,
    };
  },

  toJSON(message: EncryptedPayload): unknown {
    const obj: any = {};
    if (message.ciphertext.length !== 0) {
      obj.ciphertext = base64FromBytes(message.ciphertext);
    }
    if (message.nonce.length !== 0) {
      obj.nonce = base64FromBytes(message.nonce);
    }
    if (message.senderPublicKey.length !== 0) {
      obj.senderPublicKey = base64FromBytes(message.senderPublicKey);
    }
    if (message.algorithm !== 0) {
      obj.algorithm = keyAlgorithmToJSON(message.algorithm);
    }
    if (message.aadHash.length !== 0) {
      obj.aadHash = base64FromBytes(message.aadHash);
    }
    if (message.contractId !== "") {
      obj.contractId = message.contractId;
    }
    if (message.ratchetSeq !== 0) {
      obj.ratchetSeq = Math.round(message.ratchetSeq);
    }
    if (message.ratchetKey.length !== 0) {
      obj.ratchetKey = base64FromBytes(message.ratchetKey);
    }
    if (message.prevChainLength !== 0) {
      obj.prevChainLength = Math.round(message.prevChainLength);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EncryptedPayload>, I>>(base?: I): EncryptedPayload {
    return EncryptedPayload.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EncryptedPayload>, I>>(object: I): EncryptedPayload {
    const message = createBaseEncryptedPayload();
    message.ciphertext = object.ciphertext ?? new Uint8Array(0);
    message.nonce = object.nonce ?? new Uint8Array(0);
    message.senderPublicKey = object.senderPublicKey ?? new Uint8Array(0);
    message.algorithm = object.algorithm ?? 0;
    message.aadHash = object.aadHash ?? new Uint8Array(0);
    message.contractId = object.contractId ?? "";
    message.ratchetSeq = object.ratchetSeq ?? 0;
    message.ratchetKey = object.ratchetKey ?? new Uint8Array(0);
    message.prevChainLength = object.prevChainLength ?? 0;
    return message;
  },
};

messageTypeRegistry.set(EncryptedPayload.$type, EncryptedPayload);

function createBaseKeyExchangeRequest(): KeyExchangeRequest {
  return {
    $type: "synch.v1.KeyExchangeRequest",
    ephemeralPublicKey: new Uint8Array(0),
    identityPublicKey: new Uint8Array(0),
    identityProof: undefined,
    timestamp: 0,
  };
}

export const KeyExchangeRequest: MessageFns<KeyExchangeRequest, "synch.v1.KeyExchangeRequest"> = {
  $type: "synch.v1.KeyExchangeRequest" as const,

  encode(message: KeyExchangeRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ephemeralPublicKey.length !== 0) {
      writer.uint32(10).bytes(message.ephemeralPublicKey);
    }
    if (message.identityPublicKey.length !== 0) {
      writer.uint32(18).bytes(message.identityPublicKey);
    }
    if (message.identityProof !== undefined) {
      Signature.encode(message.identityProof, writer.uint32(26).fork()).join();
    }
    if (message.timestamp !== 0) {
      writer.uint32(32).uint64(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): KeyExchangeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseKeyExchangeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ephemeralPublicKey = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.identityPublicKey = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.identityProof = Signature.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.timestamp = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): KeyExchangeRequest {
    return {
      $type: KeyExchangeRequest.$type,
      ephemeralPublicKey: isSet(object.ephemeralPublicKey)
        ? bytesFromBase64(object.ephemeralPublicKey)
        : isSet(object.ephemeral_public_key)
        ? bytesFromBase64(object.ephemeral_public_key)
        : new Uint8Array(0),
      identityPublicKey: isSet(object.identityPublicKey)
        ? bytesFromBase64(object.identityPublicKey)
        : isSet(object.identity_public_key)
        ? bytesFromBase64(object.identity_public_key)
        : new Uint8Array(0),
      identityProof: isSet(object.identityProof)
        ? Signature.fromJSON(object.identityProof)
        : isSet(object.identity_proof)
        ? Signature.fromJSON(object.identity_proof)
        : undefined,
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
    };
  },

  toJSON(message: KeyExchangeRequest): unknown {
    const obj: any = {};
    if (message.ephemeralPublicKey.length !== 0) {
      obj.ephemeralPublicKey = base64FromBytes(message.ephemeralPublicKey);
    }
    if (message.identityPublicKey.length !== 0) {
      obj.identityPublicKey = base64FromBytes(message.identityPublicKey);
    }
    if (message.identityProof !== undefined) {
      obj.identityProof = Signature.toJSON(message.identityProof);
    }
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<KeyExchangeRequest>, I>>(base?: I): KeyExchangeRequest {
    return KeyExchangeRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<KeyExchangeRequest>, I>>(object: I): KeyExchangeRequest {
    const message = createBaseKeyExchangeRequest();
    message.ephemeralPublicKey = object.ephemeralPublicKey ?? new Uint8Array(0);
    message.identityPublicKey = object.identityPublicKey ?? new Uint8Array(0);
    message.identityProof = (object.identityProof !== undefined && object.identityProof !== null)
      ? Signature.fromPartial(object.identityProof)
      : undefined;
    message.timestamp = object.timestamp ?? 0;
    return message;
  },
};

messageTypeRegistry.set(KeyExchangeRequest.$type, KeyExchangeRequest);

function createBaseKeyExchangeResponse(): KeyExchangeResponse {
  return {
    $type: "synch.v1.KeyExchangeResponse",
    ephemeralPublicKey: new Uint8Array(0),
    identityPublicKey: new Uint8Array(0),
    identityProof: undefined,
    encryptedConfirmation: undefined,
  };
}

export const KeyExchangeResponse: MessageFns<KeyExchangeResponse, "synch.v1.KeyExchangeResponse"> = {
  $type: "synch.v1.KeyExchangeResponse" as const,

  encode(message: KeyExchangeResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ephemeralPublicKey.length !== 0) {
      writer.uint32(10).bytes(message.ephemeralPublicKey);
    }
    if (message.identityPublicKey.length !== 0) {
      writer.uint32(18).bytes(message.identityPublicKey);
    }
    if (message.identityProof !== undefined) {
      Signature.encode(message.identityProof, writer.uint32(26).fork()).join();
    }
    if (message.encryptedConfirmation !== undefined) {
      EncryptedPayload.encode(message.encryptedConfirmation, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): KeyExchangeResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseKeyExchangeResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ephemeralPublicKey = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.identityPublicKey = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.identityProof = Signature.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.encryptedConfirmation = EncryptedPayload.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): KeyExchangeResponse {
    return {
      $type: KeyExchangeResponse.$type,
      ephemeralPublicKey: isSet(object.ephemeralPublicKey)
        ? bytesFromBase64(object.ephemeralPublicKey)
        : isSet(object.ephemeral_public_key)
        ? bytesFromBase64(object.ephemeral_public_key)
        : new Uint8Array(0),
      identityPublicKey: isSet(object.identityPublicKey)
        ? bytesFromBase64(object.identityPublicKey)
        : isSet(object.identity_public_key)
        ? bytesFromBase64(object.identity_public_key)
        : new Uint8Array(0),
      identityProof: isSet(object.identityProof)
        ? Signature.fromJSON(object.identityProof)
        : isSet(object.identity_proof)
        ? Signature.fromJSON(object.identity_proof)
        : undefined,
      encryptedConfirmation: isSet(object.encryptedConfirmation)
        ? EncryptedPayload.fromJSON(object.encryptedConfirmation)
        : isSet(object.encrypted_confirmation)
        ? EncryptedPayload.fromJSON(object.encrypted_confirmation)
        : undefined,
    };
  },

  toJSON(message: KeyExchangeResponse): unknown {
    const obj: any = {};
    if (message.ephemeralPublicKey.length !== 0) {
      obj.ephemeralPublicKey = base64FromBytes(message.ephemeralPublicKey);
    }
    if (message.identityPublicKey.length !== 0) {
      obj.identityPublicKey = base64FromBytes(message.identityPublicKey);
    }
    if (message.identityProof !== undefined) {
      obj.identityProof = Signature.toJSON(message.identityProof);
    }
    if (message.encryptedConfirmation !== undefined) {
      obj.encryptedConfirmation = EncryptedPayload.toJSON(message.encryptedConfirmation);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<KeyExchangeResponse>, I>>(base?: I): KeyExchangeResponse {
    return KeyExchangeResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<KeyExchangeResponse>, I>>(object: I): KeyExchangeResponse {
    const message = createBaseKeyExchangeResponse();
    message.ephemeralPublicKey = object.ephemeralPublicKey ?? new Uint8Array(0);
    message.identityPublicKey = object.identityPublicKey ?? new Uint8Array(0);
    message.identityProof = (object.identityProof !== undefined && object.identityProof !== null)
      ? Signature.fromPartial(object.identityProof)
      : undefined;
    message.encryptedConfirmation =
      (object.encryptedConfirmation !== undefined && object.encryptedConfirmation !== null)
        ? EncryptedPayload.fromPartial(object.encryptedConfirmation)
        : undefined;
    return message;
  },
};

messageTypeRegistry.set(KeyExchangeResponse.$type, KeyExchangeResponse);

function createBaseVaultKey(): VaultKey {
  return {
    $type: "synch.v1.VaultKey",
    vaultId: "",
    encryptedKeyMaterial: new Uint8Array(0),
    wrappingAlgorithm: 0,
    keyVersion: 0,
    createdAt: 0,
    wrappedByPublicKey: new Uint8Array(0),
  };
}

export const VaultKey: MessageFns<VaultKey, "synch.v1.VaultKey"> = {
  $type: "synch.v1.VaultKey" as const,

  encode(message: VaultKey, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.vaultId !== "") {
      writer.uint32(10).string(message.vaultId);
    }
    if (message.encryptedKeyMaterial.length !== 0) {
      writer.uint32(18).bytes(message.encryptedKeyMaterial);
    }
    if (message.wrappingAlgorithm !== 0) {
      writer.uint32(24).int32(message.wrappingAlgorithm);
    }
    if (message.keyVersion !== 0) {
      writer.uint32(32).uint32(message.keyVersion);
    }
    if (message.createdAt !== 0) {
      writer.uint32(40).uint64(message.createdAt);
    }
    if (message.wrappedByPublicKey.length !== 0) {
      writer.uint32(50).bytes(message.wrappedByPublicKey);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VaultKey {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVaultKey();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.vaultId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.encryptedKeyMaterial = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.wrappingAlgorithm = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.keyVersion = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.createdAt = longToNumber(reader.uint64());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.wrappedByPublicKey = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VaultKey {
    return {
      $type: VaultKey.$type,
      vaultId: isSet(object.vaultId)
        ? globalThis.String(object.vaultId)
        : isSet(object.vault_id)
        ? globalThis.String(object.vault_id)
        : "",
      encryptedKeyMaterial: isSet(object.encryptedKeyMaterial)
        ? bytesFromBase64(object.encryptedKeyMaterial)
        : isSet(object.encrypted_key_material)
        ? bytesFromBase64(object.encrypted_key_material)
        : new Uint8Array(0),
      wrappingAlgorithm: isSet(object.wrappingAlgorithm)
        ? keyAlgorithmFromJSON(object.wrappingAlgorithm)
        : isSet(object.wrapping_algorithm)
        ? keyAlgorithmFromJSON(object.wrapping_algorithm)
        : 0,
      keyVersion: isSet(object.keyVersion)
        ? globalThis.Number(object.keyVersion)
        : isSet(object.key_version)
        ? globalThis.Number(object.key_version)
        : 0,
      createdAt: isSet(object.createdAt)
        ? globalThis.Number(object.createdAt)
        : isSet(object.created_at)
        ? globalThis.Number(object.created_at)
        : 0,
      wrappedByPublicKey: isSet(object.wrappedByPublicKey)
        ? bytesFromBase64(object.wrappedByPublicKey)
        : isSet(object.wrapped_by_public_key)
        ? bytesFromBase64(object.wrapped_by_public_key)
        : new Uint8Array(0),
    };
  },

  toJSON(message: VaultKey): unknown {
    const obj: any = {};
    if (message.vaultId !== "") {
      obj.vaultId = message.vaultId;
    }
    if (message.encryptedKeyMaterial.length !== 0) {
      obj.encryptedKeyMaterial = base64FromBytes(message.encryptedKeyMaterial);
    }
    if (message.wrappingAlgorithm !== 0) {
      obj.wrappingAlgorithm = keyAlgorithmToJSON(message.wrappingAlgorithm);
    }
    if (message.keyVersion !== 0) {
      obj.keyVersion = Math.round(message.keyVersion);
    }
    if (message.createdAt !== 0) {
      obj.createdAt = Math.round(message.createdAt);
    }
    if (message.wrappedByPublicKey.length !== 0) {
      obj.wrappedByPublicKey = base64FromBytes(message.wrappedByPublicKey);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VaultKey>, I>>(base?: I): VaultKey {
    return VaultKey.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VaultKey>, I>>(object: I): VaultKey {
    const message = createBaseVaultKey();
    message.vaultId = object.vaultId ?? "";
    message.encryptedKeyMaterial = object.encryptedKeyMaterial ?? new Uint8Array(0);
    message.wrappingAlgorithm = object.wrappingAlgorithm ?? 0;
    message.keyVersion = object.keyVersion ?? 0;
    message.createdAt = object.createdAt ?? 0;
    message.wrappedByPublicKey = object.wrappedByPublicKey ?? new Uint8Array(0);
    return message;
  },
};

messageTypeRegistry.set(VaultKey.$type, VaultKey);

function createBaseSynchCertificate(): SynchCertificate {
  return {
    $type: "synch.v1.SynchCertificate",
    version: 0,
    subjectPublicKey: new Uint8Array(0),
    subjectNodeId: "",
    issuerPublicKey: new Uint8Array(0),
    issuerSignature: undefined,
    validFrom: 0,
    validUntil: 0,
    grantedCapabilities: [],
    allowedVaultIds: [],
  };
}

export const SynchCertificate: MessageFns<SynchCertificate, "synch.v1.SynchCertificate"> = {
  $type: "synch.v1.SynchCertificate" as const,

  encode(message: SynchCertificate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.version !== 0) {
      writer.uint32(8).uint32(message.version);
    }
    if (message.subjectPublicKey.length !== 0) {
      writer.uint32(18).bytes(message.subjectPublicKey);
    }
    if (message.subjectNodeId !== "") {
      writer.uint32(26).string(message.subjectNodeId);
    }
    if (message.issuerPublicKey.length !== 0) {
      writer.uint32(34).bytes(message.issuerPublicKey);
    }
    if (message.issuerSignature !== undefined) {
      Signature.encode(message.issuerSignature, writer.uint32(42).fork()).join();
    }
    if (message.validFrom !== 0) {
      writer.uint32(48).uint64(message.validFrom);
    }
    if (message.validUntil !== 0) {
      writer.uint32(56).uint64(message.validUntil);
    }
    for (const v of message.grantedCapabilities) {
      writer.uint32(66).string(v!);
    }
    for (const v of message.allowedVaultIds) {
      writer.uint32(74).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SynchCertificate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSynchCertificate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.version = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.subjectPublicKey = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.subjectNodeId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.issuerPublicKey = reader.bytes();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.issuerSignature = Signature.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.validFrom = longToNumber(reader.uint64());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.validUntil = longToNumber(reader.uint64());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.grantedCapabilities.push(reader.string());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.allowedVaultIds.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SynchCertificate {
    return {
      $type: SynchCertificate.$type,
      version: isSet(object.version) ? globalThis.Number(object.version) : 0,
      subjectPublicKey: isSet(object.subjectPublicKey)
        ? bytesFromBase64(object.subjectPublicKey)
        : isSet(object.subject_public_key)
        ? bytesFromBase64(object.subject_public_key)
        : new Uint8Array(0),
      subjectNodeId: isSet(object.subjectNodeId)
        ? globalThis.String(object.subjectNodeId)
        : isSet(object.subject_node_id)
        ? globalThis.String(object.subject_node_id)
        : "",
      issuerPublicKey: isSet(object.issuerPublicKey)
        ? bytesFromBase64(object.issuerPublicKey)
        : isSet(object.issuer_public_key)
        ? bytesFromBase64(object.issuer_public_key)
        : new Uint8Array(0),
      issuerSignature: isSet(object.issuerSignature)
        ? Signature.fromJSON(object.issuerSignature)
        : isSet(object.issuer_signature)
        ? Signature.fromJSON(object.issuer_signature)
        : undefined,
      validFrom: isSet(object.validFrom)
        ? globalThis.Number(object.validFrom)
        : isSet(object.valid_from)
        ? globalThis.Number(object.valid_from)
        : 0,
      validUntil: isSet(object.validUntil)
        ? globalThis.Number(object.validUntil)
        : isSet(object.valid_until)
        ? globalThis.Number(object.valid_until)
        : 0,
      grantedCapabilities: globalThis.Array.isArray(object?.grantedCapabilities)
        ? object.grantedCapabilities.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.granted_capabilities)
        ? object.granted_capabilities.map((e: any) => globalThis.String(e))
        : [],
      allowedVaultIds: globalThis.Array.isArray(object?.allowedVaultIds)
        ? object.allowedVaultIds.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.allowed_vault_ids)
        ? object.allowed_vault_ids.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: SynchCertificate): unknown {
    const obj: any = {};
    if (message.version !== 0) {
      obj.version = Math.round(message.version);
    }
    if (message.subjectPublicKey.length !== 0) {
      obj.subjectPublicKey = base64FromBytes(message.subjectPublicKey);
    }
    if (message.subjectNodeId !== "") {
      obj.subjectNodeId = message.subjectNodeId;
    }
    if (message.issuerPublicKey.length !== 0) {
      obj.issuerPublicKey = base64FromBytes(message.issuerPublicKey);
    }
    if (message.issuerSignature !== undefined) {
      obj.issuerSignature = Signature.toJSON(message.issuerSignature);
    }
    if (message.validFrom !== 0) {
      obj.validFrom = Math.round(message.validFrom);
    }
    if (message.validUntil !== 0) {
      obj.validUntil = Math.round(message.validUntil);
    }
    if (message.grantedCapabilities?.length) {
      obj.grantedCapabilities = message.grantedCapabilities;
    }
    if (message.allowedVaultIds?.length) {
      obj.allowedVaultIds = message.allowedVaultIds;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SynchCertificate>, I>>(base?: I): SynchCertificate {
    return SynchCertificate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SynchCertificate>, I>>(object: I): SynchCertificate {
    const message = createBaseSynchCertificate();
    message.version = object.version ?? 0;
    message.subjectPublicKey = object.subjectPublicKey ?? new Uint8Array(0);
    message.subjectNodeId = object.subjectNodeId ?? "";
    message.issuerPublicKey = object.issuerPublicKey ?? new Uint8Array(0);
    message.issuerSignature = (object.issuerSignature !== undefined && object.issuerSignature !== null)
      ? Signature.fromPartial(object.issuerSignature)
      : undefined;
    message.validFrom = object.validFrom ?? 0;
    message.validUntil = object.validUntil ?? 0;
    message.grantedCapabilities = object.grantedCapabilities?.map((e) => e) || [];
    message.allowedVaultIds = object.allowedVaultIds?.map((e) => e) || [];
    return message;
  },
};

messageTypeRegistry.set(SynchCertificate.$type, SynchCertificate);

function bytesFromBase64(b64: string): Uint8Array {
  const bin = globalThis.atob(b64);
  const arr = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; ++i) {
    arr[i] = bin.charCodeAt(i);
  }
  return arr;
}

function base64FromBytes(arr: Uint8Array): string {
  const bin: string[] = [];
  arr.forEach((byte) => {
    bin.push(globalThis.String.fromCharCode(byte));
  });
  return globalThis.btoa(bin.join(""));
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in Exclude<keyof T, "$type">]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P> | "$type">]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T, V extends string> {
  readonly $type: V;
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
