// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               unknown
// source: v1/sync.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { messageTypeRegistry } from "../typeRegistry";
import { Signature } from "./crypto";

export const protobufPackage = "synch.v1";

/**
 * SYNCH 心契协议 — Vault 同步引擎
 * 包含：同步状态机、握手、Delta 传输、冲突检测
 */

/**
 * SyncState 对应架构文档中的同步状态图:
 *   IDLE → CONNECTING → AUTHENTICATING → SYNCING ⇄ SYNCED
 */
export enum SyncState {
  SYNC_STATE_UNSPECIFIED = 0,
  /** SYNC_STATE_IDLE - 断开，尚未连接 */
  SYNC_STATE_IDLE = 1,
  /** SYNC_STATE_CONNECTING - 正在建立 WebSocket/gRPC 连接 */
  SYNC_STATE_CONNECTING = 2,
  /** SYNC_STATE_AUTHENTICATING - 已连接，正在进行身份验证 */
  SYNC_STATE_AUTHENTICATING = 3,
  /** SYNC_STATE_SYNCING - 正在进行增量同步交换 */
  SYNC_STATE_SYNCING = 4,
  /** SYNC_STATE_SYNCED - 同步完成，监听变更 */
  SYNC_STATE_SYNCED = 5,
  /** SYNC_STATE_ERROR - 发生错误，等待恢复 */
  SYNC_STATE_ERROR = 6,
  UNRECOGNIZED = -1,
}

export function syncStateFromJSON(object: any): SyncState {
  switch (object) {
    case 0:
    case "SYNC_STATE_UNSPECIFIED":
      return SyncState.SYNC_STATE_UNSPECIFIED;
    case 1:
    case "SYNC_STATE_IDLE":
      return SyncState.SYNC_STATE_IDLE;
    case 2:
    case "SYNC_STATE_CONNECTING":
      return SyncState.SYNC_STATE_CONNECTING;
    case 3:
    case "SYNC_STATE_AUTHENTICATING":
      return SyncState.SYNC_STATE_AUTHENTICATING;
    case 4:
    case "SYNC_STATE_SYNCING":
      return SyncState.SYNC_STATE_SYNCING;
    case 5:
    case "SYNC_STATE_SYNCED":
      return SyncState.SYNC_STATE_SYNCED;
    case 6:
    case "SYNC_STATE_ERROR":
      return SyncState.SYNC_STATE_ERROR;
    case -1:
    case "UNRECOGNIZED":
    default:
      return SyncState.UNRECOGNIZED;
  }
}

export function syncStateToJSON(object: SyncState): string {
  switch (object) {
    case SyncState.SYNC_STATE_UNSPECIFIED:
      return "SYNC_STATE_UNSPECIFIED";
    case SyncState.SYNC_STATE_IDLE:
      return "SYNC_STATE_IDLE";
    case SyncState.SYNC_STATE_CONNECTING:
      return "SYNC_STATE_CONNECTING";
    case SyncState.SYNC_STATE_AUTHENTICATING:
      return "SYNC_STATE_AUTHENTICATING";
    case SyncState.SYNC_STATE_SYNCING:
      return "SYNC_STATE_SYNCING";
    case SyncState.SYNC_STATE_SYNCED:
      return "SYNC_STATE_SYNCED";
    case SyncState.SYNC_STATE_ERROR:
      return "SYNC_STATE_ERROR";
    case SyncState.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** EntryOperation 文件操作类型 */
export enum EntryOperation {
  ENTRY_OPERATION_UNSPECIFIED = 0,
  ENTRY_OPERATION_CREATE = 1,
  ENTRY_OPERATION_MODIFY = 2,
  ENTRY_OPERATION_DELETE = 3,
  ENTRY_OPERATION_RENAME = 4,
  UNRECOGNIZED = -1,
}

export function entryOperationFromJSON(object: any): EntryOperation {
  switch (object) {
    case 0:
    case "ENTRY_OPERATION_UNSPECIFIED":
      return EntryOperation.ENTRY_OPERATION_UNSPECIFIED;
    case 1:
    case "ENTRY_OPERATION_CREATE":
      return EntryOperation.ENTRY_OPERATION_CREATE;
    case 2:
    case "ENTRY_OPERATION_MODIFY":
      return EntryOperation.ENTRY_OPERATION_MODIFY;
    case 3:
    case "ENTRY_OPERATION_DELETE":
      return EntryOperation.ENTRY_OPERATION_DELETE;
    case 4:
    case "ENTRY_OPERATION_RENAME":
      return EntryOperation.ENTRY_OPERATION_RENAME;
    case -1:
    case "UNRECOGNIZED":
    default:
      return EntryOperation.UNRECOGNIZED;
  }
}

export function entryOperationToJSON(object: EntryOperation): string {
  switch (object) {
    case EntryOperation.ENTRY_OPERATION_UNSPECIFIED:
      return "ENTRY_OPERATION_UNSPECIFIED";
    case EntryOperation.ENTRY_OPERATION_CREATE:
      return "ENTRY_OPERATION_CREATE";
    case EntryOperation.ENTRY_OPERATION_MODIFY:
      return "ENTRY_OPERATION_MODIFY";
    case EntryOperation.ENTRY_OPERATION_DELETE:
      return "ENTRY_OPERATION_DELETE";
    case EntryOperation.ENTRY_OPERATION_RENAME:
      return "ENTRY_OPERATION_RENAME";
    case EntryOperation.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** ConflictResolution 冲突解决方式 */
export enum ConflictResolution {
  CONFLICT_RESOLUTION_UNSPECIFIED = 0,
  /** CONFLICT_RESOLUTION_KEEP_LOCAL - 保留本地 */
  CONFLICT_RESOLUTION_KEEP_LOCAL = 1,
  /** CONFLICT_RESOLUTION_KEEP_REMOTE - 保留远端 */
  CONFLICT_RESOLUTION_KEEP_REMOTE = 2,
  /** CONFLICT_RESOLUTION_MERGE - CRDT 自动合并 */
  CONFLICT_RESOLUTION_MERGE = 3,
  /** CONFLICT_RESOLUTION_MANUAL - 需要用户手动解决 */
  CONFLICT_RESOLUTION_MANUAL = 4,
  UNRECOGNIZED = -1,
}

export function conflictResolutionFromJSON(object: any): ConflictResolution {
  switch (object) {
    case 0:
    case "CONFLICT_RESOLUTION_UNSPECIFIED":
      return ConflictResolution.CONFLICT_RESOLUTION_UNSPECIFIED;
    case 1:
    case "CONFLICT_RESOLUTION_KEEP_LOCAL":
      return ConflictResolution.CONFLICT_RESOLUTION_KEEP_LOCAL;
    case 2:
    case "CONFLICT_RESOLUTION_KEEP_REMOTE":
      return ConflictResolution.CONFLICT_RESOLUTION_KEEP_REMOTE;
    case 3:
    case "CONFLICT_RESOLUTION_MERGE":
      return ConflictResolution.CONFLICT_RESOLUTION_MERGE;
    case 4:
    case "CONFLICT_RESOLUTION_MANUAL":
      return ConflictResolution.CONFLICT_RESOLUTION_MANUAL;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ConflictResolution.UNRECOGNIZED;
  }
}

export function conflictResolutionToJSON(object: ConflictResolution): string {
  switch (object) {
    case ConflictResolution.CONFLICT_RESOLUTION_UNSPECIFIED:
      return "CONFLICT_RESOLUTION_UNSPECIFIED";
    case ConflictResolution.CONFLICT_RESOLUTION_KEEP_LOCAL:
      return "CONFLICT_RESOLUTION_KEEP_LOCAL";
    case ConflictResolution.CONFLICT_RESOLUTION_KEEP_REMOTE:
      return "CONFLICT_RESOLUTION_KEEP_REMOTE";
    case ConflictResolution.CONFLICT_RESOLUTION_MERGE:
      return "CONFLICT_RESOLUTION_MERGE";
    case ConflictResolution.CONFLICT_RESOLUTION_MANUAL:
      return "CONFLICT_RESOLUTION_MANUAL";
    case ConflictResolution.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** PresenceStatus 在线状态 */
export enum PresenceStatus {
  PRESENCE_STATUS_UNSPECIFIED = 0,
  PRESENCE_STATUS_ONLINE = 1,
  PRESENCE_STATUS_AWAY = 2,
  PRESENCE_STATUS_BUSY = 3,
  PRESENCE_STATUS_OFFLINE = 4,
  UNRECOGNIZED = -1,
}

export function presenceStatusFromJSON(object: any): PresenceStatus {
  switch (object) {
    case 0:
    case "PRESENCE_STATUS_UNSPECIFIED":
      return PresenceStatus.PRESENCE_STATUS_UNSPECIFIED;
    case 1:
    case "PRESENCE_STATUS_ONLINE":
      return PresenceStatus.PRESENCE_STATUS_ONLINE;
    case 2:
    case "PRESENCE_STATUS_AWAY":
      return PresenceStatus.PRESENCE_STATUS_AWAY;
    case 3:
    case "PRESENCE_STATUS_BUSY":
      return PresenceStatus.PRESENCE_STATUS_BUSY;
    case 4:
    case "PRESENCE_STATUS_OFFLINE":
      return PresenceStatus.PRESENCE_STATUS_OFFLINE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return PresenceStatus.UNRECOGNIZED;
  }
}

export function presenceStatusToJSON(object: PresenceStatus): string {
  switch (object) {
    case PresenceStatus.PRESENCE_STATUS_UNSPECIFIED:
      return "PRESENCE_STATUS_UNSPECIFIED";
    case PresenceStatus.PRESENCE_STATUS_ONLINE:
      return "PRESENCE_STATUS_ONLINE";
    case PresenceStatus.PRESENCE_STATUS_AWAY:
      return "PRESENCE_STATUS_AWAY";
    case PresenceStatus.PRESENCE_STATUS_BUSY:
      return "PRESENCE_STATUS_BUSY";
    case PresenceStatus.PRESENCE_STATUS_OFFLINE:
      return "PRESENCE_STATUS_OFFLINE";
    case PresenceStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** SyncMessage 是客户端与服务端之间的同步协议帧 */
export interface SyncMessage {
  $type: "synch.v1.SyncMessage";
  /** 逻辑发送方 ID (当通过 Plugin 中继时使用) */
  senderId: string;
  handshake?: VaultHandshake | undefined;
  delta?: DeltaManifest | undefined;
  ack?: DeltaAck | undefined;
  conflict?: ConflictDetected | undefined;
  progress?: SyncProgress | undefined;
  presence?: PresenceUpdate | undefined;
}

/** VaultHandshake 用于同步开始前的版本协商 */
export interface VaultHandshake {
  $type: "synch.v1.VaultHandshake";
  /** 要同步的 Vault ID */
  vaultId: string;
  /** 客户端已知的最新版本号 */
  localVersion: number;
  /** 版本向量: node_id → 该节点已知的最大序号 */
  versionVector: { [key: string]: number };
  /** 客户端支持的同步能力: "delta", "rsync", "full-snapshot" ... */
  capabilities: string[];
  /** 客户端节点 ID (用于服务端标识来源) */
  nodeId: string;
}

export interface VaultHandshake_VersionVectorEntry {
  $type: "synch.v1.VaultHandshake.VersionVectorEntry";
  key: string;
  value: number;
}

/** DeltaManifest 描述一次增量同步批次 */
export interface DeltaManifest {
  $type: "synch.v1.DeltaManifest";
  /** Vault ID */
  vaultId: string;
  /** 此批次的基线版本 */
  baseVersion: number;
  /** 目标版本 */
  targetVersion: number;
  /** 文件/条目级变更列表 */
  changes: EntryChange[];
  /** 大文件分块引用 */
  blocks: BlockReference[];
  /** 批次总字节数 (用于进度计算) */
  totalBytes: number;
  /** 签名（用发送方私钥签署的 manifest 摘要） */
  manifestSignature: Signature | undefined;
}

/** EntryChange 描述单个文件/条目的变更 */
export interface EntryChange {
  $type: "synch.v1.EntryChange";
  /** 相对 Vault 根的路径 (如 "notes/daily/2026-03-12.md") */
  path: string;
  /** 变更操作类型 */
  operation: EntryOperation;
  /** 变更后的内容哈希 (Blake3) */
  contentHash: Uint8Array;
  /** 仅对 RENAME: 旧路径 */
  oldPath: string;
  /** 内联 delta 数据 (小文件直接嵌入) */
  deltaBytes: Uint8Array;
  /** 块级引用 (大文件通过 BlockReference 传输) */
  blockHashes: string[];
  /** 文件大小 (bytes) */
  size: number;
  /** 修改时间 (Unix epoch millis) */
  modifiedAt: number;
  /** 此变更的版本向量条目: 哪个节点产生了此变更 */
  originNodeId: string;
  originSequence: number;
}

/** BlockReference 大文件分块引用 */
export interface BlockReference {
  $type: "synch.v1.BlockReference";
  /** 块内容的 Blake3 哈希 (作为唯一标识) */
  blockHash: Uint8Array;
  /** 块大小 (bytes) */
  size: number;
  /** 块在原文件中的偏移量 */
  offset: number;
  /** 加密后的块数据 (传输时填充) */
  encryptedData: Uint8Array;
}

/** DeltaAck 确认接收并应用了 delta */
export interface DeltaAck {
  $type: "synch.v1.DeltaAck";
  vaultId: string;
  ackedVersion: number;
  success: boolean;
  /** 若 success=false, 描述原因 */
  errorMessage: string;
}

/** SyncProgress 报告同步进度 */
export interface SyncProgress {
  $type: "synch.v1.SyncProgress";
  vaultId: string;
  totalEntries: number;
  completedEntries: number;
  totalBytes: number;
  transferredBytes: number;
  currentState: SyncState;
}

/** ConflictDetected 当版本向量检测到并发修改时发送 */
export interface ConflictDetected {
  $type: "synch.v1.ConflictDetected";
  vaultId: string;
  path: string;
  /** 本地版本信息 */
  localVersion:
    | EntryChange
    | undefined;
  /** 远端版本信息 */
  remoteVersion:
    | EntryChange
    | undefined;
  /** 建议的解决策略 */
  suggestedResolution: ConflictResolution;
}

/** PresenceUpdate 广播节点在线状态 */
export interface PresenceUpdate {
  $type: "synch.v1.PresenceUpdate";
  nodeId: string;
  status: PresenceStatus;
  /** Unix epoch millis */
  lastSeen: number;
  /** 当前活跃的 Vault (可选) */
  activeVaultId: string;
}

function createBaseSyncMessage(): SyncMessage {
  return {
    $type: "synch.v1.SyncMessage",
    senderId: "",
    handshake: undefined,
    delta: undefined,
    ack: undefined,
    conflict: undefined,
    progress: undefined,
    presence: undefined,
  };
}

export const SyncMessage: MessageFns<SyncMessage, "synch.v1.SyncMessage"> = {
  $type: "synch.v1.SyncMessage" as const,

  encode(message: SyncMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.senderId !== "") {
      writer.uint32(58).string(message.senderId);
    }
    if (message.handshake !== undefined) {
      VaultHandshake.encode(message.handshake, writer.uint32(10).fork()).join();
    }
    if (message.delta !== undefined) {
      DeltaManifest.encode(message.delta, writer.uint32(18).fork()).join();
    }
    if (message.ack !== undefined) {
      DeltaAck.encode(message.ack, writer.uint32(26).fork()).join();
    }
    if (message.conflict !== undefined) {
      ConflictDetected.encode(message.conflict, writer.uint32(34).fork()).join();
    }
    if (message.progress !== undefined) {
      SyncProgress.encode(message.progress, writer.uint32(42).fork()).join();
    }
    if (message.presence !== undefined) {
      PresenceUpdate.encode(message.presence, writer.uint32(50).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SyncMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSyncMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.senderId = reader.string();
          continue;
        }
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.handshake = VaultHandshake.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.delta = DeltaManifest.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.ack = DeltaAck.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.conflict = ConflictDetected.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.progress = SyncProgress.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.presence = PresenceUpdate.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SyncMessage {
    return {
      $type: SyncMessage.$type,
      senderId: isSet(object.senderId)
        ? globalThis.String(object.senderId)
        : isSet(object.sender_id)
        ? globalThis.String(object.sender_id)
        : "",
      handshake: isSet(object.handshake) ? VaultHandshake.fromJSON(object.handshake) : undefined,
      delta: isSet(object.delta) ? DeltaManifest.fromJSON(object.delta) : undefined,
      ack: isSet(object.ack) ? DeltaAck.fromJSON(object.ack) : undefined,
      conflict: isSet(object.conflict) ? ConflictDetected.fromJSON(object.conflict) : undefined,
      progress: isSet(object.progress) ? SyncProgress.fromJSON(object.progress) : undefined,
      presence: isSet(object.presence) ? PresenceUpdate.fromJSON(object.presence) : undefined,
    };
  },

  toJSON(message: SyncMessage): unknown {
    const obj: any = {};
    if (message.senderId !== "") {
      obj.senderId = message.senderId;
    }
    if (message.handshake !== undefined) {
      obj.handshake = VaultHandshake.toJSON(message.handshake);
    }
    if (message.delta !== undefined) {
      obj.delta = DeltaManifest.toJSON(message.delta);
    }
    if (message.ack !== undefined) {
      obj.ack = DeltaAck.toJSON(message.ack);
    }
    if (message.conflict !== undefined) {
      obj.conflict = ConflictDetected.toJSON(message.conflict);
    }
    if (message.progress !== undefined) {
      obj.progress = SyncProgress.toJSON(message.progress);
    }
    if (message.presence !== undefined) {
      obj.presence = PresenceUpdate.toJSON(message.presence);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SyncMessage>, I>>(base?: I): SyncMessage {
    return SyncMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SyncMessage>, I>>(object: I): SyncMessage {
    const message = createBaseSyncMessage();
    message.senderId = object.senderId ?? "";
    message.handshake = (object.handshake !== undefined && object.handshake !== null)
      ? VaultHandshake.fromPartial(object.handshake)
      : undefined;
    message.delta = (object.delta !== undefined && object.delta !== null)
      ? DeltaManifest.fromPartial(object.delta)
      : undefined;
    message.ack = (object.ack !== undefined && object.ack !== null) ? DeltaAck.fromPartial(object.ack) : undefined;
    message.conflict = (object.conflict !== undefined && object.conflict !== null)
      ? ConflictDetected.fromPartial(object.conflict)
      : undefined;
    message.progress = (object.progress !== undefined && object.progress !== null)
      ? SyncProgress.fromPartial(object.progress)
      : undefined;
    message.presence = (object.presence !== undefined && object.presence !== null)
      ? PresenceUpdate.fromPartial(object.presence)
      : undefined;
    return message;
  },
};

messageTypeRegistry.set(SyncMessage.$type, SyncMessage);

function createBaseVaultHandshake(): VaultHandshake {
  return {
    $type: "synch.v1.VaultHandshake",
    vaultId: "",
    localVersion: 0,
    versionVector: {},
    capabilities: [],
    nodeId: "",
  };
}

export const VaultHandshake: MessageFns<VaultHandshake, "synch.v1.VaultHandshake"> = {
  $type: "synch.v1.VaultHandshake" as const,

  encode(message: VaultHandshake, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.vaultId !== "") {
      writer.uint32(10).string(message.vaultId);
    }
    if (message.localVersion !== 0) {
      writer.uint32(16).uint64(message.localVersion);
    }
    globalThis.Object.entries(message.versionVector).forEach(([key, value]: [string, number]) => {
      VaultHandshake_VersionVectorEntry.encode({
        $type: "synch.v1.VaultHandshake.VersionVectorEntry",
        key: key as any,
        value,
      }, writer.uint32(26).fork()).join();
    });
    for (const v of message.capabilities) {
      writer.uint32(34).string(v!);
    }
    if (message.nodeId !== "") {
      writer.uint32(42).string(message.nodeId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VaultHandshake {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVaultHandshake();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.vaultId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.localVersion = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          const entry3 = VaultHandshake_VersionVectorEntry.decode(reader, reader.uint32());
          if (entry3.value !== undefined) {
            message.versionVector[entry3.key] = entry3.value;
          }
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.capabilities.push(reader.string());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.nodeId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VaultHandshake {
    return {
      $type: VaultHandshake.$type,
      vaultId: isSet(object.vaultId)
        ? globalThis.String(object.vaultId)
        : isSet(object.vault_id)
        ? globalThis.String(object.vault_id)
        : "",
      localVersion: isSet(object.localVersion)
        ? globalThis.Number(object.localVersion)
        : isSet(object.local_version)
        ? globalThis.Number(object.local_version)
        : 0,
      versionVector: isObject(object.versionVector)
        ? (globalThis.Object.entries(object.versionVector) as [string, any][]).reduce(
          (acc: { [key: string]: number }, [key, value]: [string, any]) => {
            acc[key] = globalThis.Number(value);
            return acc;
          },
          {},
        )
        : isObject(object.version_vector)
        ? (globalThis.Object.entries(object.version_vector) as [string, any][]).reduce(
          (acc: { [key: string]: number }, [key, value]: [string, any]) => {
            acc[key] = globalThis.Number(value);
            return acc;
          },
          {},
        )
        : {},
      capabilities: globalThis.Array.isArray(object?.capabilities)
        ? object.capabilities.map((e: any) => globalThis.String(e))
        : [],
      nodeId: isSet(object.nodeId)
        ? globalThis.String(object.nodeId)
        : isSet(object.node_id)
        ? globalThis.String(object.node_id)
        : "",
    };
  },

  toJSON(message: VaultHandshake): unknown {
    const obj: any = {};
    if (message.vaultId !== "") {
      obj.vaultId = message.vaultId;
    }
    if (message.localVersion !== 0) {
      obj.localVersion = Math.round(message.localVersion);
    }
    if (message.versionVector) {
      const entries = globalThis.Object.entries(message.versionVector) as [string, number][];
      if (entries.length > 0) {
        obj.versionVector = {};
        entries.forEach(([k, v]) => {
          obj.versionVector[k] = Math.round(v);
        });
      }
    }
    if (message.capabilities?.length) {
      obj.capabilities = message.capabilities;
    }
    if (message.nodeId !== "") {
      obj.nodeId = message.nodeId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VaultHandshake>, I>>(base?: I): VaultHandshake {
    return VaultHandshake.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VaultHandshake>, I>>(object: I): VaultHandshake {
    const message = createBaseVaultHandshake();
    message.vaultId = object.vaultId ?? "";
    message.localVersion = object.localVersion ?? 0;
    message.versionVector = (globalThis.Object.entries(object.versionVector ?? {}) as [string, number][]).reduce(
      (acc: { [key: string]: number }, [key, value]: [string, number]) => {
        if (value !== undefined) {
          acc[key] = globalThis.Number(value);
        }
        return acc;
      },
      {},
    );
    message.capabilities = object.capabilities?.map((e) => e) || [];
    message.nodeId = object.nodeId ?? "";
    return message;
  },
};

messageTypeRegistry.set(VaultHandshake.$type, VaultHandshake);

function createBaseVaultHandshake_VersionVectorEntry(): VaultHandshake_VersionVectorEntry {
  return { $type: "synch.v1.VaultHandshake.VersionVectorEntry", key: "", value: 0 };
}

export const VaultHandshake_VersionVectorEntry: MessageFns<
  VaultHandshake_VersionVectorEntry,
  "synch.v1.VaultHandshake.VersionVectorEntry"
> = {
  $type: "synch.v1.VaultHandshake.VersionVectorEntry" as const,

  encode(message: VaultHandshake_VersionVectorEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== 0) {
      writer.uint32(16).uint64(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VaultHandshake_VersionVectorEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVaultHandshake_VersionVectorEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.value = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VaultHandshake_VersionVectorEntry {
    return {
      $type: VaultHandshake_VersionVectorEntry.$type,
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.Number(object.value) : 0,
    };
  },

  toJSON(message: VaultHandshake_VersionVectorEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== 0) {
      obj.value = Math.round(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VaultHandshake_VersionVectorEntry>, I>>(
    base?: I,
  ): VaultHandshake_VersionVectorEntry {
    return VaultHandshake_VersionVectorEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VaultHandshake_VersionVectorEntry>, I>>(
    object: I,
  ): VaultHandshake_VersionVectorEntry {
    const message = createBaseVaultHandshake_VersionVectorEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? 0;
    return message;
  },
};

messageTypeRegistry.set(VaultHandshake_VersionVectorEntry.$type, VaultHandshake_VersionVectorEntry);

function createBaseDeltaManifest(): DeltaManifest {
  return {
    $type: "synch.v1.DeltaManifest",
    vaultId: "",
    baseVersion: 0,
    targetVersion: 0,
    changes: [],
    blocks: [],
    totalBytes: 0,
    manifestSignature: undefined,
  };
}

export const DeltaManifest: MessageFns<DeltaManifest, "synch.v1.DeltaManifest"> = {
  $type: "synch.v1.DeltaManifest" as const,

  encode(message: DeltaManifest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.vaultId !== "") {
      writer.uint32(10).string(message.vaultId);
    }
    if (message.baseVersion !== 0) {
      writer.uint32(16).uint64(message.baseVersion);
    }
    if (message.targetVersion !== 0) {
      writer.uint32(24).uint64(message.targetVersion);
    }
    for (const v of message.changes) {
      EntryChange.encode(v!, writer.uint32(34).fork()).join();
    }
    for (const v of message.blocks) {
      BlockReference.encode(v!, writer.uint32(42).fork()).join();
    }
    if (message.totalBytes !== 0) {
      writer.uint32(48).uint64(message.totalBytes);
    }
    if (message.manifestSignature !== undefined) {
      Signature.encode(message.manifestSignature, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeltaManifest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeltaManifest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.vaultId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.baseVersion = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.targetVersion = longToNumber(reader.uint64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.changes.push(EntryChange.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.blocks.push(BlockReference.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.totalBytes = longToNumber(reader.uint64());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.manifestSignature = Signature.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeltaManifest {
    return {
      $type: DeltaManifest.$type,
      vaultId: isSet(object.vaultId)
        ? globalThis.String(object.vaultId)
        : isSet(object.vault_id)
        ? globalThis.String(object.vault_id)
        : "",
      baseVersion: isSet(object.baseVersion)
        ? globalThis.Number(object.baseVersion)
        : isSet(object.base_version)
        ? globalThis.Number(object.base_version)
        : 0,
      targetVersion: isSet(object.targetVersion)
        ? globalThis.Number(object.targetVersion)
        : isSet(object.target_version)
        ? globalThis.Number(object.target_version)
        : 0,
      changes: globalThis.Array.isArray(object?.changes) ? object.changes.map((e: any) => EntryChange.fromJSON(e)) : [],
      blocks: globalThis.Array.isArray(object?.blocks) ? object.blocks.map((e: any) => BlockReference.fromJSON(e)) : [],
      totalBytes: isSet(object.totalBytes)
        ? globalThis.Number(object.totalBytes)
        : isSet(object.total_bytes)
        ? globalThis.Number(object.total_bytes)
        : 0,
      manifestSignature: isSet(object.manifestSignature)
        ? Signature.fromJSON(object.manifestSignature)
        : isSet(object.manifest_signature)
        ? Signature.fromJSON(object.manifest_signature)
        : undefined,
    };
  },

  toJSON(message: DeltaManifest): unknown {
    const obj: any = {};
    if (message.vaultId !== "") {
      obj.vaultId = message.vaultId;
    }
    if (message.baseVersion !== 0) {
      obj.baseVersion = Math.round(message.baseVersion);
    }
    if (message.targetVersion !== 0) {
      obj.targetVersion = Math.round(message.targetVersion);
    }
    if (message.changes?.length) {
      obj.changes = message.changes.map((e) => EntryChange.toJSON(e));
    }
    if (message.blocks?.length) {
      obj.blocks = message.blocks.map((e) => BlockReference.toJSON(e));
    }
    if (message.totalBytes !== 0) {
      obj.totalBytes = Math.round(message.totalBytes);
    }
    if (message.manifestSignature !== undefined) {
      obj.manifestSignature = Signature.toJSON(message.manifestSignature);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeltaManifest>, I>>(base?: I): DeltaManifest {
    return DeltaManifest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeltaManifest>, I>>(object: I): DeltaManifest {
    const message = createBaseDeltaManifest();
    message.vaultId = object.vaultId ?? "";
    message.baseVersion = object.baseVersion ?? 0;
    message.targetVersion = object.targetVersion ?? 0;
    message.changes = object.changes?.map((e) => EntryChange.fromPartial(e)) || [];
    message.blocks = object.blocks?.map((e) => BlockReference.fromPartial(e)) || [];
    message.totalBytes = object.totalBytes ?? 0;
    message.manifestSignature = (object.manifestSignature !== undefined && object.manifestSignature !== null)
      ? Signature.fromPartial(object.manifestSignature)
      : undefined;
    return message;
  },
};

messageTypeRegistry.set(DeltaManifest.$type, DeltaManifest);

function createBaseEntryChange(): EntryChange {
  return {
    $type: "synch.v1.EntryChange",
    path: "",
    operation: 0,
    contentHash: new Uint8Array(0),
    oldPath: "",
    deltaBytes: new Uint8Array(0),
    blockHashes: [],
    size: 0,
    modifiedAt: 0,
    originNodeId: "",
    originSequence: 0,
  };
}

export const EntryChange: MessageFns<EntryChange, "synch.v1.EntryChange"> = {
  $type: "synch.v1.EntryChange" as const,

  encode(message: EntryChange, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.path !== "") {
      writer.uint32(10).string(message.path);
    }
    if (message.operation !== 0) {
      writer.uint32(16).int32(message.operation);
    }
    if (message.contentHash.length !== 0) {
      writer.uint32(26).bytes(message.contentHash);
    }
    if (message.oldPath !== "") {
      writer.uint32(34).string(message.oldPath);
    }
    if (message.deltaBytes.length !== 0) {
      writer.uint32(42).bytes(message.deltaBytes);
    }
    for (const v of message.blockHashes) {
      writer.uint32(50).string(v!);
    }
    if (message.size !== 0) {
      writer.uint32(56).uint64(message.size);
    }
    if (message.modifiedAt !== 0) {
      writer.uint32(64).uint64(message.modifiedAt);
    }
    if (message.originNodeId !== "") {
      writer.uint32(74).string(message.originNodeId);
    }
    if (message.originSequence !== 0) {
      writer.uint32(80).uint64(message.originSequence);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EntryChange {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEntryChange();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.path = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.operation = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.contentHash = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.oldPath = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.deltaBytes = reader.bytes();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.blockHashes.push(reader.string());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.size = longToNumber(reader.uint64());
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.modifiedAt = longToNumber(reader.uint64());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.originNodeId = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.originSequence = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EntryChange {
    return {
      $type: EntryChange.$type,
      path: isSet(object.path) ? globalThis.String(object.path) : "",
      operation: isSet(object.operation) ? entryOperationFromJSON(object.operation) : 0,
      contentHash: isSet(object.contentHash)
        ? bytesFromBase64(object.contentHash)
        : isSet(object.content_hash)
        ? bytesFromBase64(object.content_hash)
        : new Uint8Array(0),
      oldPath: isSet(object.oldPath)
        ? globalThis.String(object.oldPath)
        : isSet(object.old_path)
        ? globalThis.String(object.old_path)
        : "",
      deltaBytes: isSet(object.deltaBytes)
        ? bytesFromBase64(object.deltaBytes)
        : isSet(object.delta_bytes)
        ? bytesFromBase64(object.delta_bytes)
        : new Uint8Array(0),
      blockHashes: globalThis.Array.isArray(object?.blockHashes)
        ? object.blockHashes.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.block_hashes)
        ? object.block_hashes.map((e: any) => globalThis.String(e))
        : [],
      size: isSet(object.size) ? globalThis.Number(object.size) : 0,
      modifiedAt: isSet(object.modifiedAt)
        ? globalThis.Number(object.modifiedAt)
        : isSet(object.modified_at)
        ? globalThis.Number(object.modified_at)
        : 0,
      originNodeId: isSet(object.originNodeId)
        ? globalThis.String(object.originNodeId)
        : isSet(object.origin_node_id)
        ? globalThis.String(object.origin_node_id)
        : "",
      originSequence: isSet(object.originSequence)
        ? globalThis.Number(object.originSequence)
        : isSet(object.origin_sequence)
        ? globalThis.Number(object.origin_sequence)
        : 0,
    };
  },

  toJSON(message: EntryChange): unknown {
    const obj: any = {};
    if (message.path !== "") {
      obj.path = message.path;
    }
    if (message.operation !== 0) {
      obj.operation = entryOperationToJSON(message.operation);
    }
    if (message.contentHash.length !== 0) {
      obj.contentHash = base64FromBytes(message.contentHash);
    }
    if (message.oldPath !== "") {
      obj.oldPath = message.oldPath;
    }
    if (message.deltaBytes.length !== 0) {
      obj.deltaBytes = base64FromBytes(message.deltaBytes);
    }
    if (message.blockHashes?.length) {
      obj.blockHashes = message.blockHashes;
    }
    if (message.size !== 0) {
      obj.size = Math.round(message.size);
    }
    if (message.modifiedAt !== 0) {
      obj.modifiedAt = Math.round(message.modifiedAt);
    }
    if (message.originNodeId !== "") {
      obj.originNodeId = message.originNodeId;
    }
    if (message.originSequence !== 0) {
      obj.originSequence = Math.round(message.originSequence);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EntryChange>, I>>(base?: I): EntryChange {
    return EntryChange.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EntryChange>, I>>(object: I): EntryChange {
    const message = createBaseEntryChange();
    message.path = object.path ?? "";
    message.operation = object.operation ?? 0;
    message.contentHash = object.contentHash ?? new Uint8Array(0);
    message.oldPath = object.oldPath ?? "";
    message.deltaBytes = object.deltaBytes ?? new Uint8Array(0);
    message.blockHashes = object.blockHashes?.map((e) => e) || [];
    message.size = object.size ?? 0;
    message.modifiedAt = object.modifiedAt ?? 0;
    message.originNodeId = object.originNodeId ?? "";
    message.originSequence = object.originSequence ?? 0;
    return message;
  },
};

messageTypeRegistry.set(EntryChange.$type, EntryChange);

function createBaseBlockReference(): BlockReference {
  return {
    $type: "synch.v1.BlockReference",
    blockHash: new Uint8Array(0),
    size: 0,
    offset: 0,
    encryptedData: new Uint8Array(0),
  };
}

export const BlockReference: MessageFns<BlockReference, "synch.v1.BlockReference"> = {
  $type: "synch.v1.BlockReference" as const,

  encode(message: BlockReference, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.blockHash.length !== 0) {
      writer.uint32(10).bytes(message.blockHash);
    }
    if (message.size !== 0) {
      writer.uint32(16).uint32(message.size);
    }
    if (message.offset !== 0) {
      writer.uint32(24).uint64(message.offset);
    }
    if (message.encryptedData.length !== 0) {
      writer.uint32(34).bytes(message.encryptedData);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): BlockReference {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBlockReference();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.blockHash = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.size = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.offset = longToNumber(reader.uint64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.encryptedData = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): BlockReference {
    return {
      $type: BlockReference.$type,
      blockHash: isSet(object.blockHash)
        ? bytesFromBase64(object.blockHash)
        : isSet(object.block_hash)
        ? bytesFromBase64(object.block_hash)
        : new Uint8Array(0),
      size: isSet(object.size) ? globalThis.Number(object.size) : 0,
      offset: isSet(object.offset) ? globalThis.Number(object.offset) : 0,
      encryptedData: isSet(object.encryptedData)
        ? bytesFromBase64(object.encryptedData)
        : isSet(object.encrypted_data)
        ? bytesFromBase64(object.encrypted_data)
        : new Uint8Array(0),
    };
  },

  toJSON(message: BlockReference): unknown {
    const obj: any = {};
    if (message.blockHash.length !== 0) {
      obj.blockHash = base64FromBytes(message.blockHash);
    }
    if (message.size !== 0) {
      obj.size = Math.round(message.size);
    }
    if (message.offset !== 0) {
      obj.offset = Math.round(message.offset);
    }
    if (message.encryptedData.length !== 0) {
      obj.encryptedData = base64FromBytes(message.encryptedData);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<BlockReference>, I>>(base?: I): BlockReference {
    return BlockReference.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<BlockReference>, I>>(object: I): BlockReference {
    const message = createBaseBlockReference();
    message.blockHash = object.blockHash ?? new Uint8Array(0);
    message.size = object.size ?? 0;
    message.offset = object.offset ?? 0;
    message.encryptedData = object.encryptedData ?? new Uint8Array(0);
    return message;
  },
};

messageTypeRegistry.set(BlockReference.$type, BlockReference);

function createBaseDeltaAck(): DeltaAck {
  return { $type: "synch.v1.DeltaAck", vaultId: "", ackedVersion: 0, success: false, errorMessage: "" };
}

export const DeltaAck: MessageFns<DeltaAck, "synch.v1.DeltaAck"> = {
  $type: "synch.v1.DeltaAck" as const,

  encode(message: DeltaAck, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.vaultId !== "") {
      writer.uint32(10).string(message.vaultId);
    }
    if (message.ackedVersion !== 0) {
      writer.uint32(16).uint64(message.ackedVersion);
    }
    if (message.success !== false) {
      writer.uint32(24).bool(message.success);
    }
    if (message.errorMessage !== "") {
      writer.uint32(34).string(message.errorMessage);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeltaAck {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeltaAck();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.vaultId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.ackedVersion = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeltaAck {
    return {
      $type: DeltaAck.$type,
      vaultId: isSet(object.vaultId)
        ? globalThis.String(object.vaultId)
        : isSet(object.vault_id)
        ? globalThis.String(object.vault_id)
        : "",
      ackedVersion: isSet(object.ackedVersion)
        ? globalThis.Number(object.ackedVersion)
        : isSet(object.acked_version)
        ? globalThis.Number(object.acked_version)
        : 0,
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      errorMessage: isSet(object.errorMessage)
        ? globalThis.String(object.errorMessage)
        : isSet(object.error_message)
        ? globalThis.String(object.error_message)
        : "",
    };
  },

  toJSON(message: DeltaAck): unknown {
    const obj: any = {};
    if (message.vaultId !== "") {
      obj.vaultId = message.vaultId;
    }
    if (message.ackedVersion !== 0) {
      obj.ackedVersion = Math.round(message.ackedVersion);
    }
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.errorMessage !== "") {
      obj.errorMessage = message.errorMessage;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeltaAck>, I>>(base?: I): DeltaAck {
    return DeltaAck.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeltaAck>, I>>(object: I): DeltaAck {
    const message = createBaseDeltaAck();
    message.vaultId = object.vaultId ?? "";
    message.ackedVersion = object.ackedVersion ?? 0;
    message.success = object.success ?? false;
    message.errorMessage = object.errorMessage ?? "";
    return message;
  },
};

messageTypeRegistry.set(DeltaAck.$type, DeltaAck);

function createBaseSyncProgress(): SyncProgress {
  return {
    $type: "synch.v1.SyncProgress",
    vaultId: "",
    totalEntries: 0,
    completedEntries: 0,
    totalBytes: 0,
    transferredBytes: 0,
    currentState: 0,
  };
}

export const SyncProgress: MessageFns<SyncProgress, "synch.v1.SyncProgress"> = {
  $type: "synch.v1.SyncProgress" as const,

  encode(message: SyncProgress, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.vaultId !== "") {
      writer.uint32(10).string(message.vaultId);
    }
    if (message.totalEntries !== 0) {
      writer.uint32(16).uint64(message.totalEntries);
    }
    if (message.completedEntries !== 0) {
      writer.uint32(24).uint64(message.completedEntries);
    }
    if (message.totalBytes !== 0) {
      writer.uint32(32).uint64(message.totalBytes);
    }
    if (message.transferredBytes !== 0) {
      writer.uint32(40).uint64(message.transferredBytes);
    }
    if (message.currentState !== 0) {
      writer.uint32(48).int32(message.currentState);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SyncProgress {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSyncProgress();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.vaultId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.totalEntries = longToNumber(reader.uint64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.completedEntries = longToNumber(reader.uint64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.totalBytes = longToNumber(reader.uint64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.transferredBytes = longToNumber(reader.uint64());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.currentState = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SyncProgress {
    return {
      $type: SyncProgress.$type,
      vaultId: isSet(object.vaultId)
        ? globalThis.String(object.vaultId)
        : isSet(object.vault_id)
        ? globalThis.String(object.vault_id)
        : "",
      totalEntries: isSet(object.totalEntries)
        ? globalThis.Number(object.totalEntries)
        : isSet(object.total_entries)
        ? globalThis.Number(object.total_entries)
        : 0,
      completedEntries: isSet(object.completedEntries)
        ? globalThis.Number(object.completedEntries)
        : isSet(object.completed_entries)
        ? globalThis.Number(object.completed_entries)
        : 0,
      totalBytes: isSet(object.totalBytes)
        ? globalThis.Number(object.totalBytes)
        : isSet(object.total_bytes)
        ? globalThis.Number(object.total_bytes)
        : 0,
      transferredBytes: isSet(object.transferredBytes)
        ? globalThis.Number(object.transferredBytes)
        : isSet(object.transferred_bytes)
        ? globalThis.Number(object.transferred_bytes)
        : 0,
      currentState: isSet(object.currentState)
        ? syncStateFromJSON(object.currentState)
        : isSet(object.current_state)
        ? syncStateFromJSON(object.current_state)
        : 0,
    };
  },

  toJSON(message: SyncProgress): unknown {
    const obj: any = {};
    if (message.vaultId !== "") {
      obj.vaultId = message.vaultId;
    }
    if (message.totalEntries !== 0) {
      obj.totalEntries = Math.round(message.totalEntries);
    }
    if (message.completedEntries !== 0) {
      obj.completedEntries = Math.round(message.completedEntries);
    }
    if (message.totalBytes !== 0) {
      obj.totalBytes = Math.round(message.totalBytes);
    }
    if (message.transferredBytes !== 0) {
      obj.transferredBytes = Math.round(message.transferredBytes);
    }
    if (message.currentState !== 0) {
      obj.currentState = syncStateToJSON(message.currentState);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SyncProgress>, I>>(base?: I): SyncProgress {
    return SyncProgress.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SyncProgress>, I>>(object: I): SyncProgress {
    const message = createBaseSyncProgress();
    message.vaultId = object.vaultId ?? "";
    message.totalEntries = object.totalEntries ?? 0;
    message.completedEntries = object.completedEntries ?? 0;
    message.totalBytes = object.totalBytes ?? 0;
    message.transferredBytes = object.transferredBytes ?? 0;
    message.currentState = object.currentState ?? 0;
    return message;
  },
};

messageTypeRegistry.set(SyncProgress.$type, SyncProgress);

function createBaseConflictDetected(): ConflictDetected {
  return {
    $type: "synch.v1.ConflictDetected",
    vaultId: "",
    path: "",
    localVersion: undefined,
    remoteVersion: undefined,
    suggestedResolution: 0,
  };
}

export const ConflictDetected: MessageFns<ConflictDetected, "synch.v1.ConflictDetected"> = {
  $type: "synch.v1.ConflictDetected" as const,

  encode(message: ConflictDetected, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.vaultId !== "") {
      writer.uint32(10).string(message.vaultId);
    }
    if (message.path !== "") {
      writer.uint32(18).string(message.path);
    }
    if (message.localVersion !== undefined) {
      EntryChange.encode(message.localVersion, writer.uint32(26).fork()).join();
    }
    if (message.remoteVersion !== undefined) {
      EntryChange.encode(message.remoteVersion, writer.uint32(34).fork()).join();
    }
    if (message.suggestedResolution !== 0) {
      writer.uint32(40).int32(message.suggestedResolution);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ConflictDetected {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConflictDetected();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.vaultId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.path = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.localVersion = EntryChange.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.remoteVersion = EntryChange.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.suggestedResolution = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ConflictDetected {
    return {
      $type: ConflictDetected.$type,
      vaultId: isSet(object.vaultId)
        ? globalThis.String(object.vaultId)
        : isSet(object.vault_id)
        ? globalThis.String(object.vault_id)
        : "",
      path: isSet(object.path) ? globalThis.String(object.path) : "",
      localVersion: isSet(object.localVersion)
        ? EntryChange.fromJSON(object.localVersion)
        : isSet(object.local_version)
        ? EntryChange.fromJSON(object.local_version)
        : undefined,
      remoteVersion: isSet(object.remoteVersion)
        ? EntryChange.fromJSON(object.remoteVersion)
        : isSet(object.remote_version)
        ? EntryChange.fromJSON(object.remote_version)
        : undefined,
      suggestedResolution: isSet(object.suggestedResolution)
        ? conflictResolutionFromJSON(object.suggestedResolution)
        : isSet(object.suggested_resolution)
        ? conflictResolutionFromJSON(object.suggested_resolution)
        : 0,
    };
  },

  toJSON(message: ConflictDetected): unknown {
    const obj: any = {};
    if (message.vaultId !== "") {
      obj.vaultId = message.vaultId;
    }
    if (message.path !== "") {
      obj.path = message.path;
    }
    if (message.localVersion !== undefined) {
      obj.localVersion = EntryChange.toJSON(message.localVersion);
    }
    if (message.remoteVersion !== undefined) {
      obj.remoteVersion = EntryChange.toJSON(message.remoteVersion);
    }
    if (message.suggestedResolution !== 0) {
      obj.suggestedResolution = conflictResolutionToJSON(message.suggestedResolution);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ConflictDetected>, I>>(base?: I): ConflictDetected {
    return ConflictDetected.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ConflictDetected>, I>>(object: I): ConflictDetected {
    const message = createBaseConflictDetected();
    message.vaultId = object.vaultId ?? "";
    message.path = object.path ?? "";
    message.localVersion = (object.localVersion !== undefined && object.localVersion !== null)
      ? EntryChange.fromPartial(object.localVersion)
      : undefined;
    message.remoteVersion = (object.remoteVersion !== undefined && object.remoteVersion !== null)
      ? EntryChange.fromPartial(object.remoteVersion)
      : undefined;
    message.suggestedResolution = object.suggestedResolution ?? 0;
    return message;
  },
};

messageTypeRegistry.set(ConflictDetected.$type, ConflictDetected);

function createBasePresenceUpdate(): PresenceUpdate {
  return { $type: "synch.v1.PresenceUpdate", nodeId: "", status: 0, lastSeen: 0, activeVaultId: "" };
}

export const PresenceUpdate: MessageFns<PresenceUpdate, "synch.v1.PresenceUpdate"> = {
  $type: "synch.v1.PresenceUpdate" as const,

  encode(message: PresenceUpdate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.nodeId !== "") {
      writer.uint32(10).string(message.nodeId);
    }
    if (message.status !== 0) {
      writer.uint32(16).int32(message.status);
    }
    if (message.lastSeen !== 0) {
      writer.uint32(24).uint64(message.lastSeen);
    }
    if (message.activeVaultId !== "") {
      writer.uint32(34).string(message.activeVaultId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PresenceUpdate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePresenceUpdate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.nodeId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.lastSeen = longToNumber(reader.uint64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.activeVaultId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PresenceUpdate {
    return {
      $type: PresenceUpdate.$type,
      nodeId: isSet(object.nodeId)
        ? globalThis.String(object.nodeId)
        : isSet(object.node_id)
        ? globalThis.String(object.node_id)
        : "",
      status: isSet(object.status) ? presenceStatusFromJSON(object.status) : 0,
      lastSeen: isSet(object.lastSeen)
        ? globalThis.Number(object.lastSeen)
        : isSet(object.last_seen)
        ? globalThis.Number(object.last_seen)
        : 0,
      activeVaultId: isSet(object.activeVaultId)
        ? globalThis.String(object.activeVaultId)
        : isSet(object.active_vault_id)
        ? globalThis.String(object.active_vault_id)
        : "",
    };
  },

  toJSON(message: PresenceUpdate): unknown {
    const obj: any = {};
    if (message.nodeId !== "") {
      obj.nodeId = message.nodeId;
    }
    if (message.status !== 0) {
      obj.status = presenceStatusToJSON(message.status);
    }
    if (message.lastSeen !== 0) {
      obj.lastSeen = Math.round(message.lastSeen);
    }
    if (message.activeVaultId !== "") {
      obj.activeVaultId = message.activeVaultId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PresenceUpdate>, I>>(base?: I): PresenceUpdate {
    return PresenceUpdate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PresenceUpdate>, I>>(object: I): PresenceUpdate {
    const message = createBasePresenceUpdate();
    message.nodeId = object.nodeId ?? "";
    message.status = object.status ?? 0;
    message.lastSeen = object.lastSeen ?? 0;
    message.activeVaultId = object.activeVaultId ?? "";
    return message;
  },
};

messageTypeRegistry.set(PresenceUpdate.$type, PresenceUpdate);

function bytesFromBase64(b64: string): Uint8Array {
  const bin = globalThis.atob(b64);
  const arr = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; ++i) {
    arr[i] = bin.charCodeAt(i);
  }
  return arr;
}

function base64FromBytes(arr: Uint8Array): string {
  const bin: string[] = [];
  arr.forEach((byte) => {
    bin.push(globalThis.String.fromCharCode(byte));
  });
  return globalThis.btoa(bin.join(""));
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in Exclude<keyof T, "$type">]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P> | "$type">]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T, V extends string> {
  readonly $type: V;
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
