// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               unknown
// source: v1/synch.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { messageTypeRegistry } from "../typeRegistry";

export const protobufPackage = "synch.v1";

/**
 * SYNCH 心契协议 — 主协议定义
 * 包含：节点身份、多服务端会话、权限模型
 */

/** NodeType 标识节点的角色类型 */
export enum NodeType {
  NODE_TYPE_UNSPECIFIED = 0,
  /** NODE_TYPE_AGENT - AI助手、自动化脚本 */
  NODE_TYPE_AGENT = 1,
  /** NODE_TYPE_HUMAN - 人、管理员 */
  NODE_TYPE_HUMAN = 2,
  /** NODE_TYPE_BRIDGE - 协议转换、外部系统对接 */
  NODE_TYPE_BRIDGE = 3,
  /** NODE_TYPE_PLUGIN - 宿主环境插件 (vcp-agent, openclaw-agent) */
  NODE_TYPE_PLUGIN = 4,
  /** NODE_TYPE_MOBILE - 移动端 App (Android/iOS) */
  NODE_TYPE_MOBILE = 5,
  UNRECOGNIZED = -1,
}

export function nodeTypeFromJSON(object: any): NodeType {
  switch (object) {
    case 0:
    case "NODE_TYPE_UNSPECIFIED":
      return NodeType.NODE_TYPE_UNSPECIFIED;
    case 1:
    case "NODE_TYPE_AGENT":
      return NodeType.NODE_TYPE_AGENT;
    case 2:
    case "NODE_TYPE_HUMAN":
      return NodeType.NODE_TYPE_HUMAN;
    case 3:
    case "NODE_TYPE_BRIDGE":
      return NodeType.NODE_TYPE_BRIDGE;
    case 4:
    case "NODE_TYPE_PLUGIN":
      return NodeType.NODE_TYPE_PLUGIN;
    case 5:
    case "NODE_TYPE_MOBILE":
      return NodeType.NODE_TYPE_MOBILE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return NodeType.UNRECOGNIZED;
  }
}

export function nodeTypeToJSON(object: NodeType): string {
  switch (object) {
    case NodeType.NODE_TYPE_UNSPECIFIED:
      return "NODE_TYPE_UNSPECIFIED";
    case NodeType.NODE_TYPE_AGENT:
      return "NODE_TYPE_AGENT";
    case NodeType.NODE_TYPE_HUMAN:
      return "NODE_TYPE_HUMAN";
    case NodeType.NODE_TYPE_BRIDGE:
      return "NODE_TYPE_BRIDGE";
    case NodeType.NODE_TYPE_PLUGIN:
      return "NODE_TYPE_PLUGIN";
    case NodeType.NODE_TYPE_MOBILE:
      return "NODE_TYPE_MOBILE";
    case NodeType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** ServerRole 标识客户端与服务端的关系 */
export enum ServerRole {
  SERVER_ROLE_UNSPECIFIED = 0,
  /** SERVER_ROLE_PRIMARY - 主服务端，拥有完整权限 */
  SERVER_ROLE_PRIMARY = 1,
  /** SERVER_ROLE_SECONDARY - 备用/镜像服务端 */
  SERVER_ROLE_SECONDARY = 2,
  /** SERVER_ROLE_GUEST - 访客身份，受限权限 */
  SERVER_ROLE_GUEST = 3,
  UNRECOGNIZED = -1,
}

export function serverRoleFromJSON(object: any): ServerRole {
  switch (object) {
    case 0:
    case "SERVER_ROLE_UNSPECIFIED":
      return ServerRole.SERVER_ROLE_UNSPECIFIED;
    case 1:
    case "SERVER_ROLE_PRIMARY":
      return ServerRole.SERVER_ROLE_PRIMARY;
    case 2:
    case "SERVER_ROLE_SECONDARY":
      return ServerRole.SERVER_ROLE_SECONDARY;
    case 3:
    case "SERVER_ROLE_GUEST":
      return ServerRole.SERVER_ROLE_GUEST;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ServerRole.UNRECOGNIZED;
  }
}

export function serverRoleToJSON(object: ServerRole): string {
  switch (object) {
    case ServerRole.SERVER_ROLE_UNSPECIFIED:
      return "SERVER_ROLE_UNSPECIFIED";
    case ServerRole.SERVER_ROLE_PRIMARY:
      return "SERVER_ROLE_PRIMARY";
    case ServerRole.SERVER_ROLE_SECONDARY:
      return "SERVER_ROLE_SECONDARY";
    case ServerRole.SERVER_ROLE_GUEST:
      return "SERVER_ROLE_GUEST";
    case ServerRole.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** PermissionLevel 标识对 Vault 的操作权限 */
export enum PermissionLevel {
  PERMISSION_LEVEL_UNSPECIFIED = 0,
  /** PERMISSION_LEVEL_READ - 只读 */
  PERMISSION_LEVEL_READ = 1,
  /** PERMISSION_LEVEL_WRITE - 读写 */
  PERMISSION_LEVEL_WRITE = 2,
  /** PERMISSION_LEVEL_ADMIN - 完全控制 (含 ACL 管理) */
  PERMISSION_LEVEL_ADMIN = 3,
  UNRECOGNIZED = -1,
}

export function permissionLevelFromJSON(object: any): PermissionLevel {
  switch (object) {
    case 0:
    case "PERMISSION_LEVEL_UNSPECIFIED":
      return PermissionLevel.PERMISSION_LEVEL_UNSPECIFIED;
    case 1:
    case "PERMISSION_LEVEL_READ":
      return PermissionLevel.PERMISSION_LEVEL_READ;
    case 2:
    case "PERMISSION_LEVEL_WRITE":
      return PermissionLevel.PERMISSION_LEVEL_WRITE;
    case 3:
    case "PERMISSION_LEVEL_ADMIN":
      return PermissionLevel.PERMISSION_LEVEL_ADMIN;
    case -1:
    case "UNRECOGNIZED":
    default:
      return PermissionLevel.UNRECOGNIZED;
  }
}

export function permissionLevelToJSON(object: PermissionLevel): string {
  switch (object) {
    case PermissionLevel.PERMISSION_LEVEL_UNSPECIFIED:
      return "PERMISSION_LEVEL_UNSPECIFIED";
    case PermissionLevel.PERMISSION_LEVEL_READ:
      return "PERMISSION_LEVEL_READ";
    case PermissionLevel.PERMISSION_LEVEL_WRITE:
      return "PERMISSION_LEVEL_WRITE";
    case PermissionLevel.PERMISSION_LEVEL_ADMIN:
      return "PERMISSION_LEVEL_ADMIN";
    case PermissionLevel.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** ConflictStrategy 冲突解决策略枚举 */
export enum ConflictStrategy {
  CONFLICT_STRATEGY_UNSPECIFIED = 0,
  /** CONFLICT_STRATEGY_AUTO_LOCAL - 本地优先 */
  CONFLICT_STRATEGY_AUTO_LOCAL = 1,
  /** CONFLICT_STRATEGY_AUTO_REMOTE - 远端优先 */
  CONFLICT_STRATEGY_AUTO_REMOTE = 2,
  /** CONFLICT_STRATEGY_ASK - 询问用户 */
  CONFLICT_STRATEGY_ASK = 3,
  UNRECOGNIZED = -1,
}

export function conflictStrategyFromJSON(object: any): ConflictStrategy {
  switch (object) {
    case 0:
    case "CONFLICT_STRATEGY_UNSPECIFIED":
      return ConflictStrategy.CONFLICT_STRATEGY_UNSPECIFIED;
    case 1:
    case "CONFLICT_STRATEGY_AUTO_LOCAL":
      return ConflictStrategy.CONFLICT_STRATEGY_AUTO_LOCAL;
    case 2:
    case "CONFLICT_STRATEGY_AUTO_REMOTE":
      return ConflictStrategy.CONFLICT_STRATEGY_AUTO_REMOTE;
    case 3:
    case "CONFLICT_STRATEGY_ASK":
      return ConflictStrategy.CONFLICT_STRATEGY_ASK;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ConflictStrategy.UNRECOGNIZED;
  }
}

export function conflictStrategyToJSON(object: ConflictStrategy): string {
  switch (object) {
    case ConflictStrategy.CONFLICT_STRATEGY_UNSPECIFIED:
      return "CONFLICT_STRATEGY_UNSPECIFIED";
    case ConflictStrategy.CONFLICT_STRATEGY_AUTO_LOCAL:
      return "CONFLICT_STRATEGY_AUTO_LOCAL";
    case ConflictStrategy.CONFLICT_STRATEGY_AUTO_REMOTE:
      return "CONFLICT_STRATEGY_AUTO_REMOTE";
    case ConflictStrategy.CONFLICT_STRATEGY_ASK:
      return "CONFLICT_STRATEGY_ASK";
    case ConflictStrategy.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** MobileSyncPolicy 移动端同步策略 */
export enum MobileSyncPolicy {
  MOBILE_SYNC_POLICY_UNSPECIFIED = 0,
  /** MOBILE_SYNC_POLICY_ALWAYS - 始终同步 */
  MOBILE_SYNC_POLICY_ALWAYS = 1,
  /** MOBILE_SYNC_POLICY_WIFI_ONLY - 仅在 Wi-Fi 下同步 */
  MOBILE_SYNC_POLICY_WIFI_ONLY = 2,
  /** MOBILE_SYNC_POLICY_MANUAL - 手动触发 */
  MOBILE_SYNC_POLICY_MANUAL = 3,
  UNRECOGNIZED = -1,
}

export function mobileSyncPolicyFromJSON(object: any): MobileSyncPolicy {
  switch (object) {
    case 0:
    case "MOBILE_SYNC_POLICY_UNSPECIFIED":
      return MobileSyncPolicy.MOBILE_SYNC_POLICY_UNSPECIFIED;
    case 1:
    case "MOBILE_SYNC_POLICY_ALWAYS":
      return MobileSyncPolicy.MOBILE_SYNC_POLICY_ALWAYS;
    case 2:
    case "MOBILE_SYNC_POLICY_WIFI_ONLY":
      return MobileSyncPolicy.MOBILE_SYNC_POLICY_WIFI_ONLY;
    case 3:
    case "MOBILE_SYNC_POLICY_MANUAL":
      return MobileSyncPolicy.MOBILE_SYNC_POLICY_MANUAL;
    case -1:
    case "UNRECOGNIZED":
    default:
      return MobileSyncPolicy.UNRECOGNIZED;
  }
}

export function mobileSyncPolicyToJSON(object: MobileSyncPolicy): string {
  switch (object) {
    case MobileSyncPolicy.MOBILE_SYNC_POLICY_UNSPECIFIED:
      return "MOBILE_SYNC_POLICY_UNSPECIFIED";
    case MobileSyncPolicy.MOBILE_SYNC_POLICY_ALWAYS:
      return "MOBILE_SYNC_POLICY_ALWAYS";
    case MobileSyncPolicy.MOBILE_SYNC_POLICY_WIFI_ONLY:
      return "MOBILE_SYNC_POLICY_WIFI_ONLY";
    case MobileSyncPolicy.MOBILE_SYNC_POLICY_MANUAL:
      return "MOBILE_SYNC_POLICY_MANUAL";
    case MobileSyncPolicy.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** NodeIdentity 描述网络中的一个节点身份 */
export interface NodeIdentity {
  $type: "synch.v1.NodeIdentity";
  /** 节点唯一标识, 格式: "agent://{pk}" | "plugin://{pk}" | "mobile://{pk}" ... */
  nodeId: string;
  /** Ed25519 公钥 (32 bytes) */
  publicKey: Uint8Array;
  /** 节点类型 */
  nodeType: NodeType;
  /** 宿主平台: "vcp-agent" | "openclaw" | "android" | "ios" ... */
  platform: string;
  /** 能力声明: "chat", "tools", "rag-local", "vault-sync", "ui-panel" ... */
  capabilities: string[];
  /** 注册时间 (Unix epoch millis) */
  registeredAt: number;
  /** 人类可读的显示名称 */
  displayName: string;
}

/** ServerEndpoint 描述一个客户端连接的服务端 */
export interface ServerEndpoint {
  $type: "synch.v1.ServerEndpoint";
  /** 服务端唯一 ID (如 "home-fnos", "friend-bob") */
  serverId: string;
  /** WebSocket/gRPC 连接地址 (如 "wss://home.synch.local:8081") */
  url: string;
  /** 此客户端在该服务端上的角色 */
  role: ServerRole;
  /** 该服务端上各 Vault 的权限映射: vault_id -> VaultPermission */
  vaultAccess: { [key: string]: VaultPermission };
  /** 人类可读的服务端名称 (如 "家里心契") */
  displayName: string;
  /** 是否自动连接 */
  autoConnect: boolean;
  /** 邀请码 (用于 GUEST 角色加入) */
  inviteCode: string;
}

export interface ServerEndpoint_VaultAccessEntry {
  $type: "synch.v1.ServerEndpoint.VaultAccessEntry";
  key: string;
  value: VaultPermission | undefined;
}

/** VaultPermission 描述对单个 Vault 的权限 */
export interface VaultPermission {
  $type: "synch.v1.VaultPermission";
  /** Vault 唯一 ID: Blake3(vault_root_path + owner_pubkey)[0:16] */
  vaultId: string;
  /** 权限级别 */
  level: PermissionLevel;
  /** 用设备密钥加密的 Vault 密钥 (AES-256-GCM wrapped) */
  vaultKeyEncrypted: Uint8Array;
}

/** ClientProfile 描述客户端的身份与多服务端配置 */
export interface ClientProfile {
  $type: "synch.v1.ClientProfile";
  /** 此客户端的身份 */
  identity:
    | NodeIdentity
    | undefined;
  /** 连接的所有服务端 */
  servers: ServerEndpoint[];
  /** 同步配置 */
  syncConfig: SyncConfig | undefined;
}

/** SyncConfig 全局同步偏好设置 */
export interface SyncConfig {
  $type: "synch.v1.SyncConfig";
  /** 冲突处理策略 */
  conflictStrategy: ConflictStrategy;
  /** 带宽限制 (KB/s), 0 = 无限制 */
  bandwidthLimitKbps: number;
  /** 移动网络同步策略 */
  mobileSyncPolicy: MobileSyncPolicy;
}

function createBaseNodeIdentity(): NodeIdentity {
  return {
    $type: "synch.v1.NodeIdentity",
    nodeId: "",
    publicKey: new Uint8Array(0),
    nodeType: 0,
    platform: "",
    capabilities: [],
    registeredAt: 0,
    displayName: "",
  };
}

export const NodeIdentity: MessageFns<NodeIdentity, "synch.v1.NodeIdentity"> = {
  $type: "synch.v1.NodeIdentity" as const,

  encode(message: NodeIdentity, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.nodeId !== "") {
      writer.uint32(10).string(message.nodeId);
    }
    if (message.publicKey.length !== 0) {
      writer.uint32(18).bytes(message.publicKey);
    }
    if (message.nodeType !== 0) {
      writer.uint32(24).int32(message.nodeType);
    }
    if (message.platform !== "") {
      writer.uint32(34).string(message.platform);
    }
    for (const v of message.capabilities) {
      writer.uint32(42).string(v!);
    }
    if (message.registeredAt !== 0) {
      writer.uint32(48).uint64(message.registeredAt);
    }
    if (message.displayName !== "") {
      writer.uint32(58).string(message.displayName);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NodeIdentity {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNodeIdentity();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.nodeId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.publicKey = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.nodeType = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.platform = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.capabilities.push(reader.string());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.registeredAt = longToNumber(reader.uint64());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.displayName = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NodeIdentity {
    return {
      $type: NodeIdentity.$type,
      nodeId: isSet(object.nodeId)
        ? globalThis.String(object.nodeId)
        : isSet(object.node_id)
        ? globalThis.String(object.node_id)
        : "",
      publicKey: isSet(object.publicKey)
        ? bytesFromBase64(object.publicKey)
        : isSet(object.public_key)
        ? bytesFromBase64(object.public_key)
        : new Uint8Array(0),
      nodeType: isSet(object.nodeType)
        ? nodeTypeFromJSON(object.nodeType)
        : isSet(object.node_type)
        ? nodeTypeFromJSON(object.node_type)
        : 0,
      platform: isSet(object.platform) ? globalThis.String(object.platform) : "",
      capabilities: globalThis.Array.isArray(object?.capabilities)
        ? object.capabilities.map((e: any) => globalThis.String(e))
        : [],
      registeredAt: isSet(object.registeredAt)
        ? globalThis.Number(object.registeredAt)
        : isSet(object.registered_at)
        ? globalThis.Number(object.registered_at)
        : 0,
      displayName: isSet(object.displayName)
        ? globalThis.String(object.displayName)
        : isSet(object.display_name)
        ? globalThis.String(object.display_name)
        : "",
    };
  },

  toJSON(message: NodeIdentity): unknown {
    const obj: any = {};
    if (message.nodeId !== "") {
      obj.nodeId = message.nodeId;
    }
    if (message.publicKey.length !== 0) {
      obj.publicKey = base64FromBytes(message.publicKey);
    }
    if (message.nodeType !== 0) {
      obj.nodeType = nodeTypeToJSON(message.nodeType);
    }
    if (message.platform !== "") {
      obj.platform = message.platform;
    }
    if (message.capabilities?.length) {
      obj.capabilities = message.capabilities;
    }
    if (message.registeredAt !== 0) {
      obj.registeredAt = Math.round(message.registeredAt);
    }
    if (message.displayName !== "") {
      obj.displayName = message.displayName;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NodeIdentity>, I>>(base?: I): NodeIdentity {
    return NodeIdentity.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NodeIdentity>, I>>(object: I): NodeIdentity {
    const message = createBaseNodeIdentity();
    message.nodeId = object.nodeId ?? "";
    message.publicKey = object.publicKey ?? new Uint8Array(0);
    message.nodeType = object.nodeType ?? 0;
    message.platform = object.platform ?? "";
    message.capabilities = object.capabilities?.map((e) => e) || [];
    message.registeredAt = object.registeredAt ?? 0;
    message.displayName = object.displayName ?? "";
    return message;
  },
};

messageTypeRegistry.set(NodeIdentity.$type, NodeIdentity);

function createBaseServerEndpoint(): ServerEndpoint {
  return {
    $type: "synch.v1.ServerEndpoint",
    serverId: "",
    url: "",
    role: 0,
    vaultAccess: {},
    displayName: "",
    autoConnect: false,
    inviteCode: "",
  };
}

export const ServerEndpoint: MessageFns<ServerEndpoint, "synch.v1.ServerEndpoint"> = {
  $type: "synch.v1.ServerEndpoint" as const,

  encode(message: ServerEndpoint, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serverId !== "") {
      writer.uint32(10).string(message.serverId);
    }
    if (message.url !== "") {
      writer.uint32(18).string(message.url);
    }
    if (message.role !== 0) {
      writer.uint32(24).int32(message.role);
    }
    globalThis.Object.entries(message.vaultAccess).forEach(([key, value]: [string, VaultPermission]) => {
      ServerEndpoint_VaultAccessEntry.encode({
        $type: "synch.v1.ServerEndpoint.VaultAccessEntry",
        key: key as any,
        value,
      }, writer.uint32(34).fork()).join();
    });
    if (message.displayName !== "") {
      writer.uint32(42).string(message.displayName);
    }
    if (message.autoConnect !== false) {
      writer.uint32(48).bool(message.autoConnect);
    }
    if (message.inviteCode !== "") {
      writer.uint32(58).string(message.inviteCode);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ServerEndpoint {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServerEndpoint();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serverId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.url = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.role = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          const entry4 = ServerEndpoint_VaultAccessEntry.decode(reader, reader.uint32());
          if (entry4.value !== undefined) {
            message.vaultAccess[entry4.key] = entry4.value;
          }
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.displayName = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.autoConnect = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.inviteCode = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServerEndpoint {
    return {
      $type: ServerEndpoint.$type,
      serverId: isSet(object.serverId)
        ? globalThis.String(object.serverId)
        : isSet(object.server_id)
        ? globalThis.String(object.server_id)
        : "",
      url: isSet(object.url) ? globalThis.String(object.url) : "",
      role: isSet(object.role) ? serverRoleFromJSON(object.role) : 0,
      vaultAccess: isObject(object.vaultAccess)
        ? (globalThis.Object.entries(object.vaultAccess) as [string, any][]).reduce(
          (acc: { [key: string]: VaultPermission }, [key, value]: [string, any]) => {
            acc[key] = VaultPermission.fromJSON(value);
            return acc;
          },
          {},
        )
        : isObject(object.vault_access)
        ? (globalThis.Object.entries(object.vault_access) as [string, any][]).reduce(
          (acc: { [key: string]: VaultPermission }, [key, value]: [string, any]) => {
            acc[key] = VaultPermission.fromJSON(value);
            return acc;
          },
          {},
        )
        : {},
      displayName: isSet(object.displayName)
        ? globalThis.String(object.displayName)
        : isSet(object.display_name)
        ? globalThis.String(object.display_name)
        : "",
      autoConnect: isSet(object.autoConnect)
        ? globalThis.Boolean(object.autoConnect)
        : isSet(object.auto_connect)
        ? globalThis.Boolean(object.auto_connect)
        : false,
      inviteCode: isSet(object.inviteCode)
        ? globalThis.String(object.inviteCode)
        : isSet(object.invite_code)
        ? globalThis.String(object.invite_code)
        : "",
    };
  },

  toJSON(message: ServerEndpoint): unknown {
    const obj: any = {};
    if (message.serverId !== "") {
      obj.serverId = message.serverId;
    }
    if (message.url !== "") {
      obj.url = message.url;
    }
    if (message.role !== 0) {
      obj.role = serverRoleToJSON(message.role);
    }
    if (message.vaultAccess) {
      const entries = globalThis.Object.entries(message.vaultAccess) as [string, VaultPermission][];
      if (entries.length > 0) {
        obj.vaultAccess = {};
        entries.forEach(([k, v]) => {
          obj.vaultAccess[k] = VaultPermission.toJSON(v);
        });
      }
    }
    if (message.displayName !== "") {
      obj.displayName = message.displayName;
    }
    if (message.autoConnect !== false) {
      obj.autoConnect = message.autoConnect;
    }
    if (message.inviteCode !== "") {
      obj.inviteCode = message.inviteCode;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServerEndpoint>, I>>(base?: I): ServerEndpoint {
    return ServerEndpoint.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServerEndpoint>, I>>(object: I): ServerEndpoint {
    const message = createBaseServerEndpoint();
    message.serverId = object.serverId ?? "";
    message.url = object.url ?? "";
    message.role = object.role ?? 0;
    message.vaultAccess = (globalThis.Object.entries(object.vaultAccess ?? {}) as [string, VaultPermission][]).reduce(
      (acc: { [key: string]: VaultPermission }, [key, value]: [string, VaultPermission]) => {
        if (value !== undefined) {
          acc[key] = VaultPermission.fromPartial(value);
        }
        return acc;
      },
      {},
    );
    message.displayName = object.displayName ?? "";
    message.autoConnect = object.autoConnect ?? false;
    message.inviteCode = object.inviteCode ?? "";
    return message;
  },
};

messageTypeRegistry.set(ServerEndpoint.$type, ServerEndpoint);

function createBaseServerEndpoint_VaultAccessEntry(): ServerEndpoint_VaultAccessEntry {
  return { $type: "synch.v1.ServerEndpoint.VaultAccessEntry", key: "", value: undefined };
}

export const ServerEndpoint_VaultAccessEntry: MessageFns<
  ServerEndpoint_VaultAccessEntry,
  "synch.v1.ServerEndpoint.VaultAccessEntry"
> = {
  $type: "synch.v1.ServerEndpoint.VaultAccessEntry" as const,

  encode(message: ServerEndpoint_VaultAccessEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== undefined) {
      VaultPermission.encode(message.value, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ServerEndpoint_VaultAccessEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServerEndpoint_VaultAccessEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = VaultPermission.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServerEndpoint_VaultAccessEntry {
    return {
      $type: ServerEndpoint_VaultAccessEntry.$type,
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? VaultPermission.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: ServerEndpoint_VaultAccessEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = VaultPermission.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServerEndpoint_VaultAccessEntry>, I>>(base?: I): ServerEndpoint_VaultAccessEntry {
    return ServerEndpoint_VaultAccessEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServerEndpoint_VaultAccessEntry>, I>>(
    object: I,
  ): ServerEndpoint_VaultAccessEntry {
    const message = createBaseServerEndpoint_VaultAccessEntry();
    message.key = object.key ?? "";
    message.value = (object.value !== undefined && object.value !== null)
      ? VaultPermission.fromPartial(object.value)
      : undefined;
    return message;
  },
};

messageTypeRegistry.set(ServerEndpoint_VaultAccessEntry.$type, ServerEndpoint_VaultAccessEntry);

function createBaseVaultPermission(): VaultPermission {
  return { $type: "synch.v1.VaultPermission", vaultId: "", level: 0, vaultKeyEncrypted: new Uint8Array(0) };
}

export const VaultPermission: MessageFns<VaultPermission, "synch.v1.VaultPermission"> = {
  $type: "synch.v1.VaultPermission" as const,

  encode(message: VaultPermission, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.vaultId !== "") {
      writer.uint32(10).string(message.vaultId);
    }
    if (message.level !== 0) {
      writer.uint32(16).int32(message.level);
    }
    if (message.vaultKeyEncrypted.length !== 0) {
      writer.uint32(26).bytes(message.vaultKeyEncrypted);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VaultPermission {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVaultPermission();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.vaultId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.level = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.vaultKeyEncrypted = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VaultPermission {
    return {
      $type: VaultPermission.$type,
      vaultId: isSet(object.vaultId)
        ? globalThis.String(object.vaultId)
        : isSet(object.vault_id)
        ? globalThis.String(object.vault_id)
        : "",
      level: isSet(object.level) ? permissionLevelFromJSON(object.level) : 0,
      vaultKeyEncrypted: isSet(object.vaultKeyEncrypted)
        ? bytesFromBase64(object.vaultKeyEncrypted)
        : isSet(object.vault_key_encrypted)
        ? bytesFromBase64(object.vault_key_encrypted)
        : new Uint8Array(0),
    };
  },

  toJSON(message: VaultPermission): unknown {
    const obj: any = {};
    if (message.vaultId !== "") {
      obj.vaultId = message.vaultId;
    }
    if (message.level !== 0) {
      obj.level = permissionLevelToJSON(message.level);
    }
    if (message.vaultKeyEncrypted.length !== 0) {
      obj.vaultKeyEncrypted = base64FromBytes(message.vaultKeyEncrypted);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VaultPermission>, I>>(base?: I): VaultPermission {
    return VaultPermission.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VaultPermission>, I>>(object: I): VaultPermission {
    const message = createBaseVaultPermission();
    message.vaultId = object.vaultId ?? "";
    message.level = object.level ?? 0;
    message.vaultKeyEncrypted = object.vaultKeyEncrypted ?? new Uint8Array(0);
    return message;
  },
};

messageTypeRegistry.set(VaultPermission.$type, VaultPermission);

function createBaseClientProfile(): ClientProfile {
  return { $type: "synch.v1.ClientProfile", identity: undefined, servers: [], syncConfig: undefined };
}

export const ClientProfile: MessageFns<ClientProfile, "synch.v1.ClientProfile"> = {
  $type: "synch.v1.ClientProfile" as const,

  encode(message: ClientProfile, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.identity !== undefined) {
      NodeIdentity.encode(message.identity, writer.uint32(10).fork()).join();
    }
    for (const v of message.servers) {
      ServerEndpoint.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.syncConfig !== undefined) {
      SyncConfig.encode(message.syncConfig, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ClientProfile {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseClientProfile();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.identity = NodeIdentity.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.servers.push(ServerEndpoint.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.syncConfig = SyncConfig.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ClientProfile {
    return {
      $type: ClientProfile.$type,
      identity: isSet(object.identity) ? NodeIdentity.fromJSON(object.identity) : undefined,
      servers: globalThis.Array.isArray(object?.servers)
        ? object.servers.map((e: any) => ServerEndpoint.fromJSON(e))
        : [],
      syncConfig: isSet(object.syncConfig)
        ? SyncConfig.fromJSON(object.syncConfig)
        : isSet(object.sync_config)
        ? SyncConfig.fromJSON(object.sync_config)
        : undefined,
    };
  },

  toJSON(message: ClientProfile): unknown {
    const obj: any = {};
    if (message.identity !== undefined) {
      obj.identity = NodeIdentity.toJSON(message.identity);
    }
    if (message.servers?.length) {
      obj.servers = message.servers.map((e) => ServerEndpoint.toJSON(e));
    }
    if (message.syncConfig !== undefined) {
      obj.syncConfig = SyncConfig.toJSON(message.syncConfig);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ClientProfile>, I>>(base?: I): ClientProfile {
    return ClientProfile.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ClientProfile>, I>>(object: I): ClientProfile {
    const message = createBaseClientProfile();
    message.identity = (object.identity !== undefined && object.identity !== null)
      ? NodeIdentity.fromPartial(object.identity)
      : undefined;
    message.servers = object.servers?.map((e) => ServerEndpoint.fromPartial(e)) || [];
    message.syncConfig = (object.syncConfig !== undefined && object.syncConfig !== null)
      ? SyncConfig.fromPartial(object.syncConfig)
      : undefined;
    return message;
  },
};

messageTypeRegistry.set(ClientProfile.$type, ClientProfile);

function createBaseSyncConfig(): SyncConfig {
  return { $type: "synch.v1.SyncConfig", conflictStrategy: 0, bandwidthLimitKbps: 0, mobileSyncPolicy: 0 };
}

export const SyncConfig: MessageFns<SyncConfig, "synch.v1.SyncConfig"> = {
  $type: "synch.v1.SyncConfig" as const,

  encode(message: SyncConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.conflictStrategy !== 0) {
      writer.uint32(8).int32(message.conflictStrategy);
    }
    if (message.bandwidthLimitKbps !== 0) {
      writer.uint32(16).uint32(message.bandwidthLimitKbps);
    }
    if (message.mobileSyncPolicy !== 0) {
      writer.uint32(24).int32(message.mobileSyncPolicy);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SyncConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSyncConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.conflictStrategy = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.bandwidthLimitKbps = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.mobileSyncPolicy = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SyncConfig {
    return {
      $type: SyncConfig.$type,
      conflictStrategy: isSet(object.conflictStrategy)
        ? conflictStrategyFromJSON(object.conflictStrategy)
        : isSet(object.conflict_strategy)
        ? conflictStrategyFromJSON(object.conflict_strategy)
        : 0,
      bandwidthLimitKbps: isSet(object.bandwidthLimitKbps)
        ? globalThis.Number(object.bandwidthLimitKbps)
        : isSet(object.bandwidth_limit_kbps)
        ? globalThis.Number(object.bandwidth_limit_kbps)
        : 0,
      mobileSyncPolicy: isSet(object.mobileSyncPolicy)
        ? mobileSyncPolicyFromJSON(object.mobileSyncPolicy)
        : isSet(object.mobile_sync_policy)
        ? mobileSyncPolicyFromJSON(object.mobile_sync_policy)
        : 0,
    };
  },

  toJSON(message: SyncConfig): unknown {
    const obj: any = {};
    if (message.conflictStrategy !== 0) {
      obj.conflictStrategy = conflictStrategyToJSON(message.conflictStrategy);
    }
    if (message.bandwidthLimitKbps !== 0) {
      obj.bandwidthLimitKbps = Math.round(message.bandwidthLimitKbps);
    }
    if (message.mobileSyncPolicy !== 0) {
      obj.mobileSyncPolicy = mobileSyncPolicyToJSON(message.mobileSyncPolicy);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SyncConfig>, I>>(base?: I): SyncConfig {
    return SyncConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SyncConfig>, I>>(object: I): SyncConfig {
    const message = createBaseSyncConfig();
    message.conflictStrategy = object.conflictStrategy ?? 0;
    message.bandwidthLimitKbps = object.bandwidthLimitKbps ?? 0;
    message.mobileSyncPolicy = object.mobileSyncPolicy ?? 0;
    return message;
  },
};

messageTypeRegistry.set(SyncConfig.$type, SyncConfig);

function bytesFromBase64(b64: string): Uint8Array {
  const bin = globalThis.atob(b64);
  const arr = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; ++i) {
    arr[i] = bin.charCodeAt(i);
  }
  return arr;
}

function base64FromBytes(arr: Uint8Array): string {
  const bin: string[] = [];
  arr.forEach((byte) => {
    bin.push(globalThis.String.fromCharCode(byte));
  });
  return globalThis.btoa(bin.join(""));
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in Exclude<keyof T, "$type">]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P> | "$type">]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T, V extends string> {
  readonly $type: V;
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
