// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               unknown
// source: v1/synch.proto

/* eslint-disable @typescript-eslint/ban-ts-comment */
// @ts-nocheck
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf";
import { messageTypeRegistry } from "../typeRegistry";
import { EncryptedPayload } from "./crypto";

export const protobufPackage = "synch.v1";

/**
 * SYNCH 心契协议 �?主协议定�? * 包含：节点身份、多服务端会话、权限模�? */

/** NodeType 标识节点的角色类�?*/
export enum NodeType {
  NODE_TYPE_UNSPECIFIED = 0,
  /** NODE_TYPE_AGENT - AI助手、自动化脚本 */
  NODE_TYPE_AGENT = 1,
  /** NODE_TYPE_HUMAN - 人、管理员 */
  NODE_TYPE_HUMAN = 2,
  /** NODE_TYPE_BRIDGE - 协议转换、外部系统对�?*/
  NODE_TYPE_BRIDGE = 3,
  /** NODE_TYPE_PLUGIN - 宿主环境插件 (vcp-agent, openclaw-agent) */
  NODE_TYPE_PLUGIN = 4,
  /** NODE_TYPE_MOBILE - 移动�?App (Android/iOS) */
  NODE_TYPE_MOBILE = 5,
  /** NODE_TYPE_ADMIN - 网络管理�?(全局) */
  NODE_TYPE_ADMIN = 6,
  /** NODE_TYPE_LORD - 节点领主 (单节点最高权�? */
  NODE_TYPE_LORD = 7,
  /** NODE_TYPE_SUB_ADMIN - 次级管理�?(管事) */
  NODE_TYPE_SUB_ADMIN = 8,
  UNRECOGNIZED = -1,
}

export function nodeTypeFromJSON(object: any): NodeType {
  switch (object) {
    case 0:
    case "NODE_TYPE_UNSPECIFIED":
      return NodeType.NODE_TYPE_UNSPECIFIED;
    case 1:
    case "NODE_TYPE_AGENT":
      return NodeType.NODE_TYPE_AGENT;
    case 2:
    case "NODE_TYPE_HUMAN":
      return NodeType.NODE_TYPE_HUMAN;
    case 3:
    case "NODE_TYPE_BRIDGE":
      return NodeType.NODE_TYPE_BRIDGE;
    case 4:
    case "NODE_TYPE_PLUGIN":
      return NodeType.NODE_TYPE_PLUGIN;
    case 5:
    case "NODE_TYPE_MOBILE":
      return NodeType.NODE_TYPE_MOBILE;
    case 6:
    case "NODE_TYPE_ADMIN":
      return NodeType.NODE_TYPE_ADMIN;
    case 7:
    case "NODE_TYPE_LORD":
      return NodeType.NODE_TYPE_LORD;
    case 8:
    case "NODE_TYPE_SUB_ADMIN":
      return NodeType.NODE_TYPE_SUB_ADMIN;
    case -1:
    case "UNRECOGNIZED":
    default:
      return NodeType.UNRECOGNIZED;
  }
}

export function nodeTypeToJSON(object: NodeType): string {
  switch (object) {
    case NodeType.NODE_TYPE_UNSPECIFIED:
      return "NODE_TYPE_UNSPECIFIED";
    case NodeType.NODE_TYPE_AGENT:
      return "NODE_TYPE_AGENT";
    case NodeType.NODE_TYPE_HUMAN:
      return "NODE_TYPE_HUMAN";
    case NodeType.NODE_TYPE_BRIDGE:
      return "NODE_TYPE_BRIDGE";
    case NodeType.NODE_TYPE_PLUGIN:
      return "NODE_TYPE_PLUGIN";
    case NodeType.NODE_TYPE_MOBILE:
      return "NODE_TYPE_MOBILE";
    case NodeType.NODE_TYPE_ADMIN:
      return "NODE_TYPE_ADMIN";
    case NodeType.NODE_TYPE_LORD:
      return "NODE_TYPE_LORD";
    case NodeType.NODE_TYPE_SUB_ADMIN:
      return "NODE_TYPE_SUB_ADMIN";
    case NodeType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** PerceptionLevel 定义节点的感知层�?(动态隐私设�? */
export enum PerceptionLevel {
  PERCEPTION_LEVEL_UNSPECIFIED = 0,
  /** PERCEPTION_LEVEL_L0 - 完全公开: 广播完整公钥+历史契约摘要 */
  PERCEPTION_LEVEL_L0 = 0,
  /** PERCEPTION_LEVEL_L1 - 社交轮廓: 广播昵称+能力+信誉摘要 */
  PERCEPTION_LEVEL_L1 = 1,
  /** PERCEPTION_LEVEL_L2 - 能力橱窗: 广播能力标签，无身份 (默认) */
  PERCEPTION_LEVEL_L2 = 2,
  /** PERCEPTION_LEVEL_L3 - 影子模式: 广播加密指纹，无元数�?*/
  PERCEPTION_LEVEL_L3 = 3,
  /** PERCEPTION_LEVEL_L4 - 完全隐形: 不广播，仅响应已知契�?*/
  PERCEPTION_LEVEL_L4 = 4,
  UNRECOGNIZED = -1,
}

export function perceptionLevelFromJSON(object: any): PerceptionLevel {
  switch (object) {
    case 0:
    case "PERCEPTION_LEVEL_UNSPECIFIED":
      return PerceptionLevel.PERCEPTION_LEVEL_UNSPECIFIED;
    case 0:
    case "PERCEPTION_LEVEL_L0":
      return PerceptionLevel.PERCEPTION_LEVEL_L0;
    case 1:
    case "PERCEPTION_LEVEL_L1":
      return PerceptionLevel.PERCEPTION_LEVEL_L1;
    case 2:
    case "PERCEPTION_LEVEL_L2":
      return PerceptionLevel.PERCEPTION_LEVEL_L2;
    case 3:
    case "PERCEPTION_LEVEL_L3":
      return PerceptionLevel.PERCEPTION_LEVEL_L3;
    case 4:
    case "PERCEPTION_LEVEL_L4":
      return PerceptionLevel.PERCEPTION_LEVEL_L4;
    case -1:
    case "UNRECOGNIZED":
    default:
      return PerceptionLevel.UNRECOGNIZED;
  }
}

export function perceptionLevelToJSON(object: PerceptionLevel): string {
  switch (object) {
    case PerceptionLevel.PERCEPTION_LEVEL_UNSPECIFIED:
      return "PERCEPTION_LEVEL_UNSPECIFIED";
    case PerceptionLevel.PERCEPTION_LEVEL_L0:
      return "PERCEPTION_LEVEL_L0";
    case PerceptionLevel.PERCEPTION_LEVEL_L1:
      return "PERCEPTION_LEVEL_L1";
    case PerceptionLevel.PERCEPTION_LEVEL_L2:
      return "PERCEPTION_LEVEL_L2";
    case PerceptionLevel.PERCEPTION_LEVEL_L3:
      return "PERCEPTION_LEVEL_L3";
    case PerceptionLevel.PERCEPTION_LEVEL_L4:
      return "PERCEPTION_LEVEL_L4";
    case PerceptionLevel.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** ServerRole 标识客户端与服务端的关系 */
export enum ServerRole {
  SERVER_ROLE_UNSPECIFIED = 0,
  /** SERVER_ROLE_PRIMARY - 主服务端，拥有完整权�?*/
  SERVER_ROLE_PRIMARY = 1,
  /** SERVER_ROLE_SECONDARY - 备用/镜像服务�?*/
  SERVER_ROLE_SECONDARY = 2,
  /** SERVER_ROLE_GUEST - 访客身份，受限权�?*/
  SERVER_ROLE_GUEST = 3,
  UNRECOGNIZED = -1,
}

export function serverRoleFromJSON(object: any): ServerRole {
  switch (object) {
    case 0:
    case "SERVER_ROLE_UNSPECIFIED":
      return ServerRole.SERVER_ROLE_UNSPECIFIED;
    case 1:
    case "SERVER_ROLE_PRIMARY":
      return ServerRole.SERVER_ROLE_PRIMARY;
    case 2:
    case "SERVER_ROLE_SECONDARY":
      return ServerRole.SERVER_ROLE_SECONDARY;
    case 3:
    case "SERVER_ROLE_GUEST":
      return ServerRole.SERVER_ROLE_GUEST;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ServerRole.UNRECOGNIZED;
  }
}

export function serverRoleToJSON(object: ServerRole): string {
  switch (object) {
    case ServerRole.SERVER_ROLE_UNSPECIFIED:
      return "SERVER_ROLE_UNSPECIFIED";
    case ServerRole.SERVER_ROLE_PRIMARY:
      return "SERVER_ROLE_PRIMARY";
    case ServerRole.SERVER_ROLE_SECONDARY:
      return "SERVER_ROLE_SECONDARY";
    case ServerRole.SERVER_ROLE_GUEST:
      return "SERVER_ROLE_GUEST";
    case ServerRole.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** PermissionLevel 标识�?Vault 的操作权�?*/
export enum PermissionLevel {
  PERMISSION_LEVEL_UNSPECIFIED = 0,
  /** PERMISSION_LEVEL_READ - 只读 */
  PERMISSION_LEVEL_READ = 1,
  /** PERMISSION_LEVEL_WRITE - 读写 */
  PERMISSION_LEVEL_WRITE = 2,
  /** PERMISSION_LEVEL_ADMIN - 完全控制 (�?ACL 管理) */
  PERMISSION_LEVEL_ADMIN = 3,
  UNRECOGNIZED = -1,
}

export function permissionLevelFromJSON(object: any): PermissionLevel {
  switch (object) {
    case 0:
    case "PERMISSION_LEVEL_UNSPECIFIED":
      return PermissionLevel.PERMISSION_LEVEL_UNSPECIFIED;
    case 1:
    case "PERMISSION_LEVEL_READ":
      return PermissionLevel.PERMISSION_LEVEL_READ;
    case 2:
    case "PERMISSION_LEVEL_WRITE":
      return PermissionLevel.PERMISSION_LEVEL_WRITE;
    case 3:
    case "PERMISSION_LEVEL_ADMIN":
      return PermissionLevel.PERMISSION_LEVEL_ADMIN;
    case -1:
    case "UNRECOGNIZED":
    default:
      return PermissionLevel.UNRECOGNIZED;
  }
}

export function permissionLevelToJSON(object: PermissionLevel): string {
  switch (object) {
    case PermissionLevel.PERMISSION_LEVEL_UNSPECIFIED:
      return "PERMISSION_LEVEL_UNSPECIFIED";
    case PermissionLevel.PERMISSION_LEVEL_READ:
      return "PERMISSION_LEVEL_READ";
    case PermissionLevel.PERMISSION_LEVEL_WRITE:
      return "PERMISSION_LEVEL_WRITE";
    case PermissionLevel.PERMISSION_LEVEL_ADMIN:
      return "PERMISSION_LEVEL_ADMIN";
    case PermissionLevel.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** ConflictStrategy 冲突解决策略枚举 */
export enum ConflictStrategy {
  CONFLICT_STRATEGY_UNSPECIFIED = 0,
  /** CONFLICT_STRATEGY_AUTO_LOCAL - 本地优先 */
  CONFLICT_STRATEGY_AUTO_LOCAL = 1,
  /** CONFLICT_STRATEGY_AUTO_REMOTE - 远端优先 */
  CONFLICT_STRATEGY_AUTO_REMOTE = 2,
  /** CONFLICT_STRATEGY_ASK - 询问用户 */
  CONFLICT_STRATEGY_ASK = 3,
  UNRECOGNIZED = -1,
}

export function conflictStrategyFromJSON(object: any): ConflictStrategy {
  switch (object) {
    case 0:
    case "CONFLICT_STRATEGY_UNSPECIFIED":
      return ConflictStrategy.CONFLICT_STRATEGY_UNSPECIFIED;
    case 1:
    case "CONFLICT_STRATEGY_AUTO_LOCAL":
      return ConflictStrategy.CONFLICT_STRATEGY_AUTO_LOCAL;
    case 2:
    case "CONFLICT_STRATEGY_AUTO_REMOTE":
      return ConflictStrategy.CONFLICT_STRATEGY_AUTO_REMOTE;
    case 3:
    case "CONFLICT_STRATEGY_ASK":
      return ConflictStrategy.CONFLICT_STRATEGY_ASK;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ConflictStrategy.UNRECOGNIZED;
  }
}

export function conflictStrategyToJSON(object: ConflictStrategy): string {
  switch (object) {
    case ConflictStrategy.CONFLICT_STRATEGY_UNSPECIFIED:
      return "CONFLICT_STRATEGY_UNSPECIFIED";
    case ConflictStrategy.CONFLICT_STRATEGY_AUTO_LOCAL:
      return "CONFLICT_STRATEGY_AUTO_LOCAL";
    case ConflictStrategy.CONFLICT_STRATEGY_AUTO_REMOTE:
      return "CONFLICT_STRATEGY_AUTO_REMOTE";
    case ConflictStrategy.CONFLICT_STRATEGY_ASK:
      return "CONFLICT_STRATEGY_ASK";
    case ConflictStrategy.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** MobileSyncPolicy 移动端同步策�?*/
export enum MobileSyncPolicy {
  MOBILE_SYNC_POLICY_UNSPECIFIED = 0,
  /** MOBILE_SYNC_POLICY_ALWAYS - 始终同步 */
  MOBILE_SYNC_POLICY_ALWAYS = 1,
  /** MOBILE_SYNC_POLICY_WIFI_ONLY - 仅在 Wi-Fi 下同�?*/
  MOBILE_SYNC_POLICY_WIFI_ONLY = 2,
  /** MOBILE_SYNC_POLICY_MANUAL - 手动触发 */
  MOBILE_SYNC_POLICY_MANUAL = 3,
  UNRECOGNIZED = -1,
}

export function mobileSyncPolicyFromJSON(object: any): MobileSyncPolicy {
  switch (object) {
    case 0:
    case "MOBILE_SYNC_POLICY_UNSPECIFIED":
      return MobileSyncPolicy.MOBILE_SYNC_POLICY_UNSPECIFIED;
    case 1:
    case "MOBILE_SYNC_POLICY_ALWAYS":
      return MobileSyncPolicy.MOBILE_SYNC_POLICY_ALWAYS;
    case 2:
    case "MOBILE_SYNC_POLICY_WIFI_ONLY":
      return MobileSyncPolicy.MOBILE_SYNC_POLICY_WIFI_ONLY;
    case 3:
    case "MOBILE_SYNC_POLICY_MANUAL":
      return MobileSyncPolicy.MOBILE_SYNC_POLICY_MANUAL;
    case -1:
    case "UNRECOGNIZED":
    default:
      return MobileSyncPolicy.UNRECOGNIZED;
  }
}

export function mobileSyncPolicyToJSON(object: MobileSyncPolicy): string {
  switch (object) {
    case MobileSyncPolicy.MOBILE_SYNC_POLICY_UNSPECIFIED:
      return "MOBILE_SYNC_POLICY_UNSPECIFIED";
    case MobileSyncPolicy.MOBILE_SYNC_POLICY_ALWAYS:
      return "MOBILE_SYNC_POLICY_ALWAYS";
    case MobileSyncPolicy.MOBILE_SYNC_POLICY_WIFI_ONLY:
      return "MOBILE_SYNC_POLICY_WIFI_ONLY";
    case MobileSyncPolicy.MOBILE_SYNC_POLICY_MANUAL:
      return "MOBILE_SYNC_POLICY_MANUAL";
    case MobileSyncPolicy.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** ContractStatus 契约生命周期状�?*/
export enum ContractStatus {
  CONTRACT_STATUS_UNSPECIFIED = 0,
  /** CONTRACT_STATUS_PENDING - 等待握手确认 */
  CONTRACT_STATUS_PENDING = 1,
  /** CONTRACT_STATUS_ACTIVE - 活跃，正常通讯 */
  CONTRACT_STATUS_ACTIVE = 2,
  /** CONTRACT_STATUS_SUSPENDED - 已挂起，暂时屏蔽消息 */
  CONTRACT_STATUS_SUSPENDED = 3,
  /** CONTRACT_STATUS_EXPIRING - 即将过期，需续期 */
  CONTRACT_STATUS_EXPIRING = 4,
  /** CONTRACT_STATUS_TERMINATED - 已终止，密钥失效 */
  CONTRACT_STATUS_TERMINATED = 5,
  UNRECOGNIZED = -1,
}

export function contractStatusFromJSON(object: any): ContractStatus {
  switch (object) {
    case 0:
    case "CONTRACT_STATUS_UNSPECIFIED":
      return ContractStatus.CONTRACT_STATUS_UNSPECIFIED;
    case 1:
    case "CONTRACT_STATUS_PENDING":
      return ContractStatus.CONTRACT_STATUS_PENDING;
    case 2:
    case "CONTRACT_STATUS_ACTIVE":
      return ContractStatus.CONTRACT_STATUS_ACTIVE;
    case 3:
    case "CONTRACT_STATUS_SUSPENDED":
      return ContractStatus.CONTRACT_STATUS_SUSPENDED;
    case 4:
    case "CONTRACT_STATUS_EXPIRING":
      return ContractStatus.CONTRACT_STATUS_EXPIRING;
    case 5:
    case "CONTRACT_STATUS_TERMINATED":
      return ContractStatus.CONTRACT_STATUS_TERMINATED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ContractStatus.UNRECOGNIZED;
  }
}

export function contractStatusToJSON(object: ContractStatus): string {
  switch (object) {
    case ContractStatus.CONTRACT_STATUS_UNSPECIFIED:
      return "CONTRACT_STATUS_UNSPECIFIED";
    case ContractStatus.CONTRACT_STATUS_PENDING:
      return "CONTRACT_STATUS_PENDING";
    case ContractStatus.CONTRACT_STATUS_ACTIVE:
      return "CONTRACT_STATUS_ACTIVE";
    case ContractStatus.CONTRACT_STATUS_SUSPENDED:
      return "CONTRACT_STATUS_SUSPENDED";
    case ContractStatus.CONTRACT_STATUS_EXPIRING:
      return "CONTRACT_STATUS_EXPIRING";
    case ContractStatus.CONTRACT_STATUS_TERMINATED:
      return "CONTRACT_STATUS_TERMINATED";
    case ContractStatus.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** NodeIdentity 描述网络中的一个节点身�?*/
export interface NodeIdentity {
  $type: "synch.v1.NodeIdentity";
  /** 节点唯一标识, 格式: "agent://{pk}" | "plugin://{pk}" | "mobile://{pk}" ... */
  nodeId: string;
  /** Ed25519 公钥 (32 bytes) */
  publicKey: Uint8Array;
  /** 节点类型 */
  nodeType: NodeType;
  /** 宿主平台: "vcp-agent" | "openclaw" | "android" | "ios" ... */
  platform: string;
  /** 能力声明: "chat", "tools", "rag-local", "vault-sync", "ui-panel" ... */
  capabilities: string[];
  /** 注册时间 (Unix epoch millis) */
  registeredAt: number;
  /** 人类可读的显示名�?*/
  displayName: string;
  /** 父节�?ID (用于 Plugin -> Agent �?1:N 关系) */
  parentNodeId: string;
  /** 扩展元数�?(如环境标签、版本等) */
  metadata: { [key: string]: string };
}

export interface NodeIdentity_MetadataEntry {
  $type: "synch.v1.NodeIdentity.MetadataEntry";
  key: string;
  value: string;
}

/** ServerEndpoint 描述一个客户端连接的服务端 */
export interface ServerEndpoint {
  $type: "synch.v1.ServerEndpoint";
  /** 服务端唯一 ID (�?"home-fnos", "friend-bob") */
  serverId: string;
  /** WebSocket/gRPC 连接地址 (�?"wss://home.synch.local:8081") */
  url: string;
  /** 此客户端在该服务端上的角�?*/
  role: ServerRole;
  /** 该服务端上各 Vault 的权限映�? vault_id -> VaultPermission */
  vaultAccess: { [key: string]: VaultPermission };
  /** 人类可读的服务端名称 (�?"家里心契") */
  displayName: string;
  /** 是否自动连接 */
  autoConnect: boolean;
  /** 邀请码 (用于 GUEST 角色加入) */
  inviteCode: string;
}

export interface ServerEndpoint_VaultAccessEntry {
  $type: "synch.v1.ServerEndpoint.VaultAccessEntry";
  key: string;
  value: VaultPermission | undefined;
}

/** VaultPermission 描述对单�?Vault 的权�?*/
export interface VaultPermission {
  $type: "synch.v1.VaultPermission";
  /** Vault 唯一 ID: Blake3(vault_root_path + owner_pubkey)[0:16] */
  vaultId: string;
  /** 权限级别 */
  level: PermissionLevel;
  /** 用设备密钥加密的 Vault 密钥 (AES-256-GCM wrapped) */
  vaultKeyEncrypted: Uint8Array;
}

/** ClientProfile 描述客户端的身份与多服务端配�?*/
export interface ClientProfile {
  $type: "synch.v1.ClientProfile";
  /** 此客户端的身�?*/
  identity:
    | NodeIdentity
    | undefined;
  /** 连接的所有服务端 */
  servers: ServerEndpoint[];
  /** 同步配置 */
  syncConfig: SyncConfig | undefined;
}

/** SyncConfig 全局同步偏好设置 */
export interface SyncConfig {
  $type: "synch.v1.SyncConfig";
  /** 冲突处理策略 */
  conflictStrategy: ConflictStrategy;
  /** 带宽限制 (KB/s), 0 = 无限�?*/
  bandwidthLimitKbps: number;
  /** 移动网络同步策略 */
  mobileSyncPolicy: MobileSyncPolicy;
}

/** Contract 节点间的交互契约 */
export interface Contract {
  $type: "synch.v1.Contract";
  /** 契约唯一 ID: Blake3(req_pk + target_pk + timestamp)[0:16] */
  contractId: string;
  /** 发起方公�?(Ed25519) */
  requesterId: Uint8Array;
  /** 目标方公�?(Ed25519) */
  targetId: Uint8Array;
  /** 授权的能力列�?*/
  capabilities: string[];
  /** 契约创建时间 */
  createdAt: number;
  /** 契约过期时间 (0 = 永不过期) */
  expiresAt: number;
  /** 续期策略: "auto", "prompt", "expire" */
  renewalPolicy: string;
  /** 契约当前状�?*/
  status: ContractStatus;
  /** 发起方签�?(证明意愿) */
  requesterSignature: Uint8Array;
  /** 目标方签�?(完成握手) */
  targetSignature: Uint8Array;
  /** 发起方配置的首选中继节�?URLs (�?["wss://relay-a.local", "wss://public.synch"]) */
  requesterRelays: string[];
  /** 目标方配置的首选中继节�?URLs */
  targetRelays: string[];
}

/** SecuredMessage 经过 E2EE 转换的消息封�?*/
export interface SecuredMessage {
  $type: "synch.v1.SecuredMessage";
  /** 关联的契�?ID */
  contractId: string;
  /** 发送者指�?(L2+ 感知层下解耦身�? */
  senderFingerprint: string;
  /** 消息层级加密载荷 (AES-256-GCM) */
  payload:
    | EncryptedPayload
    | undefined;
  /** 消息发送时�?*/
  timestamp: number;
  /** 签名 (由发送方 identity 签名 header || payload) */
  signature: Uint8Array;
}

function createBaseNodeIdentity(): NodeIdentity {
  return {
    $type: "synch.v1.NodeIdentity",
    nodeId: "",
    publicKey: new Uint8Array(0),
    nodeType: 0,
    platform: "",
    capabilities: [],
    registeredAt: 0,
    displayName: "",
    parentNodeId: "",
    metadata: {},
  };
}

export const NodeIdentity: MessageFns<NodeIdentity, "synch.v1.NodeIdentity"> = {
  $type: "synch.v1.NodeIdentity" as const,

  encode(message: NodeIdentity, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.nodeId !== "") {
      writer.uint32(10).string(message.nodeId);
    }
    if (message.publicKey.length !== 0) {
      writer.uint32(18).bytes(message.publicKey);
    }
    if (message.nodeType !== 0) {
      writer.uint32(24).int32(message.nodeType);
    }
    if (message.platform !== "") {
      writer.uint32(34).string(message.platform);
    }
    for (const v of message.capabilities) {
      writer.uint32(42).string(v!);
    }
    if (message.registeredAt !== 0) {
      writer.uint32(48).uint64(message.registeredAt);
    }
    if (message.displayName !== "") {
      writer.uint32(58).string(message.displayName);
    }
    if (message.parentNodeId !== "") {
      writer.uint32(66).string(message.parentNodeId);
    }
    globalThis.Object.entries(message.metadata).forEach(([key, value]: [string, string]) => {
      NodeIdentity_MetadataEntry.encode(
        { $type: "synch.v1.NodeIdentity.MetadataEntry", key: key as any, value },
        writer.uint32(74).fork(),
      ).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NodeIdentity {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNodeIdentity();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.nodeId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.publicKey = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.nodeType = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.platform = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.capabilities.push(reader.string());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.registeredAt = longToNumber(reader.uint64());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.displayName = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.parentNodeId = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          const entry9 = NodeIdentity_MetadataEntry.decode(reader, reader.uint32());
          if (entry9.value !== undefined) {
            message.metadata[entry9.key] = entry9.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NodeIdentity {
    return {
      $type: NodeIdentity.$type,
      nodeId: isSet(object.nodeId)
        ? globalThis.String(object.nodeId)
        : isSet(object.node_id)
        ? globalThis.String(object.node_id)
        : "",
      publicKey: isSet(object.publicKey)
        ? bytesFromBase64(object.publicKey)
        : isSet(object.public_key)
        ? bytesFromBase64(object.public_key)
        : new Uint8Array(0),
      nodeType: isSet(object.nodeType)
        ? nodeTypeFromJSON(object.nodeType)
        : isSet(object.node_type)
        ? nodeTypeFromJSON(object.node_type)
        : 0,
      platform: isSet(object.platform) ? globalThis.String(object.platform) : "",
      capabilities: globalThis.Array.isArray(object?.capabilities)
        ? object.capabilities.map((e: any) => globalThis.String(e))
        : [],
      registeredAt: isSet(object.registeredAt)
        ? globalThis.Number(object.registeredAt)
        : isSet(object.registered_at)
        ? globalThis.Number(object.registered_at)
        : 0,
      displayName: isSet(object.displayName)
        ? globalThis.String(object.displayName)
        : isSet(object.display_name)
        ? globalThis.String(object.display_name)
        : "",
      parentNodeId: isSet(object.parentNodeId)
        ? globalThis.String(object.parentNodeId)
        : isSet(object.parent_node_id)
        ? globalThis.String(object.parent_node_id)
        : "",
      metadata: isObject(object.metadata)
        ? (globalThis.Object.entries(object.metadata) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: NodeIdentity): unknown {
    const obj: any = {};
    if (message.nodeId !== "") {
      obj.nodeId = message.nodeId;
    }
    if (message.publicKey.length !== 0) {
      obj.publicKey = base64FromBytes(message.publicKey);
    }
    if (message.nodeType !== 0) {
      obj.nodeType = nodeTypeToJSON(message.nodeType);
    }
    if (message.platform !== "") {
      obj.platform = message.platform;
    }
    if (message.capabilities?.length) {
      obj.capabilities = message.capabilities;
    }
    if (message.registeredAt !== 0) {
      obj.registeredAt = Math.round(message.registeredAt);
    }
    if (message.displayName !== "") {
      obj.displayName = message.displayName;
    }
    if (message.parentNodeId !== "") {
      obj.parentNodeId = message.parentNodeId;
    }
    if (message.metadata) {
      const entries = globalThis.Object.entries(message.metadata) as [string, string][];
      if (entries.length > 0) {
        obj.metadata = {};
        entries.forEach(([k, v]) => {
          obj.metadata[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NodeIdentity>, I>>(base?: I): NodeIdentity {
    return NodeIdentity.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NodeIdentity>, I>>(object: I): NodeIdentity {
    const message = createBaseNodeIdentity();
    message.nodeId = object.nodeId ?? "";
    message.publicKey = object.publicKey ?? new Uint8Array(0);
    message.nodeType = object.nodeType ?? 0;
    message.platform = object.platform ?? "";
    message.capabilities = object.capabilities?.map((e) => e) || [];
    message.registeredAt = object.registeredAt ?? 0;
    message.displayName = object.displayName ?? "";
    message.parentNodeId = object.parentNodeId ?? "";
    message.metadata = (globalThis.Object.entries(object.metadata ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

messageTypeRegistry.set(NodeIdentity.$type, NodeIdentity);

function createBaseNodeIdentity_MetadataEntry(): NodeIdentity_MetadataEntry {
  return { $type: "synch.v1.NodeIdentity.MetadataEntry", key: "", value: "" };
}

export const NodeIdentity_MetadataEntry: MessageFns<NodeIdentity_MetadataEntry, "synch.v1.NodeIdentity.MetadataEntry"> =
  {
    $type: "synch.v1.NodeIdentity.MetadataEntry" as const,

    encode(message: NodeIdentity_MetadataEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
      if (message.key !== "") {
        writer.uint32(10).string(message.key);
      }
      if (message.value !== "") {
        writer.uint32(18).string(message.value);
      }
      return writer;
    },

    decode(input: BinaryReader | Uint8Array, length?: number): NodeIdentity_MetadataEntry {
      const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseNodeIdentity_MetadataEntry();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.key = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.value = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    },

    fromJSON(object: any): NodeIdentity_MetadataEntry {
      return {
        $type: NodeIdentity_MetadataEntry.$type,
        key: isSet(object.key) ? globalThis.String(object.key) : "",
        value: isSet(object.value) ? globalThis.String(object.value) : "",
      };
    },

    toJSON(message: NodeIdentity_MetadataEntry): unknown {
      const obj: any = {};
      if (message.key !== "") {
        obj.key = message.key;
      }
      if (message.value !== "") {
        obj.value = message.value;
      }
      return obj;
    },

    create<I extends Exact<DeepPartial<NodeIdentity_MetadataEntry>, I>>(base?: I): NodeIdentity_MetadataEntry {
      return NodeIdentity_MetadataEntry.fromPartial(base ?? ({} as any));
    },
    fromPartial<I extends Exact<DeepPartial<NodeIdentity_MetadataEntry>, I>>(object: I): NodeIdentity_MetadataEntry {
      const message = createBaseNodeIdentity_MetadataEntry();
      message.key = object.key ?? "";
      message.value = object.value ?? "";
      return message;
    },
  };

messageTypeRegistry.set(NodeIdentity_MetadataEntry.$type, NodeIdentity_MetadataEntry);

function createBaseServerEndpoint(): ServerEndpoint {
  return {
    $type: "synch.v1.ServerEndpoint",
    serverId: "",
    url: "",
    role: 0,
    vaultAccess: {},
    displayName: "",
    autoConnect: false,
    inviteCode: "",
  };
}

export const ServerEndpoint: MessageFns<ServerEndpoint, "synch.v1.ServerEndpoint"> = {
  $type: "synch.v1.ServerEndpoint" as const,

  encode(message: ServerEndpoint, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.serverId !== "") {
      writer.uint32(10).string(message.serverId);
    }
    if (message.url !== "") {
      writer.uint32(18).string(message.url);
    }
    if (message.role !== 0) {
      writer.uint32(24).int32(message.role);
    }
    globalThis.Object.entries(message.vaultAccess).forEach(([key, value]: [string, VaultPermission]) => {
      ServerEndpoint_VaultAccessEntry.encode({
        $type: "synch.v1.ServerEndpoint.VaultAccessEntry",
        key: key as any,
        value,
      }, writer.uint32(34).fork()).join();
    });
    if (message.displayName !== "") {
      writer.uint32(42).string(message.displayName);
    }
    if (message.autoConnect !== false) {
      writer.uint32(48).bool(message.autoConnect);
    }
    if (message.inviteCode !== "") {
      writer.uint32(58).string(message.inviteCode);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ServerEndpoint {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServerEndpoint();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serverId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.url = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.role = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          const entry4 = ServerEndpoint_VaultAccessEntry.decode(reader, reader.uint32());
          if (entry4.value !== undefined) {
            message.vaultAccess[entry4.key] = entry4.value;
          }
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.displayName = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.autoConnect = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.inviteCode = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServerEndpoint {
    return {
      $type: ServerEndpoint.$type,
      serverId: isSet(object.serverId)
        ? globalThis.String(object.serverId)
        : isSet(object.server_id)
        ? globalThis.String(object.server_id)
        : "",
      url: isSet(object.url) ? globalThis.String(object.url) : "",
      role: isSet(object.role) ? serverRoleFromJSON(object.role) : 0,
      vaultAccess: isObject(object.vaultAccess)
        ? (globalThis.Object.entries(object.vaultAccess) as [string, any][]).reduce(
          (acc: { [key: string]: VaultPermission }, [key, value]: [string, any]) => {
            acc[key] = VaultPermission.fromJSON(value);
            return acc;
          },
          {},
        )
        : isObject(object.vault_access)
        ? (globalThis.Object.entries(object.vault_access) as [string, any][]).reduce(
          (acc: { [key: string]: VaultPermission }, [key, value]: [string, any]) => {
            acc[key] = VaultPermission.fromJSON(value);
            return acc;
          },
          {},
        )
        : {},
      displayName: isSet(object.displayName)
        ? globalThis.String(object.displayName)
        : isSet(object.display_name)
        ? globalThis.String(object.display_name)
        : "",
      autoConnect: isSet(object.autoConnect)
        ? globalThis.Boolean(object.autoConnect)
        : isSet(object.auto_connect)
        ? globalThis.Boolean(object.auto_connect)
        : false,
      inviteCode: isSet(object.inviteCode)
        ? globalThis.String(object.inviteCode)
        : isSet(object.invite_code)
        ? globalThis.String(object.invite_code)
        : "",
    };
  },

  toJSON(message: ServerEndpoint): unknown {
    const obj: any = {};
    if (message.serverId !== "") {
      obj.serverId = message.serverId;
    }
    if (message.url !== "") {
      obj.url = message.url;
    }
    if (message.role !== 0) {
      obj.role = serverRoleToJSON(message.role);
    }
    if (message.vaultAccess) {
      const entries = globalThis.Object.entries(message.vaultAccess) as [string, VaultPermission][];
      if (entries.length > 0) {
        obj.vaultAccess = {};
        entries.forEach(([k, v]) => {
          obj.vaultAccess[k] = VaultPermission.toJSON(v);
        });
      }
    }
    if (message.displayName !== "") {
      obj.displayName = message.displayName;
    }
    if (message.autoConnect !== false) {
      obj.autoConnect = message.autoConnect;
    }
    if (message.inviteCode !== "") {
      obj.inviteCode = message.inviteCode;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServerEndpoint>, I>>(base?: I): ServerEndpoint {
    return ServerEndpoint.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServerEndpoint>, I>>(object: I): ServerEndpoint {
    const message = createBaseServerEndpoint();
    message.serverId = object.serverId ?? "";
    message.url = object.url ?? "";
    message.role = object.role ?? 0;
    message.vaultAccess = (globalThis.Object.entries(object.vaultAccess ?? {}) as any).reduce(
      (acc: { [key: string]: VaultPermission }, [key, value]: [string, any]) => {
        if (value !== undefined) {
          acc[key] = VaultPermission.fromPartial(value);
        }
        return acc;
      },
      {},
    );
    message.displayName = object.displayName ?? "";
    message.autoConnect = object.autoConnect ?? false;
    message.inviteCode = object.inviteCode ?? "";
    return message;
  },
};

messageTypeRegistry.set(ServerEndpoint.$type, ServerEndpoint);

function createBaseServerEndpoint_VaultAccessEntry(): ServerEndpoint_VaultAccessEntry {
  return { $type: "synch.v1.ServerEndpoint.VaultAccessEntry", key: "", value: undefined };
}

export const ServerEndpoint_VaultAccessEntry: MessageFns<
  ServerEndpoint_VaultAccessEntry,
  "synch.v1.ServerEndpoint.VaultAccessEntry"
> = {
  $type: "synch.v1.ServerEndpoint.VaultAccessEntry" as const,

  encode(message: ServerEndpoint_VaultAccessEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== undefined) {
      VaultPermission.encode(message.value, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ServerEndpoint_VaultAccessEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseServerEndpoint_VaultAccessEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = VaultPermission.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ServerEndpoint_VaultAccessEntry {
    return {
      $type: ServerEndpoint_VaultAccessEntry.$type,
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? VaultPermission.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: ServerEndpoint_VaultAccessEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = VaultPermission.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ServerEndpoint_VaultAccessEntry>, I>>(base?: I): ServerEndpoint_VaultAccessEntry {
    return ServerEndpoint_VaultAccessEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ServerEndpoint_VaultAccessEntry>, I>>(
    object: I,
  ): ServerEndpoint_VaultAccessEntry {
    const message = createBaseServerEndpoint_VaultAccessEntry();
    message.key = object.key ?? "";
    message.value = (object.value !== undefined && object.value !== null)
      ? VaultPermission.fromPartial(object.value)
      : undefined;
    return message;
  },
};

messageTypeRegistry.set(ServerEndpoint_VaultAccessEntry.$type, ServerEndpoint_VaultAccessEntry);

function createBaseVaultPermission(): VaultPermission {
  return { $type: "synch.v1.VaultPermission", vaultId: "", level: 0, vaultKeyEncrypted: new Uint8Array(0) };
}

export const VaultPermission: MessageFns<VaultPermission, "synch.v1.VaultPermission"> = {
  $type: "synch.v1.VaultPermission" as const,

  encode(message: VaultPermission, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.vaultId !== "") {
      writer.uint32(10).string(message.vaultId);
    }
    if (message.level !== 0) {
      writer.uint32(16).int32(message.level);
    }
    if (message.vaultKeyEncrypted.length !== 0) {
      writer.uint32(26).bytes(message.vaultKeyEncrypted);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VaultPermission {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVaultPermission();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.vaultId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.level = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.vaultKeyEncrypted = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VaultPermission {
    return {
      $type: VaultPermission.$type,
      vaultId: isSet(object.vaultId)
        ? globalThis.String(object.vaultId)
        : isSet(object.vault_id)
        ? globalThis.String(object.vault_id)
        : "",
      level: isSet(object.level) ? permissionLevelFromJSON(object.level) : 0,
      vaultKeyEncrypted: isSet(object.vaultKeyEncrypted)
        ? bytesFromBase64(object.vaultKeyEncrypted)
        : isSet(object.vault_key_encrypted)
        ? bytesFromBase64(object.vault_key_encrypted)
        : new Uint8Array(0),
    };
  },

  toJSON(message: VaultPermission): unknown {
    const obj: any = {};
    if (message.vaultId !== "") {
      obj.vaultId = message.vaultId;
    }
    if (message.level !== 0) {
      obj.level = permissionLevelToJSON(message.level);
    }
    if (message.vaultKeyEncrypted.length !== 0) {
      obj.vaultKeyEncrypted = base64FromBytes(message.vaultKeyEncrypted);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VaultPermission>, I>>(base?: I): VaultPermission {
    return VaultPermission.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VaultPermission>, I>>(object: I): VaultPermission {
    const message = createBaseVaultPermission();
    message.vaultId = object.vaultId ?? "";
    message.level = object.level ?? 0;
    message.vaultKeyEncrypted = object.vaultKeyEncrypted ?? new Uint8Array(0);
    return message;
  },
};

messageTypeRegistry.set(VaultPermission.$type, VaultPermission);

function createBaseClientProfile(): ClientProfile {
  return { $type: "synch.v1.ClientProfile", identity: undefined, servers: [], syncConfig: undefined };
}

export const ClientProfile: MessageFns<ClientProfile, "synch.v1.ClientProfile"> = {
  $type: "synch.v1.ClientProfile" as const,

  encode(message: ClientProfile, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.identity !== undefined) {
      NodeIdentity.encode(message.identity, writer.uint32(10).fork()).join();
    }
    for (const v of message.servers) {
      ServerEndpoint.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.syncConfig !== undefined) {
      SyncConfig.encode(message.syncConfig, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ClientProfile {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseClientProfile();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.identity = NodeIdentity.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.servers.push(ServerEndpoint.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.syncConfig = SyncConfig.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ClientProfile {
    return {
      $type: ClientProfile.$type,
      identity: isSet(object.identity) ? NodeIdentity.fromJSON(object.identity) : undefined,
      servers: globalThis.Array.isArray(object?.servers)
        ? object.servers.map((e: any) => ServerEndpoint.fromJSON(e))
        : [],
      syncConfig: isSet(object.syncConfig)
        ? SyncConfig.fromJSON(object.syncConfig)
        : isSet(object.sync_config)
        ? SyncConfig.fromJSON(object.sync_config)
        : undefined,
    };
  },

  toJSON(message: ClientProfile): unknown {
    const obj: any = {};
    if (message.identity !== undefined) {
      obj.identity = NodeIdentity.toJSON(message.identity);
    }
    if (message.servers?.length) {
      obj.servers = message.servers.map((e) => ServerEndpoint.toJSON(e));
    }
    if (message.syncConfig !== undefined) {
      obj.syncConfig = SyncConfig.toJSON(message.syncConfig);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ClientProfile>, I>>(base?: I): ClientProfile {
    return ClientProfile.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ClientProfile>, I>>(object: I): ClientProfile {
    const message = createBaseClientProfile();
    message.identity = (object.identity !== undefined && object.identity !== null)
      ? NodeIdentity.fromPartial(object.identity)
      : undefined;
    message.servers = object.servers?.map((e) => ServerEndpoint.fromPartial(e)) || [];
    message.syncConfig = (object.syncConfig !== undefined && object.syncConfig !== null)
      ? SyncConfig.fromPartial(object.syncConfig)
      : undefined;
    return message;
  },
};

messageTypeRegistry.set(ClientProfile.$type, ClientProfile);

function createBaseSyncConfig(): SyncConfig {
  return { $type: "synch.v1.SyncConfig", conflictStrategy: 0, bandwidthLimitKbps: 0, mobileSyncPolicy: 0 };
}

export const SyncConfig: MessageFns<SyncConfig, "synch.v1.SyncConfig"> = {
  $type: "synch.v1.SyncConfig" as const,

  encode(message: SyncConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.conflictStrategy !== 0) {
      writer.uint32(8).int32(message.conflictStrategy);
    }
    if (message.bandwidthLimitKbps !== 0) {
      writer.uint32(16).uint32(message.bandwidthLimitKbps);
    }
    if (message.mobileSyncPolicy !== 0) {
      writer.uint32(24).int32(message.mobileSyncPolicy);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SyncConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSyncConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.conflictStrategy = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.bandwidthLimitKbps = reader.uint32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.mobileSyncPolicy = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SyncConfig {
    return {
      $type: SyncConfig.$type,
      conflictStrategy: isSet(object.conflictStrategy)
        ? conflictStrategyFromJSON(object.conflictStrategy)
        : isSet(object.conflict_strategy)
        ? conflictStrategyFromJSON(object.conflict_strategy)
        : 0,
      bandwidthLimitKbps: isSet(object.bandwidthLimitKbps)
        ? globalThis.Number(object.bandwidthLimitKbps)
        : isSet(object.bandwidth_limit_kbps)
        ? globalThis.Number(object.bandwidth_limit_kbps)
        : 0,
      mobileSyncPolicy: isSet(object.mobileSyncPolicy)
        ? mobileSyncPolicyFromJSON(object.mobileSyncPolicy)
        : isSet(object.mobile_sync_policy)
        ? mobileSyncPolicyFromJSON(object.mobile_sync_policy)
        : 0,
    };
  },

  toJSON(message: SyncConfig): unknown {
    const obj: any = {};
    if (message.conflictStrategy !== 0) {
      obj.conflictStrategy = conflictStrategyToJSON(message.conflictStrategy);
    }
    if (message.bandwidthLimitKbps !== 0) {
      obj.bandwidthLimitKbps = Math.round(message.bandwidthLimitKbps);
    }
    if (message.mobileSyncPolicy !== 0) {
      obj.mobileSyncPolicy = mobileSyncPolicyToJSON(message.mobileSyncPolicy);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SyncConfig>, I>>(base?: I): SyncConfig {
    return SyncConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SyncConfig>, I>>(object: I): SyncConfig {
    const message = createBaseSyncConfig();
    message.conflictStrategy = object.conflictStrategy ?? 0;
    message.bandwidthLimitKbps = object.bandwidthLimitKbps ?? 0;
    message.mobileSyncPolicy = object.mobileSyncPolicy ?? 0;
    return message;
  },
};

messageTypeRegistry.set(SyncConfig.$type, SyncConfig);

function createBaseContract(): Contract {
  return {
    $type: "synch.v1.Contract",
    contractId: "",
    requesterId: new Uint8Array(0),
    targetId: new Uint8Array(0),
    capabilities: [],
    createdAt: 0,
    expiresAt: 0,
    renewalPolicy: "",
    status: 0,
    requesterSignature: new Uint8Array(0),
    targetSignature: new Uint8Array(0),
    requesterRelays: [],
    targetRelays: [],
  };
}

export const Contract: MessageFns<Contract, "synch.v1.Contract"> = {
  $type: "synch.v1.Contract" as const,

  encode(message: Contract, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.contractId !== "") {
      writer.uint32(10).string(message.contractId);
    }
    if (message.requesterId.length !== 0) {
      writer.uint32(18).bytes(message.requesterId);
    }
    if (message.targetId.length !== 0) {
      writer.uint32(26).bytes(message.targetId);
    }
    for (const v of message.capabilities) {
      writer.uint32(34).string(v!);
    }
    if (message.createdAt !== 0) {
      writer.uint32(40).uint64(message.createdAt);
    }
    if (message.expiresAt !== 0) {
      writer.uint32(48).uint64(message.expiresAt);
    }
    if (message.renewalPolicy !== "") {
      writer.uint32(58).string(message.renewalPolicy);
    }
    if (message.status !== 0) {
      writer.uint32(64).int32(message.status);
    }
    if (message.requesterSignature.length !== 0) {
      writer.uint32(74).bytes(message.requesterSignature);
    }
    if (message.targetSignature.length !== 0) {
      writer.uint32(82).bytes(message.targetSignature);
    }
    for (const v of message.requesterRelays) {
      writer.uint32(90).string(v!);
    }
    for (const v of message.targetRelays) {
      writer.uint32(98).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Contract {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseContract();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.contractId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.requesterId = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.targetId = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.capabilities.push(reader.string());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.createdAt = longToNumber(reader.uint64());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.expiresAt = longToNumber(reader.uint64());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.renewalPolicy = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.status = reader.int32() as any;
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.requesterSignature = reader.bytes();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.targetSignature = reader.bytes();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.requesterRelays.push(reader.string());
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.targetRelays.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Contract {
    return {
      $type: Contract.$type,
      contractId: isSet(object.contractId)
        ? globalThis.String(object.contractId)
        : isSet(object.contract_id)
        ? globalThis.String(object.contract_id)
        : "",
      requesterId: isSet(object.requesterId)
        ? bytesFromBase64(object.requesterId)
        : isSet(object.requester_id)
        ? bytesFromBase64(object.requester_id)
        : new Uint8Array(0),
      targetId: isSet(object.targetId)
        ? bytesFromBase64(object.targetId)
        : isSet(object.target_id)
        ? bytesFromBase64(object.target_id)
        : new Uint8Array(0),
      capabilities: globalThis.Array.isArray(object?.capabilities)
        ? object.capabilities.map((e: any) => globalThis.String(e))
        : [],
      createdAt: isSet(object.createdAt)
        ? globalThis.Number(object.createdAt)
        : isSet(object.created_at)
        ? globalThis.Number(object.created_at)
        : 0,
      expiresAt: isSet(object.expiresAt)
        ? globalThis.Number(object.expiresAt)
        : isSet(object.expires_at)
        ? globalThis.Number(object.expires_at)
        : 0,
      renewalPolicy: isSet(object.renewalPolicy)
        ? globalThis.String(object.renewalPolicy)
        : isSet(object.renewal_policy)
        ? globalThis.String(object.renewal_policy)
        : "",
      status: isSet(object.status) ? contractStatusFromJSON(object.status) : 0,
      requesterSignature: isSet(object.requesterSignature)
        ? bytesFromBase64(object.requesterSignature)
        : isSet(object.requester_signature)
        ? bytesFromBase64(object.requester_signature)
        : new Uint8Array(0),
      targetSignature: isSet(object.targetSignature)
        ? bytesFromBase64(object.targetSignature)
        : isSet(object.target_signature)
        ? bytesFromBase64(object.target_signature)
        : new Uint8Array(0),
      requesterRelays: globalThis.Array.isArray(object?.requesterRelays)
        ? object.requesterRelays.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.requester_relays)
        ? object.requester_relays.map((e: any) => globalThis.String(e))
        : [],
      targetRelays: globalThis.Array.isArray(object?.targetRelays)
        ? object.targetRelays.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.target_relays)
        ? object.target_relays.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: Contract): unknown {
    const obj: any = {};
    if (message.contractId !== "") {
      obj.contractId = message.contractId;
    }
    if (message.requesterId.length !== 0) {
      obj.requesterId = base64FromBytes(message.requesterId);
    }
    if (message.targetId.length !== 0) {
      obj.targetId = base64FromBytes(message.targetId);
    }
    if (message.capabilities?.length) {
      obj.capabilities = message.capabilities;
    }
    if (message.createdAt !== 0) {
      obj.createdAt = Math.round(message.createdAt);
    }
    if (message.expiresAt !== 0) {
      obj.expiresAt = Math.round(message.expiresAt);
    }
    if (message.renewalPolicy !== "") {
      obj.renewalPolicy = message.renewalPolicy;
    }
    if (message.status !== 0) {
      obj.status = contractStatusToJSON(message.status);
    }
    if (message.requesterSignature.length !== 0) {
      obj.requesterSignature = base64FromBytes(message.requesterSignature);
    }
    if (message.targetSignature.length !== 0) {
      obj.targetSignature = base64FromBytes(message.targetSignature);
    }
    if (message.requesterRelays?.length) {
      obj.requesterRelays = message.requesterRelays;
    }
    if (message.targetRelays?.length) {
      obj.targetRelays = message.targetRelays;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Contract>, I>>(base?: I): Contract {
    return Contract.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Contract>, I>>(object: I): Contract {
    const message = createBaseContract();
    message.contractId = object.contractId ?? "";
    message.requesterId = object.requesterId ?? new Uint8Array(0);
    message.targetId = object.targetId ?? new Uint8Array(0);
    message.capabilities = object.capabilities?.map((e) => e) || [];
    message.createdAt = object.createdAt ?? 0;
    message.expiresAt = object.expiresAt ?? 0;
    message.renewalPolicy = object.renewalPolicy ?? "";
    message.status = object.status ?? 0;
    message.requesterSignature = object.requesterSignature ?? new Uint8Array(0);
    message.targetSignature = object.targetSignature ?? new Uint8Array(0);
    message.requesterRelays = object.requesterRelays?.map((e) => e) || [];
    message.targetRelays = object.targetRelays?.map((e) => e) || [];
    return message;
  },
};

messageTypeRegistry.set(Contract.$type, Contract);

function createBaseSecuredMessage(): SecuredMessage {
  return {
    $type: "synch.v1.SecuredMessage",
    contractId: "",
    senderFingerprint: "",
    payload: undefined,
    timestamp: 0,
    signature: new Uint8Array(0),
  };
}

export const SecuredMessage: MessageFns<SecuredMessage, "synch.v1.SecuredMessage"> = {
  $type: "synch.v1.SecuredMessage" as const,

  encode(message: SecuredMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.contractId !== "") {
      writer.uint32(10).string(message.contractId);
    }
    if (message.senderFingerprint !== "") {
      writer.uint32(18).string(message.senderFingerprint);
    }
    if (message.payload !== undefined) {
      EncryptedPayload.encode(message.payload, writer.uint32(26).fork()).join();
    }
    if (message.timestamp !== 0) {
      writer.uint32(32).uint64(message.timestamp);
    }
    if (message.signature.length !== 0) {
      writer.uint32(42).bytes(message.signature);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SecuredMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSecuredMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.contractId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.senderFingerprint = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.payload = EncryptedPayload.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.timestamp = longToNumber(reader.uint64());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.signature = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SecuredMessage {
    return {
      $type: SecuredMessage.$type,
      contractId: isSet(object.contractId)
        ? globalThis.String(object.contractId)
        : isSet(object.contract_id)
        ? globalThis.String(object.contract_id)
        : "",
      senderFingerprint: isSet(object.senderFingerprint)
        ? globalThis.String(object.senderFingerprint)
        : isSet(object.sender_fingerprint)
        ? globalThis.String(object.sender_fingerprint)
        : "",
      payload: isSet(object.payload) ? EncryptedPayload.fromJSON(object.payload) : undefined,
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
      signature: isSet(object.signature) ? bytesFromBase64(object.signature) : new Uint8Array(0),
    };
  },

  toJSON(message: SecuredMessage): unknown {
    const obj: any = {};
    if (message.contractId !== "") {
      obj.contractId = message.contractId;
    }
    if (message.senderFingerprint !== "") {
      obj.senderFingerprint = message.senderFingerprint;
    }
    if (message.payload !== undefined) {
      obj.payload = EncryptedPayload.toJSON(message.payload);
    }
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    if (message.signature.length !== 0) {
      obj.signature = base64FromBytes(message.signature);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SecuredMessage>, I>>(base?: I): SecuredMessage {
    return SecuredMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SecuredMessage>, I>>(object: I): SecuredMessage {
    const message = createBaseSecuredMessage();
    message.contractId = object.contractId ?? "";
    message.senderFingerprint = object.senderFingerprint ?? "";
    message.payload = (object.payload !== undefined && object.payload !== null)
      ? EncryptedPayload.fromPartial(object.payload)
      : undefined;
    message.timestamp = object.timestamp ?? 0;
    message.signature = object.signature ?? new Uint8Array(0);
    return message;
  },
};

messageTypeRegistry.set(SecuredMessage.$type, SecuredMessage);

function bytesFromBase64(b64: string): Uint8Array {
  const bin = globalThis.atob(b64);
  const arr = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; ++i) {
    arr[i] = bin.charCodeAt(i);
  }
  return arr;
}

function base64FromBytes(arr: Uint8Array): string {
  const bin: string[] = [];
  arr.forEach((byte) => {
    bin.push(globalThis.String.fromCharCode(byte));
  });
  return globalThis.btoa(bin.join(""));
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in Exclude<keyof T, "$type">]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P> | "$type">]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T, V extends string> {
  readonly $type: V;
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
