// SYNCH 心契协议 — 主协议定义
// 包含：节点身份、多服务端会话、权限模型

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/synch.proto

package synchv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NodeType 标识节点的角色类型
type NodeType int32

const (
	NodeType_NODE_TYPE_UNSPECIFIED NodeType = 0
	NodeType_NODE_TYPE_AGENT       NodeType = 1 // AI助手、自动化脚本
	NodeType_NODE_TYPE_HUMAN       NodeType = 2 // 人、管理员
	NodeType_NODE_TYPE_BRIDGE      NodeType = 3 // 协议转换、外部系统对接
	NodeType_NODE_TYPE_PLUGIN      NodeType = 4 // 宿主环境插件 (vcp-agent, openclaw-agent)
	NodeType_NODE_TYPE_MOBILE      NodeType = 5 // 移动端 App (Android/iOS)
)

// Enum value maps for NodeType.
var (
	NodeType_name = map[int32]string{
		0: "NODE_TYPE_UNSPECIFIED",
		1: "NODE_TYPE_AGENT",
		2: "NODE_TYPE_HUMAN",
		3: "NODE_TYPE_BRIDGE",
		4: "NODE_TYPE_PLUGIN",
		5: "NODE_TYPE_MOBILE",
	}
	NodeType_value = map[string]int32{
		"NODE_TYPE_UNSPECIFIED": 0,
		"NODE_TYPE_AGENT":       1,
		"NODE_TYPE_HUMAN":       2,
		"NODE_TYPE_BRIDGE":      3,
		"NODE_TYPE_PLUGIN":      4,
		"NODE_TYPE_MOBILE":      5,
	}
)

func (x NodeType) Enum() *NodeType {
	p := new(NodeType)
	*p = x
	return p
}

func (x NodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_synch_proto_enumTypes[0].Descriptor()
}

func (NodeType) Type() protoreflect.EnumType {
	return &file_v1_synch_proto_enumTypes[0]
}

func (x NodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeType.Descriptor instead.
func (NodeType) EnumDescriptor() ([]byte, []int) {
	return file_v1_synch_proto_rawDescGZIP(), []int{0}
}

// ServerRole 标识客户端与服务端的关系
type ServerRole int32

const (
	ServerRole_SERVER_ROLE_UNSPECIFIED ServerRole = 0
	ServerRole_SERVER_ROLE_PRIMARY     ServerRole = 1 // 主服务端，拥有完整权限
	ServerRole_SERVER_ROLE_SECONDARY   ServerRole = 2 // 备用/镜像服务端
	ServerRole_SERVER_ROLE_GUEST       ServerRole = 3 // 访客身份，受限权限
)

// Enum value maps for ServerRole.
var (
	ServerRole_name = map[int32]string{
		0: "SERVER_ROLE_UNSPECIFIED",
		1: "SERVER_ROLE_PRIMARY",
		2: "SERVER_ROLE_SECONDARY",
		3: "SERVER_ROLE_GUEST",
	}
	ServerRole_value = map[string]int32{
		"SERVER_ROLE_UNSPECIFIED": 0,
		"SERVER_ROLE_PRIMARY":     1,
		"SERVER_ROLE_SECONDARY":   2,
		"SERVER_ROLE_GUEST":       3,
	}
)

func (x ServerRole) Enum() *ServerRole {
	p := new(ServerRole)
	*p = x
	return p
}

func (x ServerRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerRole) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_synch_proto_enumTypes[1].Descriptor()
}

func (ServerRole) Type() protoreflect.EnumType {
	return &file_v1_synch_proto_enumTypes[1]
}

func (x ServerRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerRole.Descriptor instead.
func (ServerRole) EnumDescriptor() ([]byte, []int) {
	return file_v1_synch_proto_rawDescGZIP(), []int{1}
}

// PermissionLevel 标识对 Vault 的操作权限
type PermissionLevel int32

const (
	PermissionLevel_PERMISSION_LEVEL_UNSPECIFIED PermissionLevel = 0
	PermissionLevel_PERMISSION_LEVEL_READ        PermissionLevel = 1 // 只读
	PermissionLevel_PERMISSION_LEVEL_WRITE       PermissionLevel = 2 // 读写
	PermissionLevel_PERMISSION_LEVEL_ADMIN       PermissionLevel = 3 // 完全控制 (含 ACL 管理)
)

// Enum value maps for PermissionLevel.
var (
	PermissionLevel_name = map[int32]string{
		0: "PERMISSION_LEVEL_UNSPECIFIED",
		1: "PERMISSION_LEVEL_READ",
		2: "PERMISSION_LEVEL_WRITE",
		3: "PERMISSION_LEVEL_ADMIN",
	}
	PermissionLevel_value = map[string]int32{
		"PERMISSION_LEVEL_UNSPECIFIED": 0,
		"PERMISSION_LEVEL_READ":        1,
		"PERMISSION_LEVEL_WRITE":       2,
		"PERMISSION_LEVEL_ADMIN":       3,
	}
)

func (x PermissionLevel) Enum() *PermissionLevel {
	p := new(PermissionLevel)
	*p = x
	return p
}

func (x PermissionLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PermissionLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_synch_proto_enumTypes[2].Descriptor()
}

func (PermissionLevel) Type() protoreflect.EnumType {
	return &file_v1_synch_proto_enumTypes[2]
}

func (x PermissionLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PermissionLevel.Descriptor instead.
func (PermissionLevel) EnumDescriptor() ([]byte, []int) {
	return file_v1_synch_proto_rawDescGZIP(), []int{2}
}

// ConflictStrategy 冲突解决策略枚举
type ConflictStrategy int32

const (
	ConflictStrategy_CONFLICT_STRATEGY_UNSPECIFIED ConflictStrategy = 0
	ConflictStrategy_CONFLICT_STRATEGY_AUTO_LOCAL  ConflictStrategy = 1 // 本地优先
	ConflictStrategy_CONFLICT_STRATEGY_AUTO_REMOTE ConflictStrategy = 2 // 远端优先
	ConflictStrategy_CONFLICT_STRATEGY_ASK         ConflictStrategy = 3 // 询问用户
)

// Enum value maps for ConflictStrategy.
var (
	ConflictStrategy_name = map[int32]string{
		0: "CONFLICT_STRATEGY_UNSPECIFIED",
		1: "CONFLICT_STRATEGY_AUTO_LOCAL",
		2: "CONFLICT_STRATEGY_AUTO_REMOTE",
		3: "CONFLICT_STRATEGY_ASK",
	}
	ConflictStrategy_value = map[string]int32{
		"CONFLICT_STRATEGY_UNSPECIFIED": 0,
		"CONFLICT_STRATEGY_AUTO_LOCAL":  1,
		"CONFLICT_STRATEGY_AUTO_REMOTE": 2,
		"CONFLICT_STRATEGY_ASK":         3,
	}
)

func (x ConflictStrategy) Enum() *ConflictStrategy {
	p := new(ConflictStrategy)
	*p = x
	return p
}

func (x ConflictStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConflictStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_synch_proto_enumTypes[3].Descriptor()
}

func (ConflictStrategy) Type() protoreflect.EnumType {
	return &file_v1_synch_proto_enumTypes[3]
}

func (x ConflictStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConflictStrategy.Descriptor instead.
func (ConflictStrategy) EnumDescriptor() ([]byte, []int) {
	return file_v1_synch_proto_rawDescGZIP(), []int{3}
}

// MobileSyncPolicy 移动端同步策略
type MobileSyncPolicy int32

const (
	MobileSyncPolicy_MOBILE_SYNC_POLICY_UNSPECIFIED MobileSyncPolicy = 0
	MobileSyncPolicy_MOBILE_SYNC_POLICY_ALWAYS      MobileSyncPolicy = 1 // 始终同步
	MobileSyncPolicy_MOBILE_SYNC_POLICY_WIFI_ONLY   MobileSyncPolicy = 2 // 仅在 Wi-Fi 下同步
	MobileSyncPolicy_MOBILE_SYNC_POLICY_MANUAL      MobileSyncPolicy = 3 // 手动触发
)

// Enum value maps for MobileSyncPolicy.
var (
	MobileSyncPolicy_name = map[int32]string{
		0: "MOBILE_SYNC_POLICY_UNSPECIFIED",
		1: "MOBILE_SYNC_POLICY_ALWAYS",
		2: "MOBILE_SYNC_POLICY_WIFI_ONLY",
		3: "MOBILE_SYNC_POLICY_MANUAL",
	}
	MobileSyncPolicy_value = map[string]int32{
		"MOBILE_SYNC_POLICY_UNSPECIFIED": 0,
		"MOBILE_SYNC_POLICY_ALWAYS":      1,
		"MOBILE_SYNC_POLICY_WIFI_ONLY":   2,
		"MOBILE_SYNC_POLICY_MANUAL":      3,
	}
)

func (x MobileSyncPolicy) Enum() *MobileSyncPolicy {
	p := new(MobileSyncPolicy)
	*p = x
	return p
}

func (x MobileSyncPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MobileSyncPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_synch_proto_enumTypes[4].Descriptor()
}

func (MobileSyncPolicy) Type() protoreflect.EnumType {
	return &file_v1_synch_proto_enumTypes[4]
}

func (x MobileSyncPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MobileSyncPolicy.Descriptor instead.
func (MobileSyncPolicy) EnumDescriptor() ([]byte, []int) {
	return file_v1_synch_proto_rawDescGZIP(), []int{4}
}

// NodeIdentity 描述网络中的一个节点身份
type NodeIdentity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 节点唯一标识, 格式: "agent://{pk}" | "plugin://{pk}" | "mobile://{pk}" ...
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Ed25519 公钥 (32 bytes)
	PublicKey []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// 节点类型
	NodeType NodeType `protobuf:"varint,3,opt,name=node_type,json=nodeType,proto3,enum=synch.v1.NodeType" json:"node_type,omitempty"`
	// 宿主平台: "vcp-agent" | "openclaw" | "android" | "ios" ...
	Platform string `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	// 能力声明: "chat", "tools", "rag-local", "vault-sync", "ui-panel" ...
	Capabilities []string `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// 注册时间 (Unix epoch millis)
	RegisteredAt uint64 `protobuf:"varint,6,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	// 人类可读的显示名称
	DisplayName string `protobuf:"bytes,7,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// 父节点 ID (用于 Plugin -> Agent 的 1:N 关系)
	ParentNodeId string `protobuf:"bytes,8,opt,name=parent_node_id,json=parentNodeId,proto3" json:"parent_node_id,omitempty"`
	// 扩展元数据 (如环境标签、版本等)
	Metadata      map[string]string `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeIdentity) Reset() {
	*x = NodeIdentity{}
	mi := &file_v1_synch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeIdentity) ProtoMessage() {}

func (x *NodeIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_v1_synch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeIdentity.ProtoReflect.Descriptor instead.
func (*NodeIdentity) Descriptor() ([]byte, []int) {
	return file_v1_synch_proto_rawDescGZIP(), []int{0}
}

func (x *NodeIdentity) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeIdentity) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *NodeIdentity) GetNodeType() NodeType {
	if x != nil {
		return x.NodeType
	}
	return NodeType_NODE_TYPE_UNSPECIFIED
}

func (x *NodeIdentity) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *NodeIdentity) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *NodeIdentity) GetRegisteredAt() uint64 {
	if x != nil {
		return x.RegisteredAt
	}
	return 0
}

func (x *NodeIdentity) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *NodeIdentity) GetParentNodeId() string {
	if x != nil {
		return x.ParentNodeId
	}
	return ""
}

func (x *NodeIdentity) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ServerEndpoint 描述一个客户端连接的服务端
type ServerEndpoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 服务端唯一 ID (如 "home-fnos", "friend-bob")
	ServerId string `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	// WebSocket/gRPC 连接地址 (如 "wss://home.synch.local:8081")
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// 此客户端在该服务端上的角色
	Role ServerRole `protobuf:"varint,3,opt,name=role,proto3,enum=synch.v1.ServerRole" json:"role,omitempty"`
	// 该服务端上各 Vault 的权限映射: vault_id -> VaultPermission
	VaultAccess map[string]*VaultPermission `protobuf:"bytes,4,rep,name=vault_access,json=vaultAccess,proto3" json:"vault_access,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 人类可读的服务端名称 (如 "家里心契")
	DisplayName string `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// 是否自动连接
	AutoConnect bool `protobuf:"varint,6,opt,name=auto_connect,json=autoConnect,proto3" json:"auto_connect,omitempty"`
	// 邀请码 (用于 GUEST 角色加入)
	InviteCode    string `protobuf:"bytes,7,opt,name=invite_code,json=inviteCode,proto3" json:"invite_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEndpoint) Reset() {
	*x = ServerEndpoint{}
	mi := &file_v1_synch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEndpoint) ProtoMessage() {}

func (x *ServerEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_v1_synch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEndpoint.ProtoReflect.Descriptor instead.
func (*ServerEndpoint) Descriptor() ([]byte, []int) {
	return file_v1_synch_proto_rawDescGZIP(), []int{1}
}

func (x *ServerEndpoint) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ServerEndpoint) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ServerEndpoint) GetRole() ServerRole {
	if x != nil {
		return x.Role
	}
	return ServerRole_SERVER_ROLE_UNSPECIFIED
}

func (x *ServerEndpoint) GetVaultAccess() map[string]*VaultPermission {
	if x != nil {
		return x.VaultAccess
	}
	return nil
}

func (x *ServerEndpoint) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ServerEndpoint) GetAutoConnect() bool {
	if x != nil {
		return x.AutoConnect
	}
	return false
}

func (x *ServerEndpoint) GetInviteCode() string {
	if x != nil {
		return x.InviteCode
	}
	return ""
}

// VaultPermission 描述对单个 Vault 的权限
type VaultPermission struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Vault 唯一 ID: Blake3(vault_root_path + owner_pubkey)[0:16]
	VaultId string `protobuf:"bytes,1,opt,name=vault_id,json=vaultId,proto3" json:"vault_id,omitempty"`
	// 权限级别
	Level PermissionLevel `protobuf:"varint,2,opt,name=level,proto3,enum=synch.v1.PermissionLevel" json:"level,omitempty"`
	// 用设备密钥加密的 Vault 密钥 (AES-256-GCM wrapped)
	VaultKeyEncrypted []byte `protobuf:"bytes,3,opt,name=vault_key_encrypted,json=vaultKeyEncrypted,proto3" json:"vault_key_encrypted,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VaultPermission) Reset() {
	*x = VaultPermission{}
	mi := &file_v1_synch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultPermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultPermission) ProtoMessage() {}

func (x *VaultPermission) ProtoReflect() protoreflect.Message {
	mi := &file_v1_synch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultPermission.ProtoReflect.Descriptor instead.
func (*VaultPermission) Descriptor() ([]byte, []int) {
	return file_v1_synch_proto_rawDescGZIP(), []int{2}
}

func (x *VaultPermission) GetVaultId() string {
	if x != nil {
		return x.VaultId
	}
	return ""
}

func (x *VaultPermission) GetLevel() PermissionLevel {
	if x != nil {
		return x.Level
	}
	return PermissionLevel_PERMISSION_LEVEL_UNSPECIFIED
}

func (x *VaultPermission) GetVaultKeyEncrypted() []byte {
	if x != nil {
		return x.VaultKeyEncrypted
	}
	return nil
}

// ClientProfile 描述客户端的身份与多服务端配置
type ClientProfile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 此客户端的身份
	Identity *NodeIdentity `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	// 连接的所有服务端
	Servers []*ServerEndpoint `protobuf:"bytes,2,rep,name=servers,proto3" json:"servers,omitempty"`
	// 同步配置
	SyncConfig    *SyncConfig `protobuf:"bytes,3,opt,name=sync_config,json=syncConfig,proto3" json:"sync_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientProfile) Reset() {
	*x = ClientProfile{}
	mi := &file_v1_synch_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientProfile) ProtoMessage() {}

func (x *ClientProfile) ProtoReflect() protoreflect.Message {
	mi := &file_v1_synch_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientProfile.ProtoReflect.Descriptor instead.
func (*ClientProfile) Descriptor() ([]byte, []int) {
	return file_v1_synch_proto_rawDescGZIP(), []int{3}
}

func (x *ClientProfile) GetIdentity() *NodeIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *ClientProfile) GetServers() []*ServerEndpoint {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *ClientProfile) GetSyncConfig() *SyncConfig {
	if x != nil {
		return x.SyncConfig
	}
	return nil
}

// SyncConfig 全局同步偏好设置
type SyncConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 冲突处理策略
	ConflictStrategy ConflictStrategy `protobuf:"varint,1,opt,name=conflict_strategy,json=conflictStrategy,proto3,enum=synch.v1.ConflictStrategy" json:"conflict_strategy,omitempty"`
	// 带宽限制 (KB/s), 0 = 无限制
	BandwidthLimitKbps uint32 `protobuf:"varint,2,opt,name=bandwidth_limit_kbps,json=bandwidthLimitKbps,proto3" json:"bandwidth_limit_kbps,omitempty"`
	// 移动网络同步策略
	MobileSyncPolicy MobileSyncPolicy `protobuf:"varint,3,opt,name=mobile_sync_policy,json=mobileSyncPolicy,proto3,enum=synch.v1.MobileSyncPolicy" json:"mobile_sync_policy,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SyncConfig) Reset() {
	*x = SyncConfig{}
	mi := &file_v1_synch_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncConfig) ProtoMessage() {}

func (x *SyncConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v1_synch_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncConfig.ProtoReflect.Descriptor instead.
func (*SyncConfig) Descriptor() ([]byte, []int) {
	return file_v1_synch_proto_rawDescGZIP(), []int{4}
}

func (x *SyncConfig) GetConflictStrategy() ConflictStrategy {
	if x != nil {
		return x.ConflictStrategy
	}
	return ConflictStrategy_CONFLICT_STRATEGY_UNSPECIFIED
}

func (x *SyncConfig) GetBandwidthLimitKbps() uint32 {
	if x != nil {
		return x.BandwidthLimitKbps
	}
	return 0
}

func (x *SyncConfig) GetMobileSyncPolicy() MobileSyncPolicy {
	if x != nil {
		return x.MobileSyncPolicy
	}
	return MobileSyncPolicy_MOBILE_SYNC_POLICY_UNSPECIFIED
}

var File_v1_synch_proto protoreflect.FileDescriptor

const file_v1_synch_proto_rawDesc = "" +
	"\n" +
	"\x0ev1/synch.proto\x12\bsynch.v1\"\xa4\x03\n" +
	"\fNodeIdentity\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\x12/\n" +
	"\tnode_type\x18\x03 \x01(\x0e2\x12.synch.v1.NodeTypeR\bnodeType\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities\x12#\n" +
	"\rregistered_at\x18\x06 \x01(\x04R\fregisteredAt\x12!\n" +
	"\fdisplay_name\x18\a \x01(\tR\vdisplayName\x12$\n" +
	"\x0eparent_node_id\x18\b \x01(\tR\fparentNodeId\x12@\n" +
	"\bmetadata\x18\t \x03(\v2$.synch.v1.NodeIdentity.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf9\x02\n" +
	"\x0eServerEndpoint\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12(\n" +
	"\x04role\x18\x03 \x01(\x0e2\x14.synch.v1.ServerRoleR\x04role\x12L\n" +
	"\fvault_access\x18\x04 \x03(\v2).synch.v1.ServerEndpoint.VaultAccessEntryR\vvaultAccess\x12!\n" +
	"\fdisplay_name\x18\x05 \x01(\tR\vdisplayName\x12!\n" +
	"\fauto_connect\x18\x06 \x01(\bR\vautoConnect\x12\x1f\n" +
	"\vinvite_code\x18\a \x01(\tR\n" +
	"inviteCode\x1aY\n" +
	"\x10VaultAccessEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.synch.v1.VaultPermissionR\x05value:\x028\x01\"\x8d\x01\n" +
	"\x0fVaultPermission\x12\x19\n" +
	"\bvault_id\x18\x01 \x01(\tR\avaultId\x12/\n" +
	"\x05level\x18\x02 \x01(\x0e2\x19.synch.v1.PermissionLevelR\x05level\x12.\n" +
	"\x13vault_key_encrypted\x18\x03 \x01(\fR\x11vaultKeyEncrypted\"\xae\x01\n" +
	"\rClientProfile\x122\n" +
	"\bidentity\x18\x01 \x01(\v2\x16.synch.v1.NodeIdentityR\bidentity\x122\n" +
	"\aservers\x18\x02 \x03(\v2\x18.synch.v1.ServerEndpointR\aservers\x125\n" +
	"\vsync_config\x18\x03 \x01(\v2\x14.synch.v1.SyncConfigR\n" +
	"syncConfig\"\xd1\x01\n" +
	"\n" +
	"SyncConfig\x12G\n" +
	"\x11conflict_strategy\x18\x01 \x01(\x0e2\x1a.synch.v1.ConflictStrategyR\x10conflictStrategy\x120\n" +
	"\x14bandwidth_limit_kbps\x18\x02 \x01(\rR\x12bandwidthLimitKbps\x12H\n" +
	"\x12mobile_sync_policy\x18\x03 \x01(\x0e2\x1a.synch.v1.MobileSyncPolicyR\x10mobileSyncPolicy*\x91\x01\n" +
	"\bNodeType\x12\x19\n" +
	"\x15NODE_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fNODE_TYPE_AGENT\x10\x01\x12\x13\n" +
	"\x0fNODE_TYPE_HUMAN\x10\x02\x12\x14\n" +
	"\x10NODE_TYPE_BRIDGE\x10\x03\x12\x14\n" +
	"\x10NODE_TYPE_PLUGIN\x10\x04\x12\x14\n" +
	"\x10NODE_TYPE_MOBILE\x10\x05*t\n" +
	"\n" +
	"ServerRole\x12\x1b\n" +
	"\x17SERVER_ROLE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SERVER_ROLE_PRIMARY\x10\x01\x12\x19\n" +
	"\x15SERVER_ROLE_SECONDARY\x10\x02\x12\x15\n" +
	"\x11SERVER_ROLE_GUEST\x10\x03*\x86\x01\n" +
	"\x0fPermissionLevel\x12 \n" +
	"\x1cPERMISSION_LEVEL_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PERMISSION_LEVEL_READ\x10\x01\x12\x1a\n" +
	"\x16PERMISSION_LEVEL_WRITE\x10\x02\x12\x1a\n" +
	"\x16PERMISSION_LEVEL_ADMIN\x10\x03*\x95\x01\n" +
	"\x10ConflictStrategy\x12!\n" +
	"\x1dCONFLICT_STRATEGY_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cCONFLICT_STRATEGY_AUTO_LOCAL\x10\x01\x12!\n" +
	"\x1dCONFLICT_STRATEGY_AUTO_REMOTE\x10\x02\x12\x19\n" +
	"\x15CONFLICT_STRATEGY_ASK\x10\x03*\x96\x01\n" +
	"\x10MobileSyncPolicy\x12\"\n" +
	"\x1eMOBILE_SYNC_POLICY_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19MOBILE_SYNC_POLICY_ALWAYS\x10\x01\x12 \n" +
	"\x1cMOBILE_SYNC_POLICY_WIFI_ONLY\x10\x02\x12\x1d\n" +
	"\x19MOBILE_SYNC_POLICY_MANUAL\x10\x03B\x12Z\x10synch/v1;synchv1b\x06proto3"

var (
	file_v1_synch_proto_rawDescOnce sync.Once
	file_v1_synch_proto_rawDescData []byte
)

func file_v1_synch_proto_rawDescGZIP() []byte {
	file_v1_synch_proto_rawDescOnce.Do(func() {
		file_v1_synch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_synch_proto_rawDesc), len(file_v1_synch_proto_rawDesc)))
	})
	return file_v1_synch_proto_rawDescData
}

var file_v1_synch_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_v1_synch_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_v1_synch_proto_goTypes = []any{
	(NodeType)(0),           // 0: synch.v1.NodeType
	(ServerRole)(0),         // 1: synch.v1.ServerRole
	(PermissionLevel)(0),    // 2: synch.v1.PermissionLevel
	(ConflictStrategy)(0),   // 3: synch.v1.ConflictStrategy
	(MobileSyncPolicy)(0),   // 4: synch.v1.MobileSyncPolicy
	(*NodeIdentity)(nil),    // 5: synch.v1.NodeIdentity
	(*ServerEndpoint)(nil),  // 6: synch.v1.ServerEndpoint
	(*VaultPermission)(nil), // 7: synch.v1.VaultPermission
	(*ClientProfile)(nil),   // 8: synch.v1.ClientProfile
	(*SyncConfig)(nil),      // 9: synch.v1.SyncConfig
	nil,                     // 10: synch.v1.NodeIdentity.MetadataEntry
	nil,                     // 11: synch.v1.ServerEndpoint.VaultAccessEntry
}
var file_v1_synch_proto_depIdxs = []int32{
	0,  // 0: synch.v1.NodeIdentity.node_type:type_name -> synch.v1.NodeType
	10, // 1: synch.v1.NodeIdentity.metadata:type_name -> synch.v1.NodeIdentity.MetadataEntry
	1,  // 2: synch.v1.ServerEndpoint.role:type_name -> synch.v1.ServerRole
	11, // 3: synch.v1.ServerEndpoint.vault_access:type_name -> synch.v1.ServerEndpoint.VaultAccessEntry
	2,  // 4: synch.v1.VaultPermission.level:type_name -> synch.v1.PermissionLevel
	5,  // 5: synch.v1.ClientProfile.identity:type_name -> synch.v1.NodeIdentity
	6,  // 6: synch.v1.ClientProfile.servers:type_name -> synch.v1.ServerEndpoint
	9,  // 7: synch.v1.ClientProfile.sync_config:type_name -> synch.v1.SyncConfig
	3,  // 8: synch.v1.SyncConfig.conflict_strategy:type_name -> synch.v1.ConflictStrategy
	4,  // 9: synch.v1.SyncConfig.mobile_sync_policy:type_name -> synch.v1.MobileSyncPolicy
	7,  // 10: synch.v1.ServerEndpoint.VaultAccessEntry.value:type_name -> synch.v1.VaultPermission
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_v1_synch_proto_init() }
func file_v1_synch_proto_init() {
	if File_v1_synch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_synch_proto_rawDesc), len(file_v1_synch_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_synch_proto_goTypes,
		DependencyIndexes: file_v1_synch_proto_depIdxs,
		EnumInfos:         file_v1_synch_proto_enumTypes,
		MessageInfos:      file_v1_synch_proto_msgTypes,
	}.Build()
	File_v1_synch_proto = out.File
	file_v1_synch_proto_goTypes = nil
	file_v1_synch_proto_depIdxs = nil
}
