// SYNCH 心契协议 — Vault 同步引擎
// 包含：同步状态机、握手、Delta 传输、冲突检测

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/sync.proto

package synchv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SyncState 对应架构文档中的同步状态图:
//
//	IDLE → CONNECTING → AUTHENTICATING → SYNCING ⇄ SYNCED
type SyncState int32

const (
	SyncState_SYNC_STATE_UNSPECIFIED    SyncState = 0
	SyncState_SYNC_STATE_IDLE           SyncState = 1 // 断开，尚未连接
	SyncState_SYNC_STATE_CONNECTING     SyncState = 2 // 正在建立 WebSocket/gRPC 连接
	SyncState_SYNC_STATE_AUTHENTICATING SyncState = 3 // 已连接，正在进行身份验证
	SyncState_SYNC_STATE_SYNCING        SyncState = 4 // 正在进行增量同步交换
	SyncState_SYNC_STATE_SYNCED         SyncState = 5 // 同步完成，监听变更
	SyncState_SYNC_STATE_ERROR          SyncState = 6 // 发生错误，等待恢复
)

// Enum value maps for SyncState.
var (
	SyncState_name = map[int32]string{
		0: "SYNC_STATE_UNSPECIFIED",
		1: "SYNC_STATE_IDLE",
		2: "SYNC_STATE_CONNECTING",
		3: "SYNC_STATE_AUTHENTICATING",
		4: "SYNC_STATE_SYNCING",
		5: "SYNC_STATE_SYNCED",
		6: "SYNC_STATE_ERROR",
	}
	SyncState_value = map[string]int32{
		"SYNC_STATE_UNSPECIFIED":    0,
		"SYNC_STATE_IDLE":           1,
		"SYNC_STATE_CONNECTING":     2,
		"SYNC_STATE_AUTHENTICATING": 3,
		"SYNC_STATE_SYNCING":        4,
		"SYNC_STATE_SYNCED":         5,
		"SYNC_STATE_ERROR":          6,
	}
)

func (x SyncState) Enum() *SyncState {
	p := new(SyncState)
	*p = x
	return p
}

func (x SyncState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncState) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_sync_proto_enumTypes[0].Descriptor()
}

func (SyncState) Type() protoreflect.EnumType {
	return &file_v1_sync_proto_enumTypes[0]
}

func (x SyncState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncState.Descriptor instead.
func (SyncState) EnumDescriptor() ([]byte, []int) {
	return file_v1_sync_proto_rawDescGZIP(), []int{0}
}

// EntryOperation 文件操作类型
type EntryOperation int32

const (
	EntryOperation_ENTRY_OPERATION_UNSPECIFIED EntryOperation = 0
	EntryOperation_ENTRY_OPERATION_CREATE      EntryOperation = 1
	EntryOperation_ENTRY_OPERATION_MODIFY      EntryOperation = 2
	EntryOperation_ENTRY_OPERATION_DELETE      EntryOperation = 3
	EntryOperation_ENTRY_OPERATION_RENAME      EntryOperation = 4
)

// Enum value maps for EntryOperation.
var (
	EntryOperation_name = map[int32]string{
		0: "ENTRY_OPERATION_UNSPECIFIED",
		1: "ENTRY_OPERATION_CREATE",
		2: "ENTRY_OPERATION_MODIFY",
		3: "ENTRY_OPERATION_DELETE",
		4: "ENTRY_OPERATION_RENAME",
	}
	EntryOperation_value = map[string]int32{
		"ENTRY_OPERATION_UNSPECIFIED": 0,
		"ENTRY_OPERATION_CREATE":      1,
		"ENTRY_OPERATION_MODIFY":      2,
		"ENTRY_OPERATION_DELETE":      3,
		"ENTRY_OPERATION_RENAME":      4,
	}
)

func (x EntryOperation) Enum() *EntryOperation {
	p := new(EntryOperation)
	*p = x
	return p
}

func (x EntryOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntryOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_sync_proto_enumTypes[1].Descriptor()
}

func (EntryOperation) Type() protoreflect.EnumType {
	return &file_v1_sync_proto_enumTypes[1]
}

func (x EntryOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntryOperation.Descriptor instead.
func (EntryOperation) EnumDescriptor() ([]byte, []int) {
	return file_v1_sync_proto_rawDescGZIP(), []int{1}
}

// ConflictResolution 冲突解决方式
type ConflictResolution int32

const (
	ConflictResolution_CONFLICT_RESOLUTION_UNSPECIFIED ConflictResolution = 0
	ConflictResolution_CONFLICT_RESOLUTION_KEEP_LOCAL  ConflictResolution = 1 // 保留本地
	ConflictResolution_CONFLICT_RESOLUTION_KEEP_REMOTE ConflictResolution = 2 // 保留远端
	ConflictResolution_CONFLICT_RESOLUTION_MERGE       ConflictResolution = 3 // CRDT 自动合并
	ConflictResolution_CONFLICT_RESOLUTION_MANUAL      ConflictResolution = 4 // 需要用户手动解决
)

// Enum value maps for ConflictResolution.
var (
	ConflictResolution_name = map[int32]string{
		0: "CONFLICT_RESOLUTION_UNSPECIFIED",
		1: "CONFLICT_RESOLUTION_KEEP_LOCAL",
		2: "CONFLICT_RESOLUTION_KEEP_REMOTE",
		3: "CONFLICT_RESOLUTION_MERGE",
		4: "CONFLICT_RESOLUTION_MANUAL",
	}
	ConflictResolution_value = map[string]int32{
		"CONFLICT_RESOLUTION_UNSPECIFIED": 0,
		"CONFLICT_RESOLUTION_KEEP_LOCAL":  1,
		"CONFLICT_RESOLUTION_KEEP_REMOTE": 2,
		"CONFLICT_RESOLUTION_MERGE":       3,
		"CONFLICT_RESOLUTION_MANUAL":      4,
	}
)

func (x ConflictResolution) Enum() *ConflictResolution {
	p := new(ConflictResolution)
	*p = x
	return p
}

func (x ConflictResolution) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConflictResolution) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_sync_proto_enumTypes[2].Descriptor()
}

func (ConflictResolution) Type() protoreflect.EnumType {
	return &file_v1_sync_proto_enumTypes[2]
}

func (x ConflictResolution) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConflictResolution.Descriptor instead.
func (ConflictResolution) EnumDescriptor() ([]byte, []int) {
	return file_v1_sync_proto_rawDescGZIP(), []int{2}
}

// PresenceStatus 在线状态
type PresenceStatus int32

const (
	PresenceStatus_PRESENCE_STATUS_UNSPECIFIED PresenceStatus = 0
	PresenceStatus_PRESENCE_STATUS_ONLINE      PresenceStatus = 1
	PresenceStatus_PRESENCE_STATUS_AWAY        PresenceStatus = 2
	PresenceStatus_PRESENCE_STATUS_BUSY        PresenceStatus = 3
	PresenceStatus_PRESENCE_STATUS_OFFLINE     PresenceStatus = 4
)

// Enum value maps for PresenceStatus.
var (
	PresenceStatus_name = map[int32]string{
		0: "PRESENCE_STATUS_UNSPECIFIED",
		1: "PRESENCE_STATUS_ONLINE",
		2: "PRESENCE_STATUS_AWAY",
		3: "PRESENCE_STATUS_BUSY",
		4: "PRESENCE_STATUS_OFFLINE",
	}
	PresenceStatus_value = map[string]int32{
		"PRESENCE_STATUS_UNSPECIFIED": 0,
		"PRESENCE_STATUS_ONLINE":      1,
		"PRESENCE_STATUS_AWAY":        2,
		"PRESENCE_STATUS_BUSY":        3,
		"PRESENCE_STATUS_OFFLINE":     4,
	}
)

func (x PresenceStatus) Enum() *PresenceStatus {
	p := new(PresenceStatus)
	*p = x
	return p
}

func (x PresenceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PresenceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_sync_proto_enumTypes[3].Descriptor()
}

func (PresenceStatus) Type() protoreflect.EnumType {
	return &file_v1_sync_proto_enumTypes[3]
}

func (x PresenceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PresenceStatus.Descriptor instead.
func (PresenceStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1_sync_proto_rawDescGZIP(), []int{3}
}

// SyncMessage 是客户端与服务端之间的同步协议帧
type SyncMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 逻辑发送方 ID (当通过 Plugin 中继时使用)
	SenderId string `protobuf:"bytes,7,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	// 逻辑接收方 ID (用于定向路由)
	TargetId string `protobuf:"bytes,8,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*SyncMessage_Handshake
	//	*SyncMessage_Delta
	//	*SyncMessage_Ack
	//	*SyncMessage_Conflict
	//	*SyncMessage_Progress
	//	*SyncMessage_Presence
	//	*SyncMessage_Secured
	//	*SyncMessage_ContractSubmission
	Payload       isSyncMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncMessage) Reset() {
	*x = SyncMessage{}
	mi := &file_v1_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMessage) ProtoMessage() {}

func (x *SyncMessage) ProtoReflect() protoreflect.Message {
	mi := &file_v1_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMessage.ProtoReflect.Descriptor instead.
func (*SyncMessage) Descriptor() ([]byte, []int) {
	return file_v1_sync_proto_rawDescGZIP(), []int{0}
}

func (x *SyncMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *SyncMessage) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *SyncMessage) GetPayload() isSyncMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SyncMessage) GetHandshake() *VaultHandshake {
	if x != nil {
		if x, ok := x.Payload.(*SyncMessage_Handshake); ok {
			return x.Handshake
		}
	}
	return nil
}

func (x *SyncMessage) GetDelta() *DeltaManifest {
	if x != nil {
		if x, ok := x.Payload.(*SyncMessage_Delta); ok {
			return x.Delta
		}
	}
	return nil
}

func (x *SyncMessage) GetAck() *DeltaAck {
	if x != nil {
		if x, ok := x.Payload.(*SyncMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *SyncMessage) GetConflict() *ConflictDetected {
	if x != nil {
		if x, ok := x.Payload.(*SyncMessage_Conflict); ok {
			return x.Conflict
		}
	}
	return nil
}

func (x *SyncMessage) GetProgress() *SyncProgress {
	if x != nil {
		if x, ok := x.Payload.(*SyncMessage_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *SyncMessage) GetPresence() *PresenceUpdate {
	if x != nil {
		if x, ok := x.Payload.(*SyncMessage_Presence); ok {
			return x.Presence
		}
	}
	return nil
}

func (x *SyncMessage) GetSecured() *SecuredMessage {
	if x != nil {
		if x, ok := x.Payload.(*SyncMessage_Secured); ok {
			return x.Secured
		}
	}
	return nil
}

func (x *SyncMessage) GetContractSubmission() *Contract {
	if x != nil {
		if x, ok := x.Payload.(*SyncMessage_ContractSubmission); ok {
			return x.ContractSubmission
		}
	}
	return nil
}

type isSyncMessage_Payload interface {
	isSyncMessage_Payload()
}

type SyncMessage_Handshake struct {
	Handshake *VaultHandshake `protobuf:"bytes,1,opt,name=handshake,proto3,oneof"`
}

type SyncMessage_Delta struct {
	Delta *DeltaManifest `protobuf:"bytes,2,opt,name=delta,proto3,oneof"`
}

type SyncMessage_Ack struct {
	Ack *DeltaAck `protobuf:"bytes,3,opt,name=ack,proto3,oneof"`
}

type SyncMessage_Conflict struct {
	Conflict *ConflictDetected `protobuf:"bytes,4,opt,name=conflict,proto3,oneof"`
}

type SyncMessage_Progress struct {
	Progress *SyncProgress `protobuf:"bytes,5,opt,name=progress,proto3,oneof"`
}

type SyncMessage_Presence struct {
	Presence *PresenceUpdate `protobuf:"bytes,6,opt,name=presence,proto3,oneof"`
}

type SyncMessage_Secured struct {
	// 加密通讯载荷 (E2EE)
	Secured *SecuredMessage `protobuf:"bytes,10,opt,name=secured,proto3,oneof"`
}

type SyncMessage_ContractSubmission struct {
	// 契约握手/提交
	ContractSubmission *Contract `protobuf:"bytes,11,opt,name=contract_submission,json=contractSubmission,proto3,oneof"`
}

func (*SyncMessage_Handshake) isSyncMessage_Payload() {}

func (*SyncMessage_Delta) isSyncMessage_Payload() {}

func (*SyncMessage_Ack) isSyncMessage_Payload() {}

func (*SyncMessage_Conflict) isSyncMessage_Payload() {}

func (*SyncMessage_Progress) isSyncMessage_Payload() {}

func (*SyncMessage_Presence) isSyncMessage_Payload() {}

func (*SyncMessage_Secured) isSyncMessage_Payload() {}

func (*SyncMessage_ContractSubmission) isSyncMessage_Payload() {}

// VaultHandshake 用于同步开始前的版本协商
type VaultHandshake struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 要同步的 Vault ID
	VaultId string `protobuf:"bytes,1,opt,name=vault_id,json=vaultId,proto3" json:"vault_id,omitempty"`
	// 客户端已知的最新版本号
	LocalVersion uint64 `protobuf:"varint,2,opt,name=local_version,json=localVersion,proto3" json:"local_version,omitempty"`
	// 版本向量: node_id → 该节点已知的最大序号
	VersionVector map[string]uint64 `protobuf:"bytes,3,rep,name=version_vector,json=versionVector,proto3" json:"version_vector,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// 客户端支持的同步能力: "delta", "rsync", "full-snapshot" ...
	Capabilities []string `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// 客户端节点 ID (用于服务端标识来源)
	NodeId string `protobuf:"bytes,5,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// 节点类型 (用于权限校验)
	NodeType      NodeType `protobuf:"varint,6,opt,name=node_type,json=nodeType,proto3,enum=synch.v1.NodeType" json:"node_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VaultHandshake) Reset() {
	*x = VaultHandshake{}
	mi := &file_v1_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultHandshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultHandshake) ProtoMessage() {}

func (x *VaultHandshake) ProtoReflect() protoreflect.Message {
	mi := &file_v1_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultHandshake.ProtoReflect.Descriptor instead.
func (*VaultHandshake) Descriptor() ([]byte, []int) {
	return file_v1_sync_proto_rawDescGZIP(), []int{1}
}

func (x *VaultHandshake) GetVaultId() string {
	if x != nil {
		return x.VaultId
	}
	return ""
}

func (x *VaultHandshake) GetLocalVersion() uint64 {
	if x != nil {
		return x.LocalVersion
	}
	return 0
}

func (x *VaultHandshake) GetVersionVector() map[string]uint64 {
	if x != nil {
		return x.VersionVector
	}
	return nil
}

func (x *VaultHandshake) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *VaultHandshake) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *VaultHandshake) GetNodeType() NodeType {
	if x != nil {
		return x.NodeType
	}
	return NodeType_NODE_TYPE_UNSPECIFIED
}

// DeltaManifest 描述一次增量同步批次
type DeltaManifest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Vault ID
	VaultId string `protobuf:"bytes,1,opt,name=vault_id,json=vaultId,proto3" json:"vault_id,omitempty"`
	// 此批次的基线版本
	BaseVersion uint64 `protobuf:"varint,2,opt,name=base_version,json=baseVersion,proto3" json:"base_version,omitempty"`
	// 目标版本
	TargetVersion uint64 `protobuf:"varint,3,opt,name=target_version,json=targetVersion,proto3" json:"target_version,omitempty"`
	// 文件/条目级变更列表
	Changes []*EntryChange `protobuf:"bytes,4,rep,name=changes,proto3" json:"changes,omitempty"`
	// 大文件分块引用
	Blocks []*BlockReference `protobuf:"bytes,5,rep,name=blocks,proto3" json:"blocks,omitempty"`
	// 批次总字节数 (用于进度计算)
	TotalBytes uint64 `protobuf:"varint,6,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	// 签名（用发送方私钥签署的 manifest 摘要）
	ManifestSignature *Signature `protobuf:"bytes,7,opt,name=manifest_signature,json=manifestSignature,proto3" json:"manifest_signature,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeltaManifest) Reset() {
	*x = DeltaManifest{}
	mi := &file_v1_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeltaManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeltaManifest) ProtoMessage() {}

func (x *DeltaManifest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeltaManifest.ProtoReflect.Descriptor instead.
func (*DeltaManifest) Descriptor() ([]byte, []int) {
	return file_v1_sync_proto_rawDescGZIP(), []int{2}
}

func (x *DeltaManifest) GetVaultId() string {
	if x != nil {
		return x.VaultId
	}
	return ""
}

func (x *DeltaManifest) GetBaseVersion() uint64 {
	if x != nil {
		return x.BaseVersion
	}
	return 0
}

func (x *DeltaManifest) GetTargetVersion() uint64 {
	if x != nil {
		return x.TargetVersion
	}
	return 0
}

func (x *DeltaManifest) GetChanges() []*EntryChange {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *DeltaManifest) GetBlocks() []*BlockReference {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *DeltaManifest) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *DeltaManifest) GetManifestSignature() *Signature {
	if x != nil {
		return x.ManifestSignature
	}
	return nil
}

// EntryChange 描述单个文件/条目的变更
type EntryChange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 相对 Vault 根的路径 (如 "notes/daily/2026-03-12.md")
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// 变更操作类型
	Operation EntryOperation `protobuf:"varint,2,opt,name=operation,proto3,enum=synch.v1.EntryOperation" json:"operation,omitempty"`
	// 变更后的内容哈希 (Blake3)
	ContentHash []byte `protobuf:"bytes,3,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	// 仅对 RENAME: 旧路径
	OldPath string `protobuf:"bytes,4,opt,name=old_path,json=oldPath,proto3" json:"old_path,omitempty"`
	// 内联 delta 数据 (小文件直接嵌入)
	DeltaBytes []byte `protobuf:"bytes,5,opt,name=delta_bytes,json=deltaBytes,proto3" json:"delta_bytes,omitempty"`
	// 块级引用 (大文件通过 BlockReference 传输)
	BlockHashes []string `protobuf:"bytes,6,rep,name=block_hashes,json=blockHashes,proto3" json:"block_hashes,omitempty"`
	// 文件大小 (bytes)
	Size uint64 `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	// 修改时间 (Unix epoch millis)
	ModifiedAt uint64 `protobuf:"varint,8,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	// 此变更的版本向量条目: 哪个节点产生了此变更
	OriginNodeId   string `protobuf:"bytes,9,opt,name=origin_node_id,json=originNodeId,proto3" json:"origin_node_id,omitempty"`
	OriginSequence uint64 `protobuf:"varint,10,opt,name=origin_sequence,json=originSequence,proto3" json:"origin_sequence,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EntryChange) Reset() {
	*x = EntryChange{}
	mi := &file_v1_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryChange) ProtoMessage() {}

func (x *EntryChange) ProtoReflect() protoreflect.Message {
	mi := &file_v1_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryChange.ProtoReflect.Descriptor instead.
func (*EntryChange) Descriptor() ([]byte, []int) {
	return file_v1_sync_proto_rawDescGZIP(), []int{3}
}

func (x *EntryChange) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *EntryChange) GetOperation() EntryOperation {
	if x != nil {
		return x.Operation
	}
	return EntryOperation_ENTRY_OPERATION_UNSPECIFIED
}

func (x *EntryChange) GetContentHash() []byte {
	if x != nil {
		return x.ContentHash
	}
	return nil
}

func (x *EntryChange) GetOldPath() string {
	if x != nil {
		return x.OldPath
	}
	return ""
}

func (x *EntryChange) GetDeltaBytes() []byte {
	if x != nil {
		return x.DeltaBytes
	}
	return nil
}

func (x *EntryChange) GetBlockHashes() []string {
	if x != nil {
		return x.BlockHashes
	}
	return nil
}

func (x *EntryChange) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *EntryChange) GetModifiedAt() uint64 {
	if x != nil {
		return x.ModifiedAt
	}
	return 0
}

func (x *EntryChange) GetOriginNodeId() string {
	if x != nil {
		return x.OriginNodeId
	}
	return ""
}

func (x *EntryChange) GetOriginSequence() uint64 {
	if x != nil {
		return x.OriginSequence
	}
	return 0
}

// BlockReference 大文件分块引用
type BlockReference struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 块内容的 Blake3 哈希 (作为唯一标识)
	BlockHash []byte `protobuf:"bytes,1,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	// 块大小 (bytes)
	Size uint32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	// 块在原文件中的偏移量
	Offset uint64 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	// 加密后的块数据 (传输时填充)
	EncryptedData []byte `protobuf:"bytes,4,opt,name=encrypted_data,json=encryptedData,proto3" json:"encrypted_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockReference) Reset() {
	*x = BlockReference{}
	mi := &file_v1_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockReference) ProtoMessage() {}

func (x *BlockReference) ProtoReflect() protoreflect.Message {
	mi := &file_v1_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockReference.ProtoReflect.Descriptor instead.
func (*BlockReference) Descriptor() ([]byte, []int) {
	return file_v1_sync_proto_rawDescGZIP(), []int{4}
}

func (x *BlockReference) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *BlockReference) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *BlockReference) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *BlockReference) GetEncryptedData() []byte {
	if x != nil {
		return x.EncryptedData
	}
	return nil
}

// DeltaAck 确认接收并应用了 delta
type DeltaAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VaultId       string                 `protobuf:"bytes,1,opt,name=vault_id,json=vaultId,proto3" json:"vault_id,omitempty"`
	AckedVersion  uint64                 `protobuf:"varint,2,opt,name=acked_version,json=ackedVersion,proto3" json:"acked_version,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"` // 若 success=false, 描述原因
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeltaAck) Reset() {
	*x = DeltaAck{}
	mi := &file_v1_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeltaAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeltaAck) ProtoMessage() {}

func (x *DeltaAck) ProtoReflect() protoreflect.Message {
	mi := &file_v1_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeltaAck.ProtoReflect.Descriptor instead.
func (*DeltaAck) Descriptor() ([]byte, []int) {
	return file_v1_sync_proto_rawDescGZIP(), []int{5}
}

func (x *DeltaAck) GetVaultId() string {
	if x != nil {
		return x.VaultId
	}
	return ""
}

func (x *DeltaAck) GetAckedVersion() uint64 {
	if x != nil {
		return x.AckedVersion
	}
	return 0
}

func (x *DeltaAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeltaAck) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// SyncProgress 报告同步进度
type SyncProgress struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	VaultId          string                 `protobuf:"bytes,1,opt,name=vault_id,json=vaultId,proto3" json:"vault_id,omitempty"`
	TotalEntries     uint64                 `protobuf:"varint,2,opt,name=total_entries,json=totalEntries,proto3" json:"total_entries,omitempty"`
	CompletedEntries uint64                 `protobuf:"varint,3,opt,name=completed_entries,json=completedEntries,proto3" json:"completed_entries,omitempty"`
	TotalBytes       uint64                 `protobuf:"varint,4,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	TransferredBytes uint64                 `protobuf:"varint,5,opt,name=transferred_bytes,json=transferredBytes,proto3" json:"transferred_bytes,omitempty"`
	CurrentState     SyncState              `protobuf:"varint,6,opt,name=current_state,json=currentState,proto3,enum=synch.v1.SyncState" json:"current_state,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SyncProgress) Reset() {
	*x = SyncProgress{}
	mi := &file_v1_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncProgress) ProtoMessage() {}

func (x *SyncProgress) ProtoReflect() protoreflect.Message {
	mi := &file_v1_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncProgress.ProtoReflect.Descriptor instead.
func (*SyncProgress) Descriptor() ([]byte, []int) {
	return file_v1_sync_proto_rawDescGZIP(), []int{6}
}

func (x *SyncProgress) GetVaultId() string {
	if x != nil {
		return x.VaultId
	}
	return ""
}

func (x *SyncProgress) GetTotalEntries() uint64 {
	if x != nil {
		return x.TotalEntries
	}
	return 0
}

func (x *SyncProgress) GetCompletedEntries() uint64 {
	if x != nil {
		return x.CompletedEntries
	}
	return 0
}

func (x *SyncProgress) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *SyncProgress) GetTransferredBytes() uint64 {
	if x != nil {
		return x.TransferredBytes
	}
	return 0
}

func (x *SyncProgress) GetCurrentState() SyncState {
	if x != nil {
		return x.CurrentState
	}
	return SyncState_SYNC_STATE_UNSPECIFIED
}

// ConflictDetected 当版本向量检测到并发修改时发送
type ConflictDetected struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	VaultId string                 `protobuf:"bytes,1,opt,name=vault_id,json=vaultId,proto3" json:"vault_id,omitempty"`
	Path    string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// 本地版本信息
	LocalVersion *EntryChange `protobuf:"bytes,3,opt,name=local_version,json=localVersion,proto3" json:"local_version,omitempty"`
	// 远端版本信息
	RemoteVersion *EntryChange `protobuf:"bytes,4,opt,name=remote_version,json=remoteVersion,proto3" json:"remote_version,omitempty"`
	// 建议的解决策略
	SuggestedResolution ConflictResolution `protobuf:"varint,5,opt,name=suggested_resolution,json=suggestedResolution,proto3,enum=synch.v1.ConflictResolution" json:"suggested_resolution,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ConflictDetected) Reset() {
	*x = ConflictDetected{}
	mi := &file_v1_sync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConflictDetected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConflictDetected) ProtoMessage() {}

func (x *ConflictDetected) ProtoReflect() protoreflect.Message {
	mi := &file_v1_sync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConflictDetected.ProtoReflect.Descriptor instead.
func (*ConflictDetected) Descriptor() ([]byte, []int) {
	return file_v1_sync_proto_rawDescGZIP(), []int{7}
}

func (x *ConflictDetected) GetVaultId() string {
	if x != nil {
		return x.VaultId
	}
	return ""
}

func (x *ConflictDetected) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ConflictDetected) GetLocalVersion() *EntryChange {
	if x != nil {
		return x.LocalVersion
	}
	return nil
}

func (x *ConflictDetected) GetRemoteVersion() *EntryChange {
	if x != nil {
		return x.RemoteVersion
	}
	return nil
}

func (x *ConflictDetected) GetSuggestedResolution() ConflictResolution {
	if x != nil {
		return x.SuggestedResolution
	}
	return ConflictResolution_CONFLICT_RESOLUTION_UNSPECIFIED
}

// PresenceUpdate 广播节点在线状态
type PresenceUpdate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Status          PresenceStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=synch.v1.PresenceStatus" json:"status,omitempty"`
	LastSeen        uint64                 `protobuf:"varint,3,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`                                                    // Unix epoch millis
	ActiveVaultId   string                 `protobuf:"bytes,4,opt,name=active_vault_id,json=activeVaultId,proto3" json:"active_vault_id,omitempty"`                                    // 当前活跃的 Vault (可选)
	PerceptionLevel PerceptionLevel        `protobuf:"varint,5,opt,name=perception_level,json=perceptionLevel,proto3,enum=synch.v1.PerceptionLevel" json:"perception_level,omitempty"` // 感知层级
	// 节点当前的首选中继节点 URLs
	PreferredRelays []string `protobuf:"bytes,6,rep,name=preferred_relays,json=preferredRelays,proto3" json:"preferred_relays,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PresenceUpdate) Reset() {
	*x = PresenceUpdate{}
	mi := &file_v1_sync_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceUpdate) ProtoMessage() {}

func (x *PresenceUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_v1_sync_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceUpdate.ProtoReflect.Descriptor instead.
func (*PresenceUpdate) Descriptor() ([]byte, []int) {
	return file_v1_sync_proto_rawDescGZIP(), []int{8}
}

func (x *PresenceUpdate) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PresenceUpdate) GetStatus() PresenceStatus {
	if x != nil {
		return x.Status
	}
	return PresenceStatus_PRESENCE_STATUS_UNSPECIFIED
}

func (x *PresenceUpdate) GetLastSeen() uint64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

func (x *PresenceUpdate) GetActiveVaultId() string {
	if x != nil {
		return x.ActiveVaultId
	}
	return ""
}

func (x *PresenceUpdate) GetPerceptionLevel() PerceptionLevel {
	if x != nil {
		return x.PerceptionLevel
	}
	return PerceptionLevel_PERCEPTION_LEVEL_UNSPECIFIED
}

func (x *PresenceUpdate) GetPreferredRelays() []string {
	if x != nil {
		return x.PreferredRelays
	}
	return nil
}

var File_v1_sync_proto protoreflect.FileDescriptor

const file_v1_sync_proto_rawDesc = "" +
	"\n" +
	"\rv1/sync.proto\x12\bsynch.v1\x1a\x0fv1/crypto.proto\x1a\x0ev1/synch.proto\"\x8a\x04\n" +
	"\vSyncMessage\x12\x1b\n" +
	"\tsender_id\x18\a \x01(\tR\bsenderId\x12\x1b\n" +
	"\ttarget_id\x18\b \x01(\tR\btargetId\x128\n" +
	"\thandshake\x18\x01 \x01(\v2\x18.synch.v1.VaultHandshakeH\x00R\thandshake\x12/\n" +
	"\x05delta\x18\x02 \x01(\v2\x17.synch.v1.DeltaManifestH\x00R\x05delta\x12&\n" +
	"\x03ack\x18\x03 \x01(\v2\x12.synch.v1.DeltaAckH\x00R\x03ack\x128\n" +
	"\bconflict\x18\x04 \x01(\v2\x1a.synch.v1.ConflictDetectedH\x00R\bconflict\x124\n" +
	"\bprogress\x18\x05 \x01(\v2\x16.synch.v1.SyncProgressH\x00R\bprogress\x126\n" +
	"\bpresence\x18\x06 \x01(\v2\x18.synch.v1.PresenceUpdateH\x00R\bpresence\x124\n" +
	"\asecured\x18\n" +
	" \x01(\v2\x18.synch.v1.SecuredMessageH\x00R\asecured\x12E\n" +
	"\x13contract_submission\x18\v \x01(\v2\x12.synch.v1.ContractH\x00R\x12contractSubmissionB\t\n" +
	"\apayload\"\xd4\x02\n" +
	"\x0eVaultHandshake\x12\x19\n" +
	"\bvault_id\x18\x01 \x01(\tR\avaultId\x12#\n" +
	"\rlocal_version\x18\x02 \x01(\x04R\flocalVersion\x12R\n" +
	"\x0eversion_vector\x18\x03 \x03(\v2+.synch.v1.VaultHandshake.VersionVectorEntryR\rversionVector\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x12\x17\n" +
	"\anode_id\x18\x05 \x01(\tR\x06nodeId\x12/\n" +
	"\tnode_type\x18\x06 \x01(\x0e2\x12.synch.v1.NodeTypeR\bnodeType\x1a@\n" +
	"\x12VersionVectorEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"\xbc\x02\n" +
	"\rDeltaManifest\x12\x19\n" +
	"\bvault_id\x18\x01 \x01(\tR\avaultId\x12!\n" +
	"\fbase_version\x18\x02 \x01(\x04R\vbaseVersion\x12%\n" +
	"\x0etarget_version\x18\x03 \x01(\x04R\rtargetVersion\x12/\n" +
	"\achanges\x18\x04 \x03(\v2\x15.synch.v1.EntryChangeR\achanges\x120\n" +
	"\x06blocks\x18\x05 \x03(\v2\x18.synch.v1.BlockReferenceR\x06blocks\x12\x1f\n" +
	"\vtotal_bytes\x18\x06 \x01(\x04R\n" +
	"totalBytes\x12B\n" +
	"\x12manifest_signature\x18\a \x01(\v2\x13.synch.v1.SignatureR\x11manifestSignature\"\xdf\x02\n" +
	"\vEntryChange\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x126\n" +
	"\toperation\x18\x02 \x01(\x0e2\x18.synch.v1.EntryOperationR\toperation\x12!\n" +
	"\fcontent_hash\x18\x03 \x01(\fR\vcontentHash\x12\x19\n" +
	"\bold_path\x18\x04 \x01(\tR\aoldPath\x12\x1f\n" +
	"\vdelta_bytes\x18\x05 \x01(\fR\n" +
	"deltaBytes\x12!\n" +
	"\fblock_hashes\x18\x06 \x03(\tR\vblockHashes\x12\x12\n" +
	"\x04size\x18\a \x01(\x04R\x04size\x12\x1f\n" +
	"\vmodified_at\x18\b \x01(\x04R\n" +
	"modifiedAt\x12$\n" +
	"\x0eorigin_node_id\x18\t \x01(\tR\foriginNodeId\x12'\n" +
	"\x0forigin_sequence\x18\n" +
	" \x01(\x04R\x0eoriginSequence\"\x82\x01\n" +
	"\x0eBlockReference\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x01 \x01(\fR\tblockHash\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04size\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\x12%\n" +
	"\x0eencrypted_data\x18\x04 \x01(\fR\rencryptedData\"\x89\x01\n" +
	"\bDeltaAck\x12\x19\n" +
	"\bvault_id\x18\x01 \x01(\tR\avaultId\x12#\n" +
	"\racked_version\x18\x02 \x01(\x04R\fackedVersion\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"\x83\x02\n" +
	"\fSyncProgress\x12\x19\n" +
	"\bvault_id\x18\x01 \x01(\tR\avaultId\x12#\n" +
	"\rtotal_entries\x18\x02 \x01(\x04R\ftotalEntries\x12+\n" +
	"\x11completed_entries\x18\x03 \x01(\x04R\x10completedEntries\x12\x1f\n" +
	"\vtotal_bytes\x18\x04 \x01(\x04R\n" +
	"totalBytes\x12+\n" +
	"\x11transferred_bytes\x18\x05 \x01(\x04R\x10transferredBytes\x128\n" +
	"\rcurrent_state\x18\x06 \x01(\x0e2\x13.synch.v1.SyncStateR\fcurrentState\"\x8c\x02\n" +
	"\x10ConflictDetected\x12\x19\n" +
	"\bvault_id\x18\x01 \x01(\tR\avaultId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12:\n" +
	"\rlocal_version\x18\x03 \x01(\v2\x15.synch.v1.EntryChangeR\flocalVersion\x12<\n" +
	"\x0eremote_version\x18\x04 \x01(\v2\x15.synch.v1.EntryChangeR\rremoteVersion\x12O\n" +
	"\x14suggested_resolution\x18\x05 \x01(\x0e2\x1c.synch.v1.ConflictResolutionR\x13suggestedResolution\"\x91\x02\n" +
	"\x0ePresenceUpdate\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.synch.v1.PresenceStatusR\x06status\x12\x1b\n" +
	"\tlast_seen\x18\x03 \x01(\x04R\blastSeen\x12&\n" +
	"\x0factive_vault_id\x18\x04 \x01(\tR\ractiveVaultId\x12D\n" +
	"\x10perception_level\x18\x05 \x01(\x0e2\x19.synch.v1.PerceptionLevelR\x0fperceptionLevel\x12)\n" +
	"\x10preferred_relays\x18\x06 \x03(\tR\x0fpreferredRelays*\xbb\x01\n" +
	"\tSyncState\x12\x1a\n" +
	"\x16SYNC_STATE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fSYNC_STATE_IDLE\x10\x01\x12\x19\n" +
	"\x15SYNC_STATE_CONNECTING\x10\x02\x12\x1d\n" +
	"\x19SYNC_STATE_AUTHENTICATING\x10\x03\x12\x16\n" +
	"\x12SYNC_STATE_SYNCING\x10\x04\x12\x15\n" +
	"\x11SYNC_STATE_SYNCED\x10\x05\x12\x14\n" +
	"\x10SYNC_STATE_ERROR\x10\x06*\xa1\x01\n" +
	"\x0eEntryOperation\x12\x1f\n" +
	"\x1bENTRY_OPERATION_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16ENTRY_OPERATION_CREATE\x10\x01\x12\x1a\n" +
	"\x16ENTRY_OPERATION_MODIFY\x10\x02\x12\x1a\n" +
	"\x16ENTRY_OPERATION_DELETE\x10\x03\x12\x1a\n" +
	"\x16ENTRY_OPERATION_RENAME\x10\x04*\xc1\x01\n" +
	"\x12ConflictResolution\x12#\n" +
	"\x1fCONFLICT_RESOLUTION_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eCONFLICT_RESOLUTION_KEEP_LOCAL\x10\x01\x12#\n" +
	"\x1fCONFLICT_RESOLUTION_KEEP_REMOTE\x10\x02\x12\x1d\n" +
	"\x19CONFLICT_RESOLUTION_MERGE\x10\x03\x12\x1e\n" +
	"\x1aCONFLICT_RESOLUTION_MANUAL\x10\x04*\x9e\x01\n" +
	"\x0ePresenceStatus\x12\x1f\n" +
	"\x1bPRESENCE_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PRESENCE_STATUS_ONLINE\x10\x01\x12\x18\n" +
	"\x14PRESENCE_STATUS_AWAY\x10\x02\x12\x18\n" +
	"\x14PRESENCE_STATUS_BUSY\x10\x03\x12\x1b\n" +
	"\x17PRESENCE_STATUS_OFFLINE\x10\x04B\x12Z\x10synch/v1;synchv1b\x06proto3"

var (
	file_v1_sync_proto_rawDescOnce sync.Once
	file_v1_sync_proto_rawDescData []byte
)

func file_v1_sync_proto_rawDescGZIP() []byte {
	file_v1_sync_proto_rawDescOnce.Do(func() {
		file_v1_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_sync_proto_rawDesc), len(file_v1_sync_proto_rawDesc)))
	})
	return file_v1_sync_proto_rawDescData
}

var file_v1_sync_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_v1_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_v1_sync_proto_goTypes = []any{
	(SyncState)(0),           // 0: synch.v1.SyncState
	(EntryOperation)(0),      // 1: synch.v1.EntryOperation
	(ConflictResolution)(0),  // 2: synch.v1.ConflictResolution
	(PresenceStatus)(0),      // 3: synch.v1.PresenceStatus
	(*SyncMessage)(nil),      // 4: synch.v1.SyncMessage
	(*VaultHandshake)(nil),   // 5: synch.v1.VaultHandshake
	(*DeltaManifest)(nil),    // 6: synch.v1.DeltaManifest
	(*EntryChange)(nil),      // 7: synch.v1.EntryChange
	(*BlockReference)(nil),   // 8: synch.v1.BlockReference
	(*DeltaAck)(nil),         // 9: synch.v1.DeltaAck
	(*SyncProgress)(nil),     // 10: synch.v1.SyncProgress
	(*ConflictDetected)(nil), // 11: synch.v1.ConflictDetected
	(*PresenceUpdate)(nil),   // 12: synch.v1.PresenceUpdate
	nil,                      // 13: synch.v1.VaultHandshake.VersionVectorEntry
	(*SecuredMessage)(nil),   // 14: synch.v1.SecuredMessage
	(*Contract)(nil),         // 15: synch.v1.Contract
	(NodeType)(0),            // 16: synch.v1.NodeType
	(*Signature)(nil),        // 17: synch.v1.Signature
	(PerceptionLevel)(0),     // 18: synch.v1.PerceptionLevel
}
var file_v1_sync_proto_depIdxs = []int32{
	5,  // 0: synch.v1.SyncMessage.handshake:type_name -> synch.v1.VaultHandshake
	6,  // 1: synch.v1.SyncMessage.delta:type_name -> synch.v1.DeltaManifest
	9,  // 2: synch.v1.SyncMessage.ack:type_name -> synch.v1.DeltaAck
	11, // 3: synch.v1.SyncMessage.conflict:type_name -> synch.v1.ConflictDetected
	10, // 4: synch.v1.SyncMessage.progress:type_name -> synch.v1.SyncProgress
	12, // 5: synch.v1.SyncMessage.presence:type_name -> synch.v1.PresenceUpdate
	14, // 6: synch.v1.SyncMessage.secured:type_name -> synch.v1.SecuredMessage
	15, // 7: synch.v1.SyncMessage.contract_submission:type_name -> synch.v1.Contract
	13, // 8: synch.v1.VaultHandshake.version_vector:type_name -> synch.v1.VaultHandshake.VersionVectorEntry
	16, // 9: synch.v1.VaultHandshake.node_type:type_name -> synch.v1.NodeType
	7,  // 10: synch.v1.DeltaManifest.changes:type_name -> synch.v1.EntryChange
	8,  // 11: synch.v1.DeltaManifest.blocks:type_name -> synch.v1.BlockReference
	17, // 12: synch.v1.DeltaManifest.manifest_signature:type_name -> synch.v1.Signature
	1,  // 13: synch.v1.EntryChange.operation:type_name -> synch.v1.EntryOperation
	0,  // 14: synch.v1.SyncProgress.current_state:type_name -> synch.v1.SyncState
	7,  // 15: synch.v1.ConflictDetected.local_version:type_name -> synch.v1.EntryChange
	7,  // 16: synch.v1.ConflictDetected.remote_version:type_name -> synch.v1.EntryChange
	2,  // 17: synch.v1.ConflictDetected.suggested_resolution:type_name -> synch.v1.ConflictResolution
	3,  // 18: synch.v1.PresenceUpdate.status:type_name -> synch.v1.PresenceStatus
	18, // 19: synch.v1.PresenceUpdate.perception_level:type_name -> synch.v1.PerceptionLevel
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_v1_sync_proto_init() }
func file_v1_sync_proto_init() {
	if File_v1_sync_proto != nil {
		return
	}
	file_v1_crypto_proto_init()
	file_v1_synch_proto_init()
	file_v1_sync_proto_msgTypes[0].OneofWrappers = []any{
		(*SyncMessage_Handshake)(nil),
		(*SyncMessage_Delta)(nil),
		(*SyncMessage_Ack)(nil),
		(*SyncMessage_Conflict)(nil),
		(*SyncMessage_Progress)(nil),
		(*SyncMessage_Presence)(nil),
		(*SyncMessage_Secured)(nil),
		(*SyncMessage_ContractSubmission)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_sync_proto_rawDesc), len(file_v1_sync_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_sync_proto_goTypes,
		DependencyIndexes: file_v1_sync_proto_depIdxs,
		EnumInfos:         file_v1_sync_proto_enumTypes,
		MessageInfos:      file_v1_sync_proto_msgTypes,
	}.Build()
	File_v1_sync_proto = out.File
	file_v1_sync_proto_goTypes = nil
	file_v1_sync_proto_depIdxs = nil
}
