// SYNCH 心契协议 — 主协议定义
// 包含：节点身份、多服务端会话、权限模型

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/synch.proto

package synchv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NodeType 标识节点的角色类型
type NodeType int32

const (
	NodeType_NODE_TYPE_UNSPECIFIED NodeType = 0
	NodeType_NODE_TYPE_AGENT       NodeType = 1 // AI助手、自动化脚本
	NodeType_NODE_TYPE_HUMAN       NodeType = 2 // 人、管理员
	NodeType_NODE_TYPE_BRIDGE      NodeType = 3 // 协议转换、外部系统对接
	NodeType_NODE_TYPE_PLUGIN      NodeType = 4 // 宿主环境插件 (vcp-agent, openclaw-agent)
	NodeType_NODE_TYPE_MOBILE      NodeType = 5 // 移动端 App (Android/iOS)
	NodeType_NODE_TYPE_ADMIN       NodeType = 6 // 网络管理员 (全局)
	NodeType_NODE_TYPE_LORD        NodeType = 7 // 节点领主 (单节点最高权限)
	NodeType_NODE_TYPE_SUB_ADMIN   NodeType = 8 // 次级管理员 (管事)
)

// Enum value maps for NodeType.
var (
	NodeType_name = map[int32]string{
		0: "NODE_TYPE_UNSPECIFIED",
		1: "NODE_TYPE_AGENT",
		2: "NODE_TYPE_HUMAN",
		3: "NODE_TYPE_BRIDGE",
		4: "NODE_TYPE_PLUGIN",
		5: "NODE_TYPE_MOBILE",
		6: "NODE_TYPE_ADMIN",
		7: "NODE_TYPE_LORD",
		8: "NODE_TYPE_SUB_ADMIN",
	}
	NodeType_value = map[string]int32{
		"NODE_TYPE_UNSPECIFIED": 0,
		"NODE_TYPE_AGENT":       1,
		"NODE_TYPE_HUMAN":       2,
		"NODE_TYPE_BRIDGE":      3,
		"NODE_TYPE_PLUGIN":      4,
		"NODE_TYPE_MOBILE":      5,
		"NODE_TYPE_ADMIN":       6,
		"NODE_TYPE_LORD":        7,
		"NODE_TYPE_SUB_ADMIN":   8,
	}
)

func (x NodeType) Enum() *NodeType {
	p := new(NodeType)
	*p = x
	return p
}

func (x NodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_synch_proto_enumTypes[0].Descriptor()
}

func (NodeType) Type() protoreflect.EnumType {
	return &file_v1_synch_proto_enumTypes[0]
}

func (x NodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeType.Descriptor instead.
func (NodeType) EnumDescriptor() ([]byte, []int) {
	return file_v1_synch_proto_rawDescGZIP(), []int{0}
}

// PerceptionLevel 定义节点的感知层级 (动态隐私设置)
type PerceptionLevel int32

const (
	PerceptionLevel_PERCEPTION_LEVEL_UNSPECIFIED PerceptionLevel = 0
	PerceptionLevel_PERCEPTION_LEVEL_L0          PerceptionLevel = 0 // 完全公开: 广播完整公钥+历史契约摘要
	PerceptionLevel_PERCEPTION_LEVEL_L1          PerceptionLevel = 1 // 社交轮廓: 广播昵称+能力+信誉摘要
	PerceptionLevel_PERCEPTION_LEVEL_L2          PerceptionLevel = 2 // 能力橱窗: 广播能力标签，无身份 (默认)
	PerceptionLevel_PERCEPTION_LEVEL_L3          PerceptionLevel = 3 // 影子模式: 广播加密指纹，无元数据
	PerceptionLevel_PERCEPTION_LEVEL_L4          PerceptionLevel = 4 // 完全隐形: 不广播，仅响应已知契约
)

// Enum value maps for PerceptionLevel.
var (
	PerceptionLevel_name = map[int32]string{
		0: "PERCEPTION_LEVEL_UNSPECIFIED",
		// Duplicate value: 0: "PERCEPTION_LEVEL_L0",
		1: "PERCEPTION_LEVEL_L1",
		2: "PERCEPTION_LEVEL_L2",
		3: "PERCEPTION_LEVEL_L3",
		4: "PERCEPTION_LEVEL_L4",
	}
	PerceptionLevel_value = map[string]int32{
		"PERCEPTION_LEVEL_UNSPECIFIED": 0,
		"PERCEPTION_LEVEL_L0":          0,
		"PERCEPTION_LEVEL_L1":          1,
		"PERCEPTION_LEVEL_L2":          2,
		"PERCEPTION_LEVEL_L3":          3,
		"PERCEPTION_LEVEL_L4":          4,
	}
)

func (x PerceptionLevel) Enum() *PerceptionLevel {
	p := new(PerceptionLevel)
	*p = x
	return p
}

func (x PerceptionLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PerceptionLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_synch_proto_enumTypes[1].Descriptor()
}

func (PerceptionLevel) Type() protoreflect.EnumType {
	return &file_v1_synch_proto_enumTypes[1]
}

func (x PerceptionLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PerceptionLevel.Descriptor instead.
func (PerceptionLevel) EnumDescriptor() ([]byte, []int) {
	return file_v1_synch_proto_rawDescGZIP(), []int{1}
}

// ServerRole 标识客户端与服务端的关系
type ServerRole int32

const (
	ServerRole_SERVER_ROLE_UNSPECIFIED ServerRole = 0
	ServerRole_SERVER_ROLE_PRIMARY     ServerRole = 1 // 主服务端，拥有完整权限
	ServerRole_SERVER_ROLE_SECONDARY   ServerRole = 2 // 备用/镜像服务端
	ServerRole_SERVER_ROLE_GUEST       ServerRole = 3 // 访客身份，受限权限
)

// Enum value maps for ServerRole.
var (
	ServerRole_name = map[int32]string{
		0: "SERVER_ROLE_UNSPECIFIED",
		1: "SERVER_ROLE_PRIMARY",
		2: "SERVER_ROLE_SECONDARY",
		3: "SERVER_ROLE_GUEST",
	}
	ServerRole_value = map[string]int32{
		"SERVER_ROLE_UNSPECIFIED": 0,
		"SERVER_ROLE_PRIMARY":     1,
		"SERVER_ROLE_SECONDARY":   2,
		"SERVER_ROLE_GUEST":       3,
	}
)

func (x ServerRole) Enum() *ServerRole {
	p := new(ServerRole)
	*p = x
	return p
}

func (x ServerRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerRole) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_synch_proto_enumTypes[2].Descriptor()
}

func (ServerRole) Type() protoreflect.EnumType {
	return &file_v1_synch_proto_enumTypes[2]
}

func (x ServerRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerRole.Descriptor instead.
func (ServerRole) EnumDescriptor() ([]byte, []int) {
	return file_v1_synch_proto_rawDescGZIP(), []int{2}
}

// PermissionLevel 标识对 Vault 的操作权限
type PermissionLevel int32

const (
	PermissionLevel_PERMISSION_LEVEL_UNSPECIFIED PermissionLevel = 0
	PermissionLevel_PERMISSION_LEVEL_READ        PermissionLevel = 1 // 只读
	PermissionLevel_PERMISSION_LEVEL_WRITE       PermissionLevel = 2 // 读写
	PermissionLevel_PERMISSION_LEVEL_ADMIN       PermissionLevel = 3 // 完全控制 (含 ACL 管理)
)

// Enum value maps for PermissionLevel.
var (
	PermissionLevel_name = map[int32]string{
		0: "PERMISSION_LEVEL_UNSPECIFIED",
		1: "PERMISSION_LEVEL_READ",
		2: "PERMISSION_LEVEL_WRITE",
		3: "PERMISSION_LEVEL_ADMIN",
	}
	PermissionLevel_value = map[string]int32{
		"PERMISSION_LEVEL_UNSPECIFIED": 0,
		"PERMISSION_LEVEL_READ":        1,
		"PERMISSION_LEVEL_WRITE":       2,
		"PERMISSION_LEVEL_ADMIN":       3,
	}
)

func (x PermissionLevel) Enum() *PermissionLevel {
	p := new(PermissionLevel)
	*p = x
	return p
}

func (x PermissionLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PermissionLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_synch_proto_enumTypes[3].Descriptor()
}

func (PermissionLevel) Type() protoreflect.EnumType {
	return &file_v1_synch_proto_enumTypes[3]
}

func (x PermissionLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PermissionLevel.Descriptor instead.
func (PermissionLevel) EnumDescriptor() ([]byte, []int) {
	return file_v1_synch_proto_rawDescGZIP(), []int{3}
}

// ConflictStrategy 冲突解决策略枚举
type ConflictStrategy int32

const (
	ConflictStrategy_CONFLICT_STRATEGY_UNSPECIFIED ConflictStrategy = 0
	ConflictStrategy_CONFLICT_STRATEGY_AUTO_LOCAL  ConflictStrategy = 1 // 本地优先
	ConflictStrategy_CONFLICT_STRATEGY_AUTO_REMOTE ConflictStrategy = 2 // 远端优先
	ConflictStrategy_CONFLICT_STRATEGY_ASK         ConflictStrategy = 3 // 询问用户
)

// Enum value maps for ConflictStrategy.
var (
	ConflictStrategy_name = map[int32]string{
		0: "CONFLICT_STRATEGY_UNSPECIFIED",
		1: "CONFLICT_STRATEGY_AUTO_LOCAL",
		2: "CONFLICT_STRATEGY_AUTO_REMOTE",
		3: "CONFLICT_STRATEGY_ASK",
	}
	ConflictStrategy_value = map[string]int32{
		"CONFLICT_STRATEGY_UNSPECIFIED": 0,
		"CONFLICT_STRATEGY_AUTO_LOCAL":  1,
		"CONFLICT_STRATEGY_AUTO_REMOTE": 2,
		"CONFLICT_STRATEGY_ASK":         3,
	}
)

func (x ConflictStrategy) Enum() *ConflictStrategy {
	p := new(ConflictStrategy)
	*p = x
	return p
}

func (x ConflictStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConflictStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_synch_proto_enumTypes[4].Descriptor()
}

func (ConflictStrategy) Type() protoreflect.EnumType {
	return &file_v1_synch_proto_enumTypes[4]
}

func (x ConflictStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConflictStrategy.Descriptor instead.
func (ConflictStrategy) EnumDescriptor() ([]byte, []int) {
	return file_v1_synch_proto_rawDescGZIP(), []int{4}
}

// MobileSyncPolicy 移动端同步策略
type MobileSyncPolicy int32

const (
	MobileSyncPolicy_MOBILE_SYNC_POLICY_UNSPECIFIED MobileSyncPolicy = 0
	MobileSyncPolicy_MOBILE_SYNC_POLICY_ALWAYS      MobileSyncPolicy = 1 // 始终同步
	MobileSyncPolicy_MOBILE_SYNC_POLICY_WIFI_ONLY   MobileSyncPolicy = 2 // 仅在 Wi-Fi 下同步
	MobileSyncPolicy_MOBILE_SYNC_POLICY_MANUAL      MobileSyncPolicy = 3 // 手动触发
)

// Enum value maps for MobileSyncPolicy.
var (
	MobileSyncPolicy_name = map[int32]string{
		0: "MOBILE_SYNC_POLICY_UNSPECIFIED",
		1: "MOBILE_SYNC_POLICY_ALWAYS",
		2: "MOBILE_SYNC_POLICY_WIFI_ONLY",
		3: "MOBILE_SYNC_POLICY_MANUAL",
	}
	MobileSyncPolicy_value = map[string]int32{
		"MOBILE_SYNC_POLICY_UNSPECIFIED": 0,
		"MOBILE_SYNC_POLICY_ALWAYS":      1,
		"MOBILE_SYNC_POLICY_WIFI_ONLY":   2,
		"MOBILE_SYNC_POLICY_MANUAL":      3,
	}
)

func (x MobileSyncPolicy) Enum() *MobileSyncPolicy {
	p := new(MobileSyncPolicy)
	*p = x
	return p
}

func (x MobileSyncPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MobileSyncPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_synch_proto_enumTypes[5].Descriptor()
}

func (MobileSyncPolicy) Type() protoreflect.EnumType {
	return &file_v1_synch_proto_enumTypes[5]
}

func (x MobileSyncPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MobileSyncPolicy.Descriptor instead.
func (MobileSyncPolicy) EnumDescriptor() ([]byte, []int) {
	return file_v1_synch_proto_rawDescGZIP(), []int{5}
}

// ContractStatus 契约生命周期状态
type ContractStatus int32

const (
	ContractStatus_CONTRACT_STATUS_UNSPECIFIED ContractStatus = 0
	ContractStatus_CONTRACT_STATUS_PENDING     ContractStatus = 1 // 等待握手确认
	ContractStatus_CONTRACT_STATUS_ACTIVE      ContractStatus = 2 // 活跃，正常通讯
	ContractStatus_CONTRACT_STATUS_SUSPENDED   ContractStatus = 3 // 已挂起，暂时屏蔽消息
	ContractStatus_CONTRACT_STATUS_EXPIRING    ContractStatus = 4 // 即将过期，需续期
	ContractStatus_CONTRACT_STATUS_TERMINATED  ContractStatus = 5 // 已终止，密钥失效
)

// Enum value maps for ContractStatus.
var (
	ContractStatus_name = map[int32]string{
		0: "CONTRACT_STATUS_UNSPECIFIED",
		1: "CONTRACT_STATUS_PENDING",
		2: "CONTRACT_STATUS_ACTIVE",
		3: "CONTRACT_STATUS_SUSPENDED",
		4: "CONTRACT_STATUS_EXPIRING",
		5: "CONTRACT_STATUS_TERMINATED",
	}
	ContractStatus_value = map[string]int32{
		"CONTRACT_STATUS_UNSPECIFIED": 0,
		"CONTRACT_STATUS_PENDING":     1,
		"CONTRACT_STATUS_ACTIVE":      2,
		"CONTRACT_STATUS_SUSPENDED":   3,
		"CONTRACT_STATUS_EXPIRING":    4,
		"CONTRACT_STATUS_TERMINATED":  5,
	}
)

func (x ContractStatus) Enum() *ContractStatus {
	p := new(ContractStatus)
	*p = x
	return p
}

func (x ContractStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContractStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_synch_proto_enumTypes[6].Descriptor()
}

func (ContractStatus) Type() protoreflect.EnumType {
	return &file_v1_synch_proto_enumTypes[6]
}

func (x ContractStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContractStatus.Descriptor instead.
func (ContractStatus) EnumDescriptor() ([]byte, []int) {
	return file_v1_synch_proto_rawDescGZIP(), []int{6}
}

// NodeIdentity 描述网络中的一个节点身份
type NodeIdentity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 节点唯一标识, 格式: "agent://{pk}" | "plugin://{pk}" | "mobile://{pk}" ...
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Ed25519 公钥 (32 bytes)
	PublicKey []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// 节点类型
	NodeType NodeType `protobuf:"varint,3,opt,name=node_type,json=nodeType,proto3,enum=synch.v1.NodeType" json:"node_type,omitempty"`
	// 宿主平台: "vcp-agent" | "openclaw" | "android" | "ios" ...
	Platform string `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	// 能力声明: "chat", "tools", "rag-local", "vault-sync", "ui-panel" ...
	Capabilities []string `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// 注册时间 (Unix epoch millis)
	RegisteredAt uint64 `protobuf:"varint,6,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	// 人类可读的显示名称
	DisplayName string `protobuf:"bytes,7,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// 父节点 ID (用于 Plugin -> Agent 的 1:N 关系)
	ParentNodeId string `protobuf:"bytes,8,opt,name=parent_node_id,json=parentNodeId,proto3" json:"parent_node_id,omitempty"`
	// 扩展元数据 (如环境标签、版本等)
	Metadata      map[string]string `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeIdentity) Reset() {
	*x = NodeIdentity{}
	mi := &file_v1_synch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeIdentity) ProtoMessage() {}

func (x *NodeIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_v1_synch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeIdentity.ProtoReflect.Descriptor instead.
func (*NodeIdentity) Descriptor() ([]byte, []int) {
	return file_v1_synch_proto_rawDescGZIP(), []int{0}
}

func (x *NodeIdentity) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeIdentity) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *NodeIdentity) GetNodeType() NodeType {
	if x != nil {
		return x.NodeType
	}
	return NodeType_NODE_TYPE_UNSPECIFIED
}

func (x *NodeIdentity) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *NodeIdentity) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *NodeIdentity) GetRegisteredAt() uint64 {
	if x != nil {
		return x.RegisteredAt
	}
	return 0
}

func (x *NodeIdentity) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *NodeIdentity) GetParentNodeId() string {
	if x != nil {
		return x.ParentNodeId
	}
	return ""
}

func (x *NodeIdentity) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ServerEndpoint 描述一个客户端连接的服务端
type ServerEndpoint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 服务端唯一 ID (如 "home-fnos", "friend-bob")
	ServerId string `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	// WebSocket/gRPC 连接地址 (如 "wss://home.synch.local:8081")
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// 此客户端在该服务端上的角色
	Role ServerRole `protobuf:"varint,3,opt,name=role,proto3,enum=synch.v1.ServerRole" json:"role,omitempty"`
	// 该服务端上各 Vault 的权限映射: vault_id -> VaultPermission
	VaultAccess map[string]*VaultPermission `protobuf:"bytes,4,rep,name=vault_access,json=vaultAccess,proto3" json:"vault_access,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 人类可读的服务端名称 (如 "家里心契")
	DisplayName string `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// 是否自动连接
	AutoConnect bool `protobuf:"varint,6,opt,name=auto_connect,json=autoConnect,proto3" json:"auto_connect,omitempty"`
	// 邀请码 (用于 GUEST 角色加入)
	InviteCode    string `protobuf:"bytes,7,opt,name=invite_code,json=inviteCode,proto3" json:"invite_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEndpoint) Reset() {
	*x = ServerEndpoint{}
	mi := &file_v1_synch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEndpoint) ProtoMessage() {}

func (x *ServerEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_v1_synch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEndpoint.ProtoReflect.Descriptor instead.
func (*ServerEndpoint) Descriptor() ([]byte, []int) {
	return file_v1_synch_proto_rawDescGZIP(), []int{1}
}

func (x *ServerEndpoint) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ServerEndpoint) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ServerEndpoint) GetRole() ServerRole {
	if x != nil {
		return x.Role
	}
	return ServerRole_SERVER_ROLE_UNSPECIFIED
}

func (x *ServerEndpoint) GetVaultAccess() map[string]*VaultPermission {
	if x != nil {
		return x.VaultAccess
	}
	return nil
}

func (x *ServerEndpoint) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ServerEndpoint) GetAutoConnect() bool {
	if x != nil {
		return x.AutoConnect
	}
	return false
}

func (x *ServerEndpoint) GetInviteCode() string {
	if x != nil {
		return x.InviteCode
	}
	return ""
}

// VaultPermission 描述对单个 Vault 的权限
type VaultPermission struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Vault 唯一 ID: Blake3(vault_root_path + owner_pubkey)[0:16]
	VaultId string `protobuf:"bytes,1,opt,name=vault_id,json=vaultId,proto3" json:"vault_id,omitempty"`
	// 权限级别
	Level PermissionLevel `protobuf:"varint,2,opt,name=level,proto3,enum=synch.v1.PermissionLevel" json:"level,omitempty"`
	// 用设备密钥加密的 Vault 密钥 (AES-256-GCM wrapped)
	VaultKeyEncrypted []byte `protobuf:"bytes,3,opt,name=vault_key_encrypted,json=vaultKeyEncrypted,proto3" json:"vault_key_encrypted,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VaultPermission) Reset() {
	*x = VaultPermission{}
	mi := &file_v1_synch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultPermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultPermission) ProtoMessage() {}

func (x *VaultPermission) ProtoReflect() protoreflect.Message {
	mi := &file_v1_synch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultPermission.ProtoReflect.Descriptor instead.
func (*VaultPermission) Descriptor() ([]byte, []int) {
	return file_v1_synch_proto_rawDescGZIP(), []int{2}
}

func (x *VaultPermission) GetVaultId() string {
	if x != nil {
		return x.VaultId
	}
	return ""
}

func (x *VaultPermission) GetLevel() PermissionLevel {
	if x != nil {
		return x.Level
	}
	return PermissionLevel_PERMISSION_LEVEL_UNSPECIFIED
}

func (x *VaultPermission) GetVaultKeyEncrypted() []byte {
	if x != nil {
		return x.VaultKeyEncrypted
	}
	return nil
}

// ClientProfile 描述客户端的身份与多服务端配置
type ClientProfile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 此客户端的身份
	Identity *NodeIdentity `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	// 连接的所有服务端
	Servers []*ServerEndpoint `protobuf:"bytes,2,rep,name=servers,proto3" json:"servers,omitempty"`
	// 同步配置
	SyncConfig    *SyncConfig `protobuf:"bytes,3,opt,name=sync_config,json=syncConfig,proto3" json:"sync_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientProfile) Reset() {
	*x = ClientProfile{}
	mi := &file_v1_synch_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientProfile) ProtoMessage() {}

func (x *ClientProfile) ProtoReflect() protoreflect.Message {
	mi := &file_v1_synch_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientProfile.ProtoReflect.Descriptor instead.
func (*ClientProfile) Descriptor() ([]byte, []int) {
	return file_v1_synch_proto_rawDescGZIP(), []int{3}
}

func (x *ClientProfile) GetIdentity() *NodeIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *ClientProfile) GetServers() []*ServerEndpoint {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *ClientProfile) GetSyncConfig() *SyncConfig {
	if x != nil {
		return x.SyncConfig
	}
	return nil
}

// SyncConfig 全局同步偏好设置
type SyncConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 冲突处理策略
	ConflictStrategy ConflictStrategy `protobuf:"varint,1,opt,name=conflict_strategy,json=conflictStrategy,proto3,enum=synch.v1.ConflictStrategy" json:"conflict_strategy,omitempty"`
	// 带宽限制 (KB/s), 0 = 无限制
	BandwidthLimitKbps uint32 `protobuf:"varint,2,opt,name=bandwidth_limit_kbps,json=bandwidthLimitKbps,proto3" json:"bandwidth_limit_kbps,omitempty"`
	// 移动网络同步策略
	MobileSyncPolicy MobileSyncPolicy `protobuf:"varint,3,opt,name=mobile_sync_policy,json=mobileSyncPolicy,proto3,enum=synch.v1.MobileSyncPolicy" json:"mobile_sync_policy,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SyncConfig) Reset() {
	*x = SyncConfig{}
	mi := &file_v1_synch_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncConfig) ProtoMessage() {}

func (x *SyncConfig) ProtoReflect() protoreflect.Message {
	mi := &file_v1_synch_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncConfig.ProtoReflect.Descriptor instead.
func (*SyncConfig) Descriptor() ([]byte, []int) {
	return file_v1_synch_proto_rawDescGZIP(), []int{4}
}

func (x *SyncConfig) GetConflictStrategy() ConflictStrategy {
	if x != nil {
		return x.ConflictStrategy
	}
	return ConflictStrategy_CONFLICT_STRATEGY_UNSPECIFIED
}

func (x *SyncConfig) GetBandwidthLimitKbps() uint32 {
	if x != nil {
		return x.BandwidthLimitKbps
	}
	return 0
}

func (x *SyncConfig) GetMobileSyncPolicy() MobileSyncPolicy {
	if x != nil {
		return x.MobileSyncPolicy
	}
	return MobileSyncPolicy_MOBILE_SYNC_POLICY_UNSPECIFIED
}

// Contract 节点间的交互契约
type Contract struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 契约唯一 ID: Blake3(req_pk + target_pk + timestamp)[0:16]
	ContractId string `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	// 发起方公钥 (Ed25519)
	RequesterId []byte `protobuf:"bytes,2,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	// 目标方公钥 (Ed25519)
	TargetId []byte `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	// 授权的能力列表
	Capabilities []string `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// 契约创建时间
	CreatedAt uint64 `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// 契约过期时间 (0 = 永不过期)
	ExpiresAt uint64 `protobuf:"varint,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// 续期策略: "auto", "prompt", "expire"
	RenewalPolicy string `protobuf:"bytes,7,opt,name=renewal_policy,json=renewalPolicy,proto3" json:"renewal_policy,omitempty"`
	// 契约当前状态
	Status ContractStatus `protobuf:"varint,8,opt,name=status,proto3,enum=synch.v1.ContractStatus" json:"status,omitempty"`
	// 发起方签名 (证明意愿)
	RequesterSignature []byte `protobuf:"bytes,9,opt,name=requester_signature,json=requesterSignature,proto3" json:"requester_signature,omitempty"`
	// 目标方签名 (完成握手)
	TargetSignature []byte `protobuf:"bytes,10,opt,name=target_signature,json=targetSignature,proto3" json:"target_signature,omitempty"`
	// 发起方配置的首选中继节点 URLs (如 ["wss://relay-a.local", "wss://public.synch"])
	RequesterRelays []string `protobuf:"bytes,11,rep,name=requester_relays,json=requesterRelays,proto3" json:"requester_relays,omitempty"`
	// 目标方配置的首选中继节点 URLs
	TargetRelays  []string `protobuf:"bytes,12,rep,name=target_relays,json=targetRelays,proto3" json:"target_relays,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contract) Reset() {
	*x = Contract{}
	mi := &file_v1_synch_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contract) ProtoMessage() {}

func (x *Contract) ProtoReflect() protoreflect.Message {
	mi := &file_v1_synch_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contract.ProtoReflect.Descriptor instead.
func (*Contract) Descriptor() ([]byte, []int) {
	return file_v1_synch_proto_rawDescGZIP(), []int{5}
}

func (x *Contract) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *Contract) GetRequesterId() []byte {
	if x != nil {
		return x.RequesterId
	}
	return nil
}

func (x *Contract) GetTargetId() []byte {
	if x != nil {
		return x.TargetId
	}
	return nil
}

func (x *Contract) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Contract) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Contract) GetExpiresAt() uint64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *Contract) GetRenewalPolicy() string {
	if x != nil {
		return x.RenewalPolicy
	}
	return ""
}

func (x *Contract) GetStatus() ContractStatus {
	if x != nil {
		return x.Status
	}
	return ContractStatus_CONTRACT_STATUS_UNSPECIFIED
}

func (x *Contract) GetRequesterSignature() []byte {
	if x != nil {
		return x.RequesterSignature
	}
	return nil
}

func (x *Contract) GetTargetSignature() []byte {
	if x != nil {
		return x.TargetSignature
	}
	return nil
}

func (x *Contract) GetRequesterRelays() []string {
	if x != nil {
		return x.RequesterRelays
	}
	return nil
}

func (x *Contract) GetTargetRelays() []string {
	if x != nil {
		return x.TargetRelays
	}
	return nil
}

// SecuredMessage 经过 E2EE 转换的消息封装
type SecuredMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 关联的契约 ID
	ContractId string `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	// 发送者指纹 (L2+ 感知层下解耦身份)
	SenderFingerprint string `protobuf:"bytes,2,opt,name=sender_fingerprint,json=senderFingerprint,proto3" json:"sender_fingerprint,omitempty"`
	// 消息层级加密载荷 (AES-256-GCM)
	Payload *EncryptedPayload `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// 消息发送时间
	Timestamp uint64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// 签名 (由发送方 identity 签名 header || payload)
	Signature     []byte `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecuredMessage) Reset() {
	*x = SecuredMessage{}
	mi := &file_v1_synch_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecuredMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecuredMessage) ProtoMessage() {}

func (x *SecuredMessage) ProtoReflect() protoreflect.Message {
	mi := &file_v1_synch_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecuredMessage.ProtoReflect.Descriptor instead.
func (*SecuredMessage) Descriptor() ([]byte, []int) {
	return file_v1_synch_proto_rawDescGZIP(), []int{6}
}

func (x *SecuredMessage) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *SecuredMessage) GetSenderFingerprint() string {
	if x != nil {
		return x.SenderFingerprint
	}
	return ""
}

func (x *SecuredMessage) GetPayload() *EncryptedPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SecuredMessage) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SecuredMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_v1_synch_proto protoreflect.FileDescriptor

const file_v1_synch_proto_rawDesc = "" +
	"\n" +
	"\x0ev1/synch.proto\x12\bsynch.v1\x1a\x0fv1/crypto.proto\"\xa4\x03\n" +
	"\fNodeIdentity\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\x12/\n" +
	"\tnode_type\x18\x03 \x01(\x0e2\x12.synch.v1.NodeTypeR\bnodeType\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities\x12#\n" +
	"\rregistered_at\x18\x06 \x01(\x04R\fregisteredAt\x12!\n" +
	"\fdisplay_name\x18\a \x01(\tR\vdisplayName\x12$\n" +
	"\x0eparent_node_id\x18\b \x01(\tR\fparentNodeId\x12@\n" +
	"\bmetadata\x18\t \x03(\v2$.synch.v1.NodeIdentity.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf9\x02\n" +
	"\x0eServerEndpoint\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12(\n" +
	"\x04role\x18\x03 \x01(\x0e2\x14.synch.v1.ServerRoleR\x04role\x12L\n" +
	"\fvault_access\x18\x04 \x03(\v2).synch.v1.ServerEndpoint.VaultAccessEntryR\vvaultAccess\x12!\n" +
	"\fdisplay_name\x18\x05 \x01(\tR\vdisplayName\x12!\n" +
	"\fauto_connect\x18\x06 \x01(\bR\vautoConnect\x12\x1f\n" +
	"\vinvite_code\x18\a \x01(\tR\n" +
	"inviteCode\x1aY\n" +
	"\x10VaultAccessEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.synch.v1.VaultPermissionR\x05value:\x028\x01\"\x8d\x01\n" +
	"\x0fVaultPermission\x12\x19\n" +
	"\bvault_id\x18\x01 \x01(\tR\avaultId\x12/\n" +
	"\x05level\x18\x02 \x01(\x0e2\x19.synch.v1.PermissionLevelR\x05level\x12.\n" +
	"\x13vault_key_encrypted\x18\x03 \x01(\fR\x11vaultKeyEncrypted\"\xae\x01\n" +
	"\rClientProfile\x122\n" +
	"\bidentity\x18\x01 \x01(\v2\x16.synch.v1.NodeIdentityR\bidentity\x122\n" +
	"\aservers\x18\x02 \x03(\v2\x18.synch.v1.ServerEndpointR\aservers\x125\n" +
	"\vsync_config\x18\x03 \x01(\v2\x14.synch.v1.SyncConfigR\n" +
	"syncConfig\"\xd1\x01\n" +
	"\n" +
	"SyncConfig\x12G\n" +
	"\x11conflict_strategy\x18\x01 \x01(\x0e2\x1a.synch.v1.ConflictStrategyR\x10conflictStrategy\x120\n" +
	"\x14bandwidth_limit_kbps\x18\x02 \x01(\rR\x12bandwidthLimitKbps\x12H\n" +
	"\x12mobile_sync_policy\x18\x03 \x01(\x0e2\x1a.synch.v1.MobileSyncPolicyR\x10mobileSyncPolicy\"\xd2\x03\n" +
	"\bContract\x12\x1f\n" +
	"\vcontract_id\x18\x01 \x01(\tR\n" +
	"contractId\x12!\n" +
	"\frequester_id\x18\x02 \x01(\fR\vrequesterId\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\fR\btargetId\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x04R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\x04R\texpiresAt\x12%\n" +
	"\x0erenewal_policy\x18\a \x01(\tR\rrenewalPolicy\x120\n" +
	"\x06status\x18\b \x01(\x0e2\x18.synch.v1.ContractStatusR\x06status\x12/\n" +
	"\x13requester_signature\x18\t \x01(\fR\x12requesterSignature\x12)\n" +
	"\x10target_signature\x18\n" +
	" \x01(\fR\x0ftargetSignature\x12)\n" +
	"\x10requester_relays\x18\v \x03(\tR\x0frequesterRelays\x12#\n" +
	"\rtarget_relays\x18\f \x03(\tR\ftargetRelays\"\xd2\x01\n" +
	"\x0eSecuredMessage\x12\x1f\n" +
	"\vcontract_id\x18\x01 \x01(\tR\n" +
	"contractId\x12-\n" +
	"\x12sender_fingerprint\x18\x02 \x01(\tR\x11senderFingerprint\x124\n" +
	"\apayload\x18\x03 \x01(\v2\x1a.synch.v1.EncryptedPayloadR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x04R\ttimestamp\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature*\xd3\x01\n" +
	"\bNodeType\x12\x19\n" +
	"\x15NODE_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fNODE_TYPE_AGENT\x10\x01\x12\x13\n" +
	"\x0fNODE_TYPE_HUMAN\x10\x02\x12\x14\n" +
	"\x10NODE_TYPE_BRIDGE\x10\x03\x12\x14\n" +
	"\x10NODE_TYPE_PLUGIN\x10\x04\x12\x14\n" +
	"\x10NODE_TYPE_MOBILE\x10\x05\x12\x13\n" +
	"\x0fNODE_TYPE_ADMIN\x10\x06\x12\x12\n" +
	"\x0eNODE_TYPE_LORD\x10\a\x12\x17\n" +
	"\x13NODE_TYPE_SUB_ADMIN\x10\b*\xb4\x01\n" +
	"\x0fPerceptionLevel\x12 \n" +
	"\x1cPERCEPTION_LEVEL_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13PERCEPTION_LEVEL_L0\x10\x00\x12\x17\n" +
	"\x13PERCEPTION_LEVEL_L1\x10\x01\x12\x17\n" +
	"\x13PERCEPTION_LEVEL_L2\x10\x02\x12\x17\n" +
	"\x13PERCEPTION_LEVEL_L3\x10\x03\x12\x17\n" +
	"\x13PERCEPTION_LEVEL_L4\x10\x04\x1a\x02\x10\x01*t\n" +
	"\n" +
	"ServerRole\x12\x1b\n" +
	"\x17SERVER_ROLE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SERVER_ROLE_PRIMARY\x10\x01\x12\x19\n" +
	"\x15SERVER_ROLE_SECONDARY\x10\x02\x12\x15\n" +
	"\x11SERVER_ROLE_GUEST\x10\x03*\x86\x01\n" +
	"\x0fPermissionLevel\x12 \n" +
	"\x1cPERMISSION_LEVEL_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PERMISSION_LEVEL_READ\x10\x01\x12\x1a\n" +
	"\x16PERMISSION_LEVEL_WRITE\x10\x02\x12\x1a\n" +
	"\x16PERMISSION_LEVEL_ADMIN\x10\x03*\x95\x01\n" +
	"\x10ConflictStrategy\x12!\n" +
	"\x1dCONFLICT_STRATEGY_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cCONFLICT_STRATEGY_AUTO_LOCAL\x10\x01\x12!\n" +
	"\x1dCONFLICT_STRATEGY_AUTO_REMOTE\x10\x02\x12\x19\n" +
	"\x15CONFLICT_STRATEGY_ASK\x10\x03*\x96\x01\n" +
	"\x10MobileSyncPolicy\x12\"\n" +
	"\x1eMOBILE_SYNC_POLICY_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19MOBILE_SYNC_POLICY_ALWAYS\x10\x01\x12 \n" +
	"\x1cMOBILE_SYNC_POLICY_WIFI_ONLY\x10\x02\x12\x1d\n" +
	"\x19MOBILE_SYNC_POLICY_MANUAL\x10\x03*\xc7\x01\n" +
	"\x0eContractStatus\x12\x1f\n" +
	"\x1bCONTRACT_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17CONTRACT_STATUS_PENDING\x10\x01\x12\x1a\n" +
	"\x16CONTRACT_STATUS_ACTIVE\x10\x02\x12\x1d\n" +
	"\x19CONTRACT_STATUS_SUSPENDED\x10\x03\x12\x1c\n" +
	"\x18CONTRACT_STATUS_EXPIRING\x10\x04\x12\x1e\n" +
	"\x1aCONTRACT_STATUS_TERMINATED\x10\x05B\x12Z\x10synch/v1;synchv1b\x06proto3"

var (
	file_v1_synch_proto_rawDescOnce sync.Once
	file_v1_synch_proto_rawDescData []byte
)

func file_v1_synch_proto_rawDescGZIP() []byte {
	file_v1_synch_proto_rawDescOnce.Do(func() {
		file_v1_synch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_synch_proto_rawDesc), len(file_v1_synch_proto_rawDesc)))
	})
	return file_v1_synch_proto_rawDescData
}

var file_v1_synch_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_v1_synch_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_v1_synch_proto_goTypes = []any{
	(NodeType)(0),            // 0: synch.v1.NodeType
	(PerceptionLevel)(0),     // 1: synch.v1.PerceptionLevel
	(ServerRole)(0),          // 2: synch.v1.ServerRole
	(PermissionLevel)(0),     // 3: synch.v1.PermissionLevel
	(ConflictStrategy)(0),    // 4: synch.v1.ConflictStrategy
	(MobileSyncPolicy)(0),    // 5: synch.v1.MobileSyncPolicy
	(ContractStatus)(0),      // 6: synch.v1.ContractStatus
	(*NodeIdentity)(nil),     // 7: synch.v1.NodeIdentity
	(*ServerEndpoint)(nil),   // 8: synch.v1.ServerEndpoint
	(*VaultPermission)(nil),  // 9: synch.v1.VaultPermission
	(*ClientProfile)(nil),    // 10: synch.v1.ClientProfile
	(*SyncConfig)(nil),       // 11: synch.v1.SyncConfig
	(*Contract)(nil),         // 12: synch.v1.Contract
	(*SecuredMessage)(nil),   // 13: synch.v1.SecuredMessage
	nil,                      // 14: synch.v1.NodeIdentity.MetadataEntry
	nil,                      // 15: synch.v1.ServerEndpoint.VaultAccessEntry
	(*EncryptedPayload)(nil), // 16: synch.v1.EncryptedPayload
}
var file_v1_synch_proto_depIdxs = []int32{
	0,  // 0: synch.v1.NodeIdentity.node_type:type_name -> synch.v1.NodeType
	14, // 1: synch.v1.NodeIdentity.metadata:type_name -> synch.v1.NodeIdentity.MetadataEntry
	2,  // 2: synch.v1.ServerEndpoint.role:type_name -> synch.v1.ServerRole
	15, // 3: synch.v1.ServerEndpoint.vault_access:type_name -> synch.v1.ServerEndpoint.VaultAccessEntry
	3,  // 4: synch.v1.VaultPermission.level:type_name -> synch.v1.PermissionLevel
	7,  // 5: synch.v1.ClientProfile.identity:type_name -> synch.v1.NodeIdentity
	8,  // 6: synch.v1.ClientProfile.servers:type_name -> synch.v1.ServerEndpoint
	11, // 7: synch.v1.ClientProfile.sync_config:type_name -> synch.v1.SyncConfig
	4,  // 8: synch.v1.SyncConfig.conflict_strategy:type_name -> synch.v1.ConflictStrategy
	5,  // 9: synch.v1.SyncConfig.mobile_sync_policy:type_name -> synch.v1.MobileSyncPolicy
	6,  // 10: synch.v1.Contract.status:type_name -> synch.v1.ContractStatus
	16, // 11: synch.v1.SecuredMessage.payload:type_name -> synch.v1.EncryptedPayload
	9,  // 12: synch.v1.ServerEndpoint.VaultAccessEntry.value:type_name -> synch.v1.VaultPermission
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_v1_synch_proto_init() }
func file_v1_synch_proto_init() {
	if File_v1_synch_proto != nil {
		return
	}
	file_v1_crypto_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_synch_proto_rawDesc), len(file_v1_synch_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_synch_proto_goTypes,
		DependencyIndexes: file_v1_synch_proto_depIdxs,
		EnumInfos:         file_v1_synch_proto_enumTypes,
		MessageInfos:      file_v1_synch_proto_msgTypes,
	}.Build()
	File_v1_synch_proto = out.File
	file_v1_synch_proto_goTypes = nil
	file_v1_synch_proto_depIdxs = nil
}
